#! /usr/bin/env python

def build(bld):

	bld(features  = 'javac',
		srcdir    = 'src',
		compat    = '1.7',
		use       = 'animals',
		name      = 'cats-src',
	)

	bld(features  = 'jar',
		basedir   = '.',
		destfile  = '../cats.jar',
		name      = 'cats',
		use       = 'cats-src'
	)

