#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    vehicle = bld.path.name
    bld.ap_stlib(
        name=vehicle + '_libs',
        ap_vehicle=vehicle,
        ap_libraries=bld.ap_common_vehicle_libraries() + [
            'APM_Control',
            'AP_Arming',
            'AP_L1_Control',
            'AP_Mount',
            'AP_Navigation',
            'AR_WPNav',
            'AP_RCMapper',
            'AP_Beacon',
            'AP_AdvancedFailsafe',
            'AP_WheelEncoder',
            'AP_SmartRTL',
            'AC_Fence',
            'AC_AttitudeControl',
            'AP_LTM_Telem',
            'AP_Devo_Telem',
            'AP_Follow',
            'AP_OSD',
            'AP_WindVane',
            'AP_Motors',
        ],
    )

    bld.ap_program(
        program_name='ardurover',
        program_groups=['bin', 'rover'],
        use=vehicle + '_libs',
    )
