#pragma once

#include <AP_HAL/AP_HAL_Boards.h>
#include <AP_Logger/AP_Logger_config.h>

/**
   maximum number of INS instances available on this platform. If more
   than 1 then redundant sensors may be available
 */

#ifndef AP_INERTIALSENSOR_ENABLED
#define AP_INERTIALSENSOR_ENABLED 1
#endif

#ifndef HAL_INS_TEMPERATURE_CAL_ENABLE
#define HAL_INS_TEMPERATURE_CAL_ENABLE HAL_PROGRAM_SIZE_LIMIT_KB > 1024
#endif

#ifndef AP_INERTIALSENSOR_HARMONICNOTCH_ENABLED
#define AP_INERTIALSENSOR_HARMONICNOTCH_ENABLED AP_INERTIALSENSOR_ENABLED
#endif

#ifndef AP_INERTIALSENSOR_ALLOW_NO_SENSORS
#define AP_INERTIALSENSOR_ALLOW_NO_SENSORS 0
#endif

// support for boards forcing on a third IMU instance in case the
// first two fail:
#ifndef AP_INERTIALSENSOR_FORCE_ENABLE_NONISOLATED_INSTANCE
#define AP_INERTIALSENSOR_FORCE_ENABLE_NONISOLATED_INSTANCE 0
#endif  // AP_INERTIALSENSOR_FORCE_ENABLE_NONISOLATED_INSTANCE

#ifndef AP_INERTIALSENSOR_BATCHSAMPLER_ENABLED
#define AP_INERTIALSENSOR_BATCHSAMPLER_ENABLED (AP_INERTIALSENSOR_ENABLED && HAL_LOGGING_ENABLED)
#endif

#ifndef AP_INERTIALSENSOR_KILL_IMU_ENABLED
#define AP_INERTIALSENSOR_KILL_IMU_ENABLED 1
#endif

#ifndef AP_INERTIALSENSOR_BACKEND_DEFAULT_ENABLED
#define AP_INERTIALSENSOR_BACKEND_DEFAULT_ENABLED 0
#endif  // AP_INERTIALSENSOR_BACKEND_DEFAULT_ENABLED

#ifndef AP_INERTIALSENSOR_RST_ENABLED
#define AP_INERTIALSENSOR_RST_ENABLED 0
#endif // AP_INERTIALSENSOR_RST_ENABLED

// Anello X3 FOG IMU: serial backend, selected by SERIALx_PROTOCOL = AnelloX3
#ifndef AP_INERTIALSENSOR_ANELLOX3_ENABLED
#define AP_INERTIALSENSOR_ANELLOX3_ENABLED (AP_INERTIALSENSOR_ENABLED && (HAL_PROGRAM_SIZE_LIMIT_KB > 1024))
#endif
