#include <AP_HAL/AP_HAL_Boards.h>
#include <GCS_MAVLink/GCS_config.h>

#ifndef AP_NETWORKING_ENABLED
#define AP_NETWORKING_ENABLED 0
#endif

#ifndef AP_NETWORKING_MAX_INSTANCES
#define AP_NETWORKING_MAX_INSTANCES 4
#endif

#ifndef AP_NETWORKING_ETHERNET_TCP_PAYLOAD_MAX_SIZE
#define AP_NETWORKING_ETHERNET_TCP_PAYLOAD_MAX_SIZE 1460 // 1500 (Eth MTU) - 20 (IP header) - 20 (TCP header)
#endif
#ifndef AP_NETWORKING_ETHERNET_UDP_PAYLOAD_MAX_SIZE
#define AP_NETWORKING_ETHERNET_UDP_PAYLOAD_MAX_SIZE 1472 // 1500 (Eth MTU) - 20 (IP header) - 8 (UDP header)
#endif

#ifndef AP_NETWORKING_ETH_IP_UDP_OVERHEAD
#define AP_NETWORKING_ETH_IP_UDP_OVERHEAD 51 // 23 (Eth frame) + 20 (IP header) + 8 (UDP header)
#endif

#ifndef AP_NETWORKING_SERIAL_ENABLED
#define AP_NETWORKING_SERIAL_ENABLED AP_NETWORKING_ENABLED && HAL_GCS_ENABLED
#endif

#ifndef AP_NETWORKING_SPEEDTEST_ENABLED
// Flash use: 1.5 KB
#define AP_NETWORKING_SPEEDTEST_ENABLED AP_NETWORKING_ENABLED
#endif

#ifndef AP_NETWORKING_LATENCYTEST_ENABLED
// Flash use: 568 Bytes
#define AP_NETWORKING_LATENCYTEST_ENABLED 0
#endif

#ifndef AP_NETWORKING_SNTP_ENABLED
// Flash use: 3.1 KB
#define AP_NETWORKING_SNTP_ENABLED 0
#endif

#ifndef AP_NETWORKING_SNTP_SERVERNAME
#define AP_NETWORKING_SNTP_SERVERNAME "pool.ntp.org"
#endif


#ifndef AP_NETWORKING_NETBIOS_ENABLED
// Flash use: 800 Bytes
#define AP_NETWORKING_NETBIOS_ENABLED 0
#endif
#ifndef AP_NETWORKING_NETBIOS_NAME
    // This string must be 15 (NETBIOS_NAME_LEN) or less characters
    #define AP_NETWORKING_NETBIOS_NAME "ARDUPILOT"
#endif

#ifndef AP_NETWORKING_TFTP_ENABLED
// Flash use: 1.85 KB
#define AP_NETWORKING_TFTP_ENABLED 0
#endif


#if CONFIG_HAL_BOARD == HAL_BOARD_CHIBIOS
    #define AP_NETWORKING_DHCP_AVAILABLE    LWIP_DHCP
#else
    #define AP_NETWORKING_DHCP_AVAILABLE    1 // for non-ChibiOS, assume it's available
#endif


// ---------------------------
// Below are default params
// ---------------------------

#ifndef AP_NETWORKING_DEFAULT_OPTIONS
    #define AP_NETWORKING_DEFAULT_OPTIONS 0
#endif

// Default DHCP
#ifndef AP_NETWORKING_DEFAULT_DHCP_ENABLE
#define AP_NETWORKING_DEFAULT_DHCP_ENABLE 0
#endif

// Default Static IP Address: 192.168.13.13
#ifndef AP_NETWORKING_DEFAULT_STATIC_IP_ADDR0
    #define AP_NETWORKING_DEFAULT_STATIC_IP_ADDR0   192
#endif
#ifndef AP_NETWORKING_DEFAULT_STATIC_IP_ADDR1
    #define AP_NETWORKING_DEFAULT_STATIC_IP_ADDR1   168
#endif
#ifndef AP_NETWORKING_DEFAULT_STATIC_IP_ADDR2
    #define AP_NETWORKING_DEFAULT_STATIC_IP_ADDR2   13
#endif
#ifndef AP_NETWORKING_DEFAULT_STATIC_IP_ADDR3
    #define AP_NETWORKING_DEFAULT_STATIC_IP_ADDR3   14
#endif


// Default Static IP Address: 192.168.13.1
#ifndef AP_NETWORKING_DEFAULT_STATIC_GW_ADDR0
    #define AP_NETWORKING_DEFAULT_STATIC_GW_ADDR0   192
#endif
#ifndef AP_NETWORKING_DEFAULT_STATIC_GW_ADDR1
    #define AP_NETWORKING_DEFAULT_STATIC_GW_ADDR1   168
#endif
#ifndef AP_NETWORKING_DEFAULT_STATIC_GW_ADDR2
    #define AP_NETWORKING_DEFAULT_STATIC_GW_ADDR2   13
#endif
#ifndef AP_NETWORKING_DEFAULT_STATIC_GW_ADDR3
    #define AP_NETWORKING_DEFAULT_STATIC_GW_ADDR3   1
#endif


// Default MAC Address: 2C:AF:51:03:CF:46
// Note, lower 3 bytes (ADDR3,4,5) will be replaced with the platform UUID 
#ifndef AP_NETWORKING_DEFAULT_MAC_ADDR0
    #define AP_NETWORKING_DEFAULT_MAC_ADDR0     0xC2 //LWIP_ETHADDR_0
#endif
#ifndef AP_NETWORKING_DEFAULT_MAC_ADDR1
    #define AP_NETWORKING_DEFAULT_MAC_ADDR1     0xAF //LWIP_ETHADDR_1
#endif
#ifndef AP_NETWORKING_DEFAULT_MAC_ADDR2
    #define AP_NETWORKING_DEFAULT_MAC_ADDR2     0x51 //LWIP_ETHADDR_2
#endif
#ifndef AP_NETWORKING_DEFAULT_MAC_ADDR3
    #define AP_NETWORKING_DEFAULT_MAC_ADDR3     0x03 //LWIP_ETHADDR_3
#endif
#ifndef AP_NETWORKING_DEFAULT_MAC_ADDR4
    #define AP_NETWORKING_DEFAULT_MAC_ADDR4     0xCF //LWIP_ETHADDR_4
#endif
#ifndef AP_NETWORKING_DEFAULT_MAC_ADDR5
    #define AP_NETWORKING_DEFAULT_MAC_ADDR5     0x46 //LWIP_ETHADDR_5
#endif



// Default Netmask: 24
// Note, the netmask is the number of consecutive bits
#ifndef AP_NETWORKING_DEFAULT_NETMASK
    #define AP_NETWORKING_DEFAULT_NETMASK       24 // 255.255.255.0
    // #define AP_NETWORKING_DEFAULT_NETMASK    16 // 255.255.0.0
#endif
