#include <AP_HAL/AP_HAL_Boards.h>
#include <AP_SerialManager/AP_SerialManager_config.h>
#include <AP_Filesystem/AP_Filesystem_config.h>
#include <GCS_MAVLink/GCS_config.h>

// ---------------------------
// Platform capability: lwIP availability
// lwIP doesn't work on macOS, Cygwin, or clang-on-Linux
// ---------------------------
#ifndef AP_NETWORKING_LWIP_AVAILABLE
#if defined(__APPLE__) || defined(__CYGWIN__) || defined(__CYGWIN64__) || defined(CYGWIN_BUILD)
#define AP_NETWORKING_LWIP_AVAILABLE 0
#elif defined(__clang__) && (CONFIG_HAL_BOARD == HAL_BOARD_SITL)
#define AP_NETWORKING_LWIP_AVAILABLE 0
#else
#define AP_NETWORKING_LWIP_AVAILABLE 1
#endif
#endif

// ---------------------------
// Hardware flags (set by hwdef)
// ---------------------------
#ifndef AP_NETWORKING_BACKEND_IS_MAC_GATEWAY
#define AP_NETWORKING_BACKEND_IS_MAC_GATEWAY 0
#endif
#ifndef AP_NETWORKING_BACKEND_IS_MAC_GATEWAY_CLIENT
#define AP_NETWORKING_BACKEND_IS_MAC_GATEWAY_CLIENT 0
#endif

// MAC gateway configurations require networking
#if (AP_NETWORKING_BACKEND_IS_MAC_GATEWAY || AP_NETWORKING_BACKEND_IS_MAC_GATEWAY_CLIENT) && \
    !defined(AP_NETWORKING_ENABLED)
#define AP_NETWORKING_ENABLED 1
#endif

#if defined(AP_NETWORKING_BACKEND_PPP) && !defined(AP_NETWORKING_ENABLED)
// allow --enable-PPP to enable networking
#define AP_NETWORKING_ENABLED AP_NETWORKING_BACKEND_PPP
#endif


#ifndef AP_NETWORKING_ENABLED
#if !defined(__APPLE__) && defined(__clang__)
// clang fails on linux
#define AP_NETWORKING_ENABLED 0
#else
#define AP_NETWORKING_ENABLED ((CONFIG_HAL_BOARD == HAL_BOARD_LINUX) || (CONFIG_HAL_BOARD == HAL_BOARD_SITL))
#endif
#endif

#ifndef AP_NETWORKING_BACKEND_DEFAULT_ENABLED
#define AP_NETWORKING_BACKEND_DEFAULT_ENABLED AP_NETWORKING_ENABLED
#endif

// ---------------------------
// Backends
// ---------------------------
#ifndef AP_NETWORKING_BACKEND_CHIBIOS
#ifndef HAL_USE_MAC
#define HAL_USE_MAC 0
#endif
#define AP_NETWORKING_BACKEND_CHIBIOS (AP_NETWORKING_BACKEND_DEFAULT_ENABLED && (CONFIG_HAL_BOARD == HAL_BOARD_CHIBIOS) && HAL_USE_MAC)
#endif

#if !defined(AP_NETWORKING_BACKEND_PPP)
#define AP_NETWORKING_BACKEND_PPP (AP_NETWORKING_BACKEND_DEFAULT_ENABLED && (CONFIG_HAL_BOARD == HAL_BOARD_CHIBIOS) && !HAL_USE_MAC)
#endif

#ifndef AP_NETWORKING_BACKEND_SITL
#define AP_NETWORKING_BACKEND_SITL (AP_NETWORKING_BACKEND_DEFAULT_ENABLED && (CONFIG_HAL_BOARD == HAL_BOARD_SITL))
#endif

#ifndef AP_NETWORKING_SOCKETS_ENABLED
#define AP_NETWORKING_SOCKETS_ENABLED AP_NETWORKING_ENABLED
#endif

// ---------------------------
// Switch Architecture
// ---------------------------
#ifndef AP_NETWORKING_BACKEND_SWITCHPORT_COBS
#define AP_NETWORKING_BACKEND_SWITCHPORT_COBS \
    (AP_NETWORKING_BACKEND_IS_MAC_GATEWAY || AP_NETWORKING_BACKEND_IS_MAC_GATEWAY_CLIENT)
#endif

#ifndef AP_NETWORKING_BACKEND_SWITCHPORT_ETHERNET
#define AP_NETWORKING_BACKEND_SWITCHPORT_ETHERNET \
    (AP_NETWORKING_BACKEND_IS_MAC_GATEWAY || ((CONFIG_HAL_BOARD == HAL_BOARD_CHIBIOS) && HAL_USE_MAC))
#endif

#ifndef AP_NETWORKING_BACKEND_SWITCHPORT_LWIP
// lwIP switchport - for MAC gateway clients, NOT enabled on SITL by default
// (SITL uses native sockets by default for compatibility)
#define AP_NETWORKING_BACKEND_SWITCHPORT_LWIP \
    (AP_NETWORKING_LWIP_AVAILABLE && AP_NETWORKING_BACKEND_IS_MAC_GATEWAY_CLIENT)
#endif

#ifndef AP_NETWORKING_BACKEND_SWITCHPORT_MAVLINK_COBS
// MAVLink COBS - disabled by default, can be enabled for SITL testing
#define AP_NETWORKING_BACKEND_SWITCHPORT_MAVLINK_COBS 0
#endif

#ifndef AP_NETWORKING_BACKEND_SWITCH
#if defined(HAL_BOOTLOADER_BUILD)
#define AP_NETWORKING_BACKEND_SWITCH 0
#elif (CONFIG_HAL_BOARD == HAL_BOARD_CHIBIOS) && \
      (AP_NETWORKING_BACKEND_SWITCHPORT_COBS || AP_NETWORKING_BACKEND_SWITCHPORT_ETHERNET)
#define AP_NETWORKING_BACKEND_SWITCH 1
#else
#define AP_NETWORKING_BACKEND_SWITCH 0
#endif
#endif

// Force switch ports off if switch is disabled
#if !AP_NETWORKING_BACKEND_SWITCH
#undef AP_NETWORKING_BACKEND_SWITCHPORT_COBS
#undef AP_NETWORKING_BACKEND_SWITCHPORT_ETHERNET
#undef AP_NETWORKING_BACKEND_SWITCHPORT_LWIP
#undef AP_NETWORKING_BACKEND_SWITCHPORT_MAVLINK_COBS
#define AP_NETWORKING_BACKEND_SWITCHPORT_COBS 0
#define AP_NETWORKING_BACKEND_SWITCHPORT_ETHERNET 0
#define AP_NETWORKING_BACKEND_SWITCHPORT_LWIP 0
#define AP_NETWORKING_BACKEND_SWITCHPORT_MAVLINK_COBS 0
#endif

#ifndef AP_NETWORKING_SWITCHPORT_MAX_INSTANCES
#define AP_NETWORKING_SWITCHPORT_MAX_INSTANCES 8
#endif

#ifndef AP_NETWORKING_SWITCH_SWITCHING_ENABLED
#define AP_NETWORKING_SWITCH_SWITCHING_ENABLED AP_NETWORKING_BACKEND_SWITCH
#endif

#ifndef AP_NETWORKING_SWITCH_MAC_TABLE_SIZE
#define AP_NETWORKING_SWITCH_MAC_TABLE_SIZE 64
#endif

#ifndef AP_NETWORKING_SWITCH_MAC_AGE_MS
#define AP_NETWORKING_SWITCH_MAC_AGE_MS 300000
#endif

#ifndef AP_NETWORKING_BACKEND_SWITCHPORT_COBS_BOND_INSTANCE_MAX
#define AP_NETWORKING_BACKEND_SWITCHPORT_COBS_BOND_INSTANCE_MAX 2
#endif

#ifndef AP_NETWORKING_COBS_MAX_BOND_MEMBERS
#define AP_NETWORKING_COBS_MAX_BOND_MEMBERS 4
#endif

#ifndef AP_NETWORKING_CAPTURE_ENABLED
#define AP_NETWORKING_CAPTURE_ENABLED \
    (AP_NETWORKING_BACKEND_SWITCH && AP_FILESYSTEM_FILE_WRITING_ENABLED)
#endif

// Show serial manager params on periph if COBS is enabled
#if defined(HAL_BUILD_AP_PERIPH) && !defined(HAL_PERIPH_SHOW_SERIAL_MANAGER_PARAMS) && \
    AP_NETWORKING_BACKEND_SWITCHPORT_COBS
#define HAL_PERIPH_SHOW_SERIAL_MANAGER_PARAMS 1
#endif

#ifndef AP_NETWORKING_CONTROLS_HOST_IP_SETTINGS_ENABLED
// AP_NETWORKING_CONTROLS_HOST_IP_SETTINGS_ENABLED should only be true if we have the ability to
// change the IP address. If not then the IP, GW, NetMask, MAC and DHCP params are hidden. 
// This does not mean that the system/OS does not have the ability to set the IP, just that
// we have no control from this scope. For example, Linux systems (including SITL) have
// their own DHCP client running but we have no control over it.
// When using Switch with lwIP on SITL, we control the IP address within lwIP.
#define AP_NETWORKING_CONTROLS_HOST_IP_SETTINGS_ENABLED \
    (AP_NETWORKING_BACKEND_CHIBIOS || AP_NETWORKING_BACKEND_SWITCHPORT_LWIP)
#endif

#ifndef AP_NETWORKING_CONTROLS_HOST_MAC_SETTINGS_ENABLED
#define AP_NETWORKING_CONTROLS_HOST_MAC_SETTINGS_ENABLED \
    ((AP_NETWORKING_BACKEND_CHIBIOS && HAL_USE_MAC) || AP_NETWORKING_BACKEND_SWITCHPORT_LWIP)
#endif

// MAC gateway overrides
#if AP_NETWORKING_BACKEND_IS_MAC_GATEWAY
#undef AP_NETWORKING_CONTROLS_HOST_IP_SETTINGS_ENABLED
#undef AP_NETWORKING_CONTROLS_HOST_MAC_SETTINGS_ENABLED
#define AP_NETWORKING_CONTROLS_HOST_IP_SETTINGS_ENABLED 0
#define AP_NETWORKING_CONTROLS_HOST_MAC_SETTINGS_ENABLED 0
#endif
#if AP_NETWORKING_BACKEND_IS_MAC_GATEWAY_CLIENT
#undef AP_NETWORKING_CONTROLS_HOST_IP_SETTINGS_ENABLED
#undef AP_NETWORKING_CONTROLS_HOST_MAC_SETTINGS_ENABLED
#define AP_NETWORKING_CONTROLS_HOST_IP_SETTINGS_ENABLED 1
#define AP_NETWORKING_CONTROLS_HOST_MAC_SETTINGS_ENABLED 1
#endif

#define AP_NETWORKING_NEED_LWIP \
    (AP_NETWORKING_BACKEND_CHIBIOS || AP_NETWORKING_BACKEND_PPP || AP_NETWORKING_BACKEND_SWITCHPORT_LWIP)

// Native sockets vs lwIP sockets
// On SITL, use native sockets by default UNLESS PPP is enabled.
// PPP creates an interface in lwIP, so sockets must use lwIP to see it.
#ifndef AP_NETWORKING_SOCKETS_NATIVE
#if CONFIG_HAL_BOARD == HAL_BOARD_SITL && !AP_NETWORKING_BACKEND_PPP
#define AP_NETWORKING_SOCKETS_NATIVE 1
#else
#define AP_NETWORKING_SOCKETS_NATIVE 0
#endif
#endif

// ---------------------------
// IP Features
// ---------------------------
#ifndef AP_NETWORKING_DHCP_AVAILABLE
// AP_NETWORKING_DHCP_AVAILABLE should only be true if, by setting the NET_DHCP parameter,
// we have the ability to turn on/off the DHCP client which effects the assigned IP address.
// Otherwise, param NET_DHCP will be hidden. This does not mean that the system/OS does not
// have DHCP, just that we have no control from this scope. For example, Linux systems
// (including SITL) have their own DHCP client running but we have no control over it.
#define AP_NETWORKING_DHCP_AVAILABLE (AP_NETWORKING_CONTROLS_HOST_IP_SETTINGS_ENABLED || AP_NETWORKING_BACKEND_CHIBIOS)
#endif


// ---------------------------
// Below are default params
// ---------------------------

// Default DHCP
#ifndef AP_NETWORKING_DEFAULT_DHCP_ENABLE
#define AP_NETWORKING_DEFAULT_DHCP_ENABLE AP_NETWORKING_DHCP_AVAILABLE
#endif

// Default Static IP Address: 192.168.144.14
#ifndef AP_NETWORKING_DEFAULT_STATIC_IP_ADDR
#define AP_NETWORKING_DEFAULT_STATIC_IP_ADDR "192.168.144.14"
#endif

// Default Netmask: 24
// Note, the netmask is the number of consecutive bits
#ifndef AP_NETWORKING_DEFAULT_NETMASK
#define AP_NETWORKING_DEFAULT_NETMASK       24 // 255.255.255.0 (for 10.0.xxx.xxx or 172.xxx.xxx.xxx type networks)
// #define AP_NETWORKING_DEFAULT_NETMASK    16 // 255.255.0.0 (for 192.168.xxx.xxxx type networks)
#endif


// Default Static IP Address: 192.168.144.1
#ifndef AP_NETWORKING_DEFAULT_STATIC_GW_ADDR
#define AP_NETWORKING_DEFAULT_STATIC_GW_ADDR "192.168.144.1"
#endif

// Default MAC Address: C2:AF:51:03:CF:46
// Note, lower 3 bytes (ADDR3,4,5) will be replaced with the platform UUID
#ifndef AP_NETWORKING_DEFAULT_MAC_ADDR
#define AP_NETWORKING_DEFAULT_MAC_ADDR "C2:AF:51:03:CF:46"
#endif

#ifndef AP_NETWORKING_TESTS_ENABLED
#define AP_NETWORKING_TESTS_ENABLED 0
#endif

#ifndef AP_NETWORKING_CAN_MCAST_ENABLED
#define AP_NETWORKING_CAN_MCAST_ENABLED 0
#endif

#ifndef AP_NETWORKING_CAN_MCAST_BRIDGING_ENABLED
#define AP_NETWORKING_CAN_MCAST_BRIDGING_ENABLED AP_NETWORKING_CAN_MCAST_ENABLED
#endif

#if AP_NETWORKING_TESTS_ENABLED
#ifndef AP_NETWORKING_TEST_IP
#define AP_NETWORKING_TEST_IP "192.168.144.2"
#endif
#endif

#ifndef AP_NETWORKING_NUM_PORTS
#if AP_NETWORKING_BACKEND_IS_MAC_GATEWAY
#define AP_NETWORKING_NUM_PORTS 0
#else
#define AP_NETWORKING_NUM_PORTS 4
#endif
#endif

#ifndef AP_NETWORKING_PORT_STACK_SIZE
#define AP_NETWORKING_PORT_STACK_SIZE 1300
#endif

#ifndef AP_NETWORKING_UDP_SERVER_MULTI_CLIENT_MAX
#define AP_NETWORKING_UDP_SERVER_MULTI_CLIENT_MAX 10
#endif

#ifndef AP_NETWORKING_UDP_SERVER_MULTI_CLIENT_TIMEOUT_MS
#define AP_NETWORKING_UDP_SERVER_MULTI_CLIENT_TIMEOUT_MS 10000
#endif

#ifndef AP_NETWORKING_UDP_SERVER_MULTI_CLIENT_ANNOUNCE_CLIENT_CONNECT_DISCONNECT
#define AP_NETWORKING_UDP_SERVER_MULTI_CLIENT_ANNOUNCE_CLIENT_CONNECT_DISCONNECT 1
#endif

// Default IP stack enable (lwIP)
#ifndef AP_NETWORKING_DEFAULT_IP_ENABLE
#define AP_NETWORKING_DEFAULT_IP_ENABLE (CONFIG_HAL_BOARD != HAL_BOARD_SITL)
#endif

#ifndef AP_NETWORKING_NUM_SENDFILES
#define AP_NETWORKING_NUM_SENDFILES 20
#endif

#ifndef AP_NETWORKING_SENDFILE_BUFSIZE
#define AP_NETWORKING_SENDFILE_BUFSIZE (64*512)
#endif

#ifndef AP_NETWORKING_PPP_GATEWAY_ENABLED
#define AP_NETWORKING_PPP_GATEWAY_ENABLED \
    (AP_NETWORKING_BACKEND_PPP && (AP_NETWORKING_BACKEND_CHIBIOS || AP_NETWORKING_BACKEND_SWITCH))
#endif

/*
  the IP address given to the remote end of the PPP link when running
  as a PPP<->ethernet gateway. If this is on the same subnet as the
  ethernet interface IP then proxyarp will be used
 */
#ifndef AP_NETWORKING_REMOTE_PPP_IP
#define AP_NETWORKING_REMOTE_PPP_IP "0.0.0.0"
#endif

#ifndef AP_NETWORKING_REGISTER_PORT_ENABLED
#define AP_NETWORKING_REGISTER_PORT_ENABLED AP_NETWORKING_ENABLED && AP_SERIALMANAGER_REGISTER_ENABLED
#endif

