#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2010 (ita)

"""
scala example
"""

VERSION = '0.0.1'
APPNAME = 'scala_test'

top = '.'

def configure(conf):
	conf.load('scala')
	try:
		conf.load('java')
	except:
		pass

def build(bld):

	bld(features   = 'scalac',    # there are scala files to process
		srcdir     = '.',         # folder containing the sources to compile
		outdir     = 'out',       # folder where to output the classes (in the build directory)
		classpath  = ['.', '..'],
		name       = 'scala_one'
		)

	if bld.env.JAR:
		bld(
			features  = 'jar',
			basedir   = 'out',
			destfile  = 'filez.jar',
			use       = 'scala_one'
		)

