#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2010 (ita)

top = '.'
out = 'build'

def options(opt):
	opt.load('compiler_c')
	opt.load('errcheck')

def configure(conf):
	conf.load('compiler_c')

def build(bld):
	bld(feature='c cprogram', source='main.c', target='app1')
	bld.program(sources='main.c', target='app2')
	bld.program(source='main.c', targets='app3')
	bld.program(source='main.c', target='app4', include='.')
	bld.program(source='main.c', target='app5', define='x=1')
