// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// osd_tx_pal //
// ---------- //

#define osd_tx_pal_wrap_target 0
#define osd_tx_pal_wrap 30
#define osd_tx_pal_pio_version 1

#define osd_tx_pal_offset_loop_hsync 8u

static const uint16_t osd_tx_pal_program_instructions[] = {
            //     .wrap_target
    0xc000, //  0: irq    nowait 0
    0x20a0, //  1: wait   1 pin, 0
    0x2020, //  2: wait   0 pin, 0
    0xec56, //  3: set    y, 22                  [12]
    0x1f84, //  4: jmp    y--, 4                 [31]
    0x00c1, //  5: jmp    pin, 1
    0x20a0, //  6: wait   1 pin, 0
    0xe030, //  7: set    x, 16
    0xe04f, //  8: set    y, 15
    0x2920, //  9: wait   0 pin, 0               [9]
    0x0e8a, // 10: jmp    y--, 10                [14]
    0x00c8, // 11: jmp    pin, 8
    0xe058, // 12: set    y, 24
    0x1a8d, // 13: jmp    y--, 13                [26]
    0x00d0, // 14: jmp    pin, 16
    0x0008, // 15: jmp    8
    0x0048, // 16: jmp    x--, 8
    0xa026, // 17: mov    x, isr
    0x2020, // 18: wait   0 pin, 0
    0xec5a, // 19: set    y, 26                  [12]
    0x1d94, // 20: jmp    y--, 20                [29]
    0x00d7, // 21: jmp    pin, 23
    0x0000, // 22: jmp    0
    0xe056, // 23: set    y, 22
    0x8080, // 24: pull   noblock
    0x6002, // 25: out    pins, 2
    0x06fc, // 26: jmp    !osre, 28              [6]
    0x0098, // 27: jmp    y--, 24
    0x01f9, // 28: jmp    !osre, 25              [1]
    0xe000, // 29: set    pins, 0
    0x0052, // 30: jmp    x--, 18
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program osd_tx_pal_program = {
    .instructions = osd_tx_pal_program_instructions,
    .length = 31,
    .origin = -1,
    .pio_version = osd_tx_pal_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config osd_tx_pal_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + osd_tx_pal_wrap_target, offset + osd_tx_pal_wrap);
    return c;
}
#endif

// ----------- //
// osd_tx_ntsc //
// ----------- //

#define osd_tx_ntsc_wrap_target 0
#define osd_tx_ntsc_wrap 30
#define osd_tx_ntsc_pio_version 1

static const uint16_t osd_tx_ntsc_program_instructions[] = {
            //     .wrap_target
    0xc000, //  0: irq    nowait 0
    0x20a0, //  1: wait   1 pin, 0
    0x2020, //  2: wait   0 pin, 0
    0xec56, //  3: set    y, 22                  [12]
    0x1f84, //  4: jmp    y--, 4                 [31]
    0x00c1, //  5: jmp    pin, 1
    0x20a0, //  6: wait   1 pin, 0
    0xe030, //  7: set    x, 16
    0xe04f, //  8: set    y, 15
    0x2920, //  9: wait   0 pin, 0               [9]
    0x0e8a, // 10: jmp    y--, 10                [14]
    0x00c8, // 11: jmp    pin, 8
    0xe058, // 12: set    y, 24
    0x1a8d, // 13: jmp    y--, 13                [26]
    0x00d0, // 14: jmp    pin, 16
    0x0008, // 15: jmp    8
    0x0048, // 16: jmp    x--, 8
    0xa026, // 17: mov    x, isr
    0x2020, // 18: wait   0 pin, 0
    0xe859, // 19: set    y, 25                  [8]
    0x1d94, // 20: jmp    y--, 20                [29]
    0x00d7, // 21: jmp    pin, 23
    0x0000, // 22: jmp    0
    0xe056, // 23: set    y, 22
    0x8080, // 24: pull   noblock
    0x6002, // 25: out    pins, 2
    0x06fc, // 26: jmp    !osre, 28              [6]
    0x0098, // 27: jmp    y--, 24
    0x01f9, // 28: jmp    !osre, 25              [1]
    0xe000, // 29: set    pins, 0
    0x0052, // 30: jmp    x--, 18
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program osd_tx_ntsc_program = {
    .instructions = osd_tx_ntsc_program_instructions,
    .length = 31,
    .origin = -1,
    .pio_version = osd_tx_ntsc_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config osd_tx_ntsc_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + osd_tx_ntsc_wrap_target, offset + osd_tx_ntsc_wrap);
    return c;
}
#endif

// -------------- //
// osd_count_sync //
// -------------- //

#define osd_count_sync_wrap_target 0
#define osd_count_sync_wrap 24
#define osd_count_sync_pio_version 1

#define osd_count_sync_offset_ready 1u

static const uint16_t osd_count_sync_program_instructions[] = {
            //     .wrap_target
    0x4060, //  0: in     null, 32
    0x80a0, //  1: pull   block
    0x20a0, //  2: wait   1 pin, 0
    0x2020, //  3: wait   0 pin, 0
    0xe02e, //  4: set    x, 14
    0x1c45, //  5: jmp    x--, 5                 [28]
    0x00c2, //  6: jmp    pin, 2
    0x6040, //  7: out    y, 32
    0xa0e2, //  8: mov    osr, y
    0x20a0, //  9: wait   1 pin, 0
    0x2020, // 10: wait   0 pin, 0
    0xe028, // 11: set    x, 8
    0x1c4c, // 12: jmp    x--, 12                [28]
    0x00ca, // 13: jmp    pin, 10
    0xe025, // 14: set    x, 5
    0x1c4f, // 15: jmp    x--, 15                [28]
    0x00d7, // 16: jmp    pin, 23
    0x6020, // 17: out    x, 32
    0xa0e1, // 18: mov    osr, x
    0x00b5, // 19: jmp    x != y, 21
    0x000a, // 20: jmp    10
    0x4040, // 21: in     y, 32
    0x0001, // 22: jmp    1
    0x008a, // 23: jmp    y--, 10
    0x0002, // 24: jmp    2
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program osd_count_sync_program = {
    .instructions = osd_count_sync_program_instructions,
    .length = 25,
    .origin = -1,
    .pio_version = osd_count_sync_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config osd_count_sync_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + osd_count_sync_wrap_target, offset + osd_count_sync_wrap);
    return c;
}
#endif

