// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------- //
// uart_tx //
// ------- //

#define uart_tx_wrap_target 0
#define uart_tx_wrap 9
#define uart_tx_pio_version 0

static const uint16_t uart_tx_program_instructions[] = {
            //     .wrap_target
    0xe080, //  0: set    pindirs, 0
    0x80a0, //  1: pull   block
    0xf681, //  2: set    pindirs, 1      side 0 [6]
    0xe027, //  3: set    x, 7
    0x6001, //  4: out    pins, 1
    0x0644, //  5: jmp    x--, 4                 [6]
    0x1d68, //  6: jmp    !y, 8           side 1 [5]
    0xbf42, //  7: nop                    side 1 [7]
    0xa025, //  8: mov    x, status
    0x0021, //  9: jmp    !x, 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program uart_tx_program = {
    .instructions = uart_tx_program_instructions,
    .length = 10,
    .origin = 0,
    .pio_version = uart_tx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config uart_tx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + uart_tx_wrap_target, offset + uart_tx_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    sm_config_set_mov_status(&c, STATUS_TX_LESSTHAN, 1);
    return c;
}
#endif

// ------- //
// uart_rx //
// ------- //

#define uart_rx_wrap_target 0
#define uart_rx_wrap 8
#define uart_rx_pio_version 0

static const uint16_t uart_rx_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0
    0xea27, //  1: set    x, 7                   [10]
    0x4001, //  2: in     pins, 1
    0x0642, //  3: jmp    x--, 2                 [6]
    0x00c8, //  4: jmp    pin, 8
    0xc014, //  5: irq    nowait 4 rel
    0x20a0, //  6: wait   1 pin, 0
    0x0000, //  7: jmp    0
    0x8020, //  8: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program uart_rx_program = {
    .instructions = uart_rx_program_instructions,
    .length = 9,
    .origin = 10,
    .pio_version = uart_rx_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config uart_rx_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + uart_rx_wrap_target, offset + uart_rx_wrap);
    return c;
}
#endif

// ------------ //
// uart_rx_sbus //
// ------------ //

#define uart_rx_sbus_wrap_target 0
#define uart_rx_sbus_wrap 9
#define uart_rx_sbus_pio_version 0

static const uint16_t uart_rx_sbus_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0
    0xea27, //  1: set    x, 7                   [10]
    0x4001, //  2: in     pins, 1
    0x0642, //  3: jmp    x--, 2                 [6]
    0xa642, //  4: nop                           [6]
    0x00c9, //  5: jmp    pin, 9
    0xc014, //  6: irq    nowait 4 rel
    0x20a0, //  7: wait   1 pin, 0
    0x0000, //  8: jmp    0
    0x8020, //  9: push   block
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program uart_rx_sbus_program = {
    .instructions = uart_rx_sbus_program_instructions,
    .length = 10,
    .origin = 19,
    .pio_version = uart_rx_sbus_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config uart_rx_sbus_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + uart_rx_sbus_wrap_target, offset + uart_rx_sbus_wrap);
    return c;
}
#endif

