#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    vehicle = bld.path.name
    bld.ap_stlib(
        name=vehicle + '_libs',
        vehicle=vehicle,
        libraries=bld.ap_common_vehicle_libraries() + [
            'PID',
        ],
        use='mavlink',
    )

    bld.ap_program(
        program_name='antennatracker',
        use=vehicle + '_libs',
    )
