#! /usr/bin/env python


INCLUDES = [
    '.',
   # '../lib/'
]

def build(bld):

    bld.shlib(
        target='libex',
        source='libex.c',
        includes=INCLUDES,
        export_includes=INCLUDES,
        install_path=bld.env.LIBDIR,
        use='lib'
        )

   