# See https://pre-commit.com for more information, specially https://pre-commit.com/#pre-commit-run for manual trigger
# Some example useful invocations:
#  pre-commit run: this is what pre-commit runs by default when committing. This will run all hooks against currently staged files.
#  pre-commit run --all-files: run all the hooks against all the files. This is a useful invocation if you are using pre-commit in CI.
#  pre-commit run check-executables-have-shebangs: run the check-executables-have-shebangs hook against all staged files.

# Files or directory we want to exclude from checking
exclude: |
  (?x)(
    ^modules/ |
    ^build/ |
    ^cmake-build-debug/ |
    \.m |
    ^libraries/AP_HAL_ChibiOS/hwdef/scripts/
  )

repos:
  - repo: local
    hooks:
      - id: check-added-large-files
        name: Check for added large files
        entry: check-added-large-files
        language: python
        additional_dependencies: [pre-commit-hooks==6.0.0]
      #- id: check-executables-have-shebangs
      #  name: Check executables have shebangs
      #  entry: check-executables-have-shebangs
      #  language: python
      #  additional_dependencies: [pre-commit-hooks==6.0.0]
      - id: check-shebang-scripts-are-executable
        name: Check shebang scripts are executable
        entry: check-shebang-scripts-are-executable
        language: python
        additional_dependencies: [pre-commit-hooks==6.0.0]
        exclude: |
          (?x)^(
            .*\/wscript |
            wscript
          )$
      - id: check-merge-conflict
        name: Check for merge conflicts
        entry: check-merge-conflict
        language: python
        additional_dependencies: [pre-commit-hooks==6.0.0]
      - id: check-xml
        name: Check XML files
        entry: check-xml
        language: python
        additional_dependencies: [pre-commit-hooks==6.0.0]
        types: [xml]
      - id: check-yaml
        name: Check YAML files
        entry: check-yaml
        language: python
        additional_dependencies: [pre-commit-hooks==6.0.0]
        types: [yaml]
      - id: mixed-line-ending
        name: Check line ending character (LF)
        entry: mixed-line-ending
        language: python
        additional_dependencies: [pre-commit-hooks==6.0.0]
        args: ["--fix=lf"]
        types_or: [python, c, c++, shell]
        exclude: |
          (?x)^(
            libraries/AP_ADSB/AP_ADSB_Sagetech_MXS.cpp |
            libraries/AP_ADSB/AP_ADSB_Sagetech_MXS.h
          )$
      # - id: end-of-file-fixer
      # - id: trailing-whitespace

      - id: ament-pep257
        name: Run ament_pep257 on Tools/ros2
        entry: bash -c 'ament_pep257 Tools/ros2 > /dev/null'
        language: python
        additional_dependencies:
          - ament-lint-pep257
          - tomli;python_version<'3.11'
        pass_filenames: false
        files: ^Tools/ros2/

      - id: black
        name: black
        entry: black
        language: python
        additional_dependencies: [black==25.1.0]
        files: |
          (?x)^(
            libraries\/AP_DDS\/(wscript|.*\.py)$ |
            Tools/ros2/.*\.py
          )$

      - id: check-copyright
        name: check copyright notice in files
        entry: Tools/gittools/pre_commit_copyright.py
        language: python
        files: |
          (?x)^(
            Tools/ros2/.*\.py
          )$
        args: [
          --ignore=Tools/ros2/ardupilot_dds_tests/setup.py,
          --ignore=Tools/ros2/ardupilot_dds_tests/test/test_pep257.py,
          --ignore=Tools/ros2/ardupilot_dds_tests/test/test_copyright.py,
        ]

      - id: codespell
        name: codespell  # See pyproject.toml for args
        entry: codespell
        language: python
        additional_dependencies:
          - codespell==2.4.2
          - tomli
        types_or: [python]
        args:
          - --ignore-words-list=afile,bodgy,chek,commitish,edn,empy,finis,fram,mot,ned,parm,releas,parms,rin,ser,sitl,siz

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        additional_dependencies: [flake8==7.3.0]
        types: [python]

      - id: ruff-check
        name: ruff check
        entry: ruff check
        language: python
        additional_dependencies: [ruff==0.15.8]
        types: [python]

      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        args: [--severity=error]
        types: [shell]

# # Use to sort python imports by name and put system import first.
#   - repo: local
#     hooks:
#       - id: isort
#         name: isort (python)
#         entry: isort
#         language: python
#         additional_dependencies: [isort==5.12.0]
#         args: [--check-only]

# # Use to check python typing to show errors.
#   - repo: local
#     hooks:
#       - id: mypy
#         name: mypy
#         entry: mypy
#         language: python
#         additional_dependencies: [mypy, types-PyYAML, types-requests]
#         args: [--no-strict-optional, --ignore-missing-imports]
