#!/bin/bash
key="$1"
if [ "$key" == "debug" ]; then
	scp build/linux-debug/examples/* root@192.168.1.158:/home/root/build/debug
else
	scp build/linux/examples/* root@192.168.1.158:/home/root/build
fi

