#!/usr/bin/env python
# encoding: utf-8

from waflib.TaskGen import extension

top = '.'
out = 'build'


@extension('.py', 'wscript')
def check_syntax(self, node):
    self.create_task('Pep8', node)


def options(opt):
    opt.load('pep8')


def configure(conf):
    # warning after this comment
    
    conf.load('pep8')


def build(bld):
    bld(source='wscript')
