#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    if not bld.env.BOOTLOADER:
        return

    if bld.env.EXT_FLASH_SIZE_MB:
        flashiface_lib = ['AP_HAL', 'AP_FlashIface', 'AP_HAL_Empty']
    else:
        flashiface_lib = []
    
    # build external libcanard library
    bld.stlib(source='../../modules/DroneCAN/libcanard/canard.c',
              use='dronecan',
              target='libcanard')

    bld.ap_program(
        use=['ap','libcanard','AP_Bootloader_libs', 'dronecan'],
        program_groups='bootloader'
    )

    bld.ap_stlib(
        name= 'AP_Bootloader_libs',
        use='dronecan',
        dynamic_source='modules/DroneCAN/libcanard/dsdlc_generated/src/**.c',
        ap_vehicle='AP_Bootloader',
        ap_libraries= flashiface_lib + [
        'AP_Math',
        'AP_CheckFirmware'
        ])
