#pragma once

#include <AP_HAL/AP_HAL_Boards.h>
#include <AP_ADSB/AP_ADSB_config.h>
#include <AP_Scripting/AP_Scripting_config.h>
#include <AP_Follow/AP_Follow_config.h>
#include <AC_Avoidance/AC_Avoid_config.h>
#include <GCS_MAVLink/GCS_config.h>

#ifndef AP_LOCATIONDB_ENABLED
#define AP_LOCATIONDB_ENABLED BOARD_FLASH_SIZE > 1024
#endif

#ifndef AP_LOCATIONDB_KEYDOMAIN_DEFAULT_ENABLED
#define AP_LOCATIONDB_KEYDOMAIN_DEFAULT_ENABLED AP_LOCATIONDB_ENABLED
#endif

#ifndef AP_LOCATIONDB_KEYDOMAIN_ADSB_ENABLED
#define AP_LOCATIONDB_KEYDOMAIN_ADSB_ENABLED (AP_LOCATIONDB_KEYDOMAIN_DEFAULT_ENABLED && HAL_ADSB_ENABLED)
#endif

#ifndef AP_LOCATIONDB_KEYDOMAIN_SCRIPTING_ENABLED
#define AP_LOCATIONDB_KEYDOMAIN_SCRIPTING_ENABLED (AP_LOCATIONDB_KEYDOMAIN_DEFAULT_ENABLED && AP_SCRIPTING_ENABLED)
#endif

#ifndef AP_LOCATIONDB_KEYDOMAIN_MAVLINK_ENABLED
#define AP_LOCATIONDB_KEYDOMAIN_MAVLINK_ENABLED (AP_LOCATIONDB_KEYDOMAIN_DEFAULT_ENABLED && HAL_GCS_ENABLED)
#endif
