#! /usr/bin/env python

def options(opt):
	opt.load('compiler_c')

def configure(conf):
	conf.load('compiler_c')

	# choose wisely
	conf.load('strip', tooldir='.')
	#conf.load('strip_hack', tooldir='.')
	#conf.load('strip_on_install', tooldir='.')

def build(bld):
	bld.shlib(source='a.c', target='lib1')
	bld.program(source='main.c', target='app', use='lib1')

