#! /usr/bin/env python

bld.stlib(
	source   = 'test_staticlib.c',
	target   = 'my_static_lib')

bld.program(
	source   = 'main.c',
	target   = 'test_static_link',
	includes = '.',
	use      = 'my_static_lib')

