#! /usr/bin/env python
# encoding: utf-8
# Jaap Haitsma, 2008

# the following two variables are used by the target "waf dist"
VERSION = '0.0.1'
APPNAME = 'vala-gtk-example'

# these variables are mandatory ('/' are converted automatically)
top = '.'
out = 'build'

def options(opt):
	opt.load('compiler_c')
	opt.load('vala')

def configure(conf):
	conf.env.VALA_MINVER = (0, 25, 0)
	conf.load('compiler_c vala')
	conf.check_cfg(package='glib-2.0', uselib_store='GLIB', atleast_version='2.10.0', mandatory=1, args='--cflags --libs')
	conf.recurse('resources')

def build(bld):
	bld.recurse('shlib multi-file stlib resources')

