#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2016 (ita)

VERSION='0.0.1'
APPNAME='msvs_test'

top = '.'
out = 'build'

def options(opt):
	opt.load('compiler_cxx msvs')

def configure(conf):
	conf.load('compiler_cxx')

def build(bld):
	bld.shlib(source='a.cpp', target='mylib', vnum='9.8.7')
	bld.program(source='main.cpp', target='app', use='mylib')
	bld.stlib(source='b.cpp', target='stlib')

