#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_LEAKDETECTOR_ENABLED
#define AP_LEAKDETECTOR_ENABLED 1
#endif

#ifndef AP_LEAKDETECTOR_ANALOG_ENABLED
#define AP_LEAKDETECTOR_ANALOG_ENABLED AP_LEAKDETECTOR_ENABLED
#endif

#ifndef AP_LEAKDETECTOR_DIGITAL_ENABLED
#define AP_LEAKDETECTOR_DIGITAL_ENABLED AP_LEAKDETECTOR_ENABLED
#endif
