#!/usr/bin/env python3

def build(bld):
    if not bld.env.ENABLE_DDS:
        return

    bld.ap_find_tests(
        use='ap',
        DOUBLE_PRECISION_SOURCES=['test_ap_dds_external_odom.cpp']
    )
