#pragma once

#include <AP_BoardConfig/AP_BoardConfig.h>

#ifndef AP_GRIPPER_ENABLED
#define AP_GRIPPER_ENABLED !HAL_MINIMIZE_FEATURES
#endif

#ifndef AP_GRIPPER_BACKEND_DEFAULT_ENABLED
#define AP_GRIPPER_BACKEND_DEFAULT_ENABLED AP_GRIPPER_ENABLED
#endif

#ifndef AP_GRIPPER_SERVO_ENABLED
#define AP_GRIPPER_SERVO_ENABLED AP_GRIPPER_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AP_GRIPPER_EPM_ENABLED
#define AP_GRIPPER_EPM_ENABLED AP_GRIPPER_BACKEND_DEFAULT_ENABLED
#endif
