#! /usr/bin/env python
# encoding: utf-8
# Jérôme Carretero, 2012 (zougloub)
# Put this file in ti-dsplink-tree/dsplink/dsp/src/samples/message

def options(opt):
	opt.load('ticgt')

def configure(cfg):
	cfg.load("ticgt")
	cfg.env.INCLUDES += ['.']

	#if cfg.env.CC_NAME == 'ticc':
	# Take them from the _cflags.txt file
	cfg.env.CFLAGS += "-o3 -q -pdr -pdv -pden -ml3 -mv6740 --disable:sploop".split()
	cfg.env.LINKFLAGS += "-c -x".split()

	# Experimental functions, please comment
	cfg.ti_dsplink_set_platform_flags("OMAPL138", "C674X", "5.XX", "OMAPL138GEM")
	cfg.ti_set_debug(0)

def build(bld):
	bld(
	 target="message",
	 features="c ti-tconf",
	 source=[
	  'DspBios/5.XX/OMAPL138GEM/message.tcf',
	  'DspBios/5.XX/OMAPL138GEM/message.cmd',
	  ],
	 includes='.', # because we need message.tci
	 use=['DSPLINK', 'DSPBIOS' ], # we need them
	)

	bld(
	 target='messagelib',
	 features='c cstlib',
	 source=bld.path.ant_glob('*.c'),
	 use=[
	  'DSPBIOS', 'DSPLINK',
	 ],
	 # Taken from DSP/Link generated _defines.txt files, replaced a -D by a -d
	 defines=' -dTSK_MODE -dMAX_DSPS=1 -dMAX_PROCESSORS=2 -dID_GPP=1 -dOMAPL138 -dPROC_COMPONENT -dPOOL_COMPONENT -dNOTIFY_COMPONENT -dMPCS_COMPONENT -dRINGIO_COMPONENT -dMPLIST_COMPONENT -dMSGQ_COMPONENT -dMSGQ_ZCPY_LINK -dCHNL_COMPONENT -dCHNL_ZCPY_LINK -dZCPY_LINK -dPROCID=0 -dDA8XXGEM -dDA8XXGEM_INTERFACE=SHMEM_INTERFACE -dPHYINTERFACE=SHMEM_INTERFACE -dDSP_SWI_MODE'.split(" -d")[1:] + [
	 ],
	)

	bld(
	 target='message-demo',
	 features='c cprogram',
	 use=[
	  'messagelib',
	  'message',
	 ],
	)

