// -*- tab-width: 4; Mode: C++; c-basic-offset: 4; indent-tabs-mode: nil -*-

// THIS IS A SAMPLE CONFIGURATION FILE FOR DOING HARDWARE IN THE LOOP TESTING USING THE ORIGINAL X-PLANE INTERFACE
// IF YOU WANTED TO USE THIS YOU WOULD COPY THE CONTENTS INTO YOUR APM_Config.h FILE!


#define FLIGHT_MODE_CHANNEL	8
#define FLIGHT_MODE_1		AUTO
#define FLIGHT_MODE_2		RTL
#define FLIGHT_MODE_3 		FLY_BY_WIRE_A
#define FLIGHT_MODE_4       FLY_BY_WIRE_A
#define FLIGHT_MODE_5       MANUAL
#define FLIGHT_MODE_6       MANUAL

#define HIL_PROTOCOL        HIL_PROTOCOL_XPLANE

#define HIL_MODE            HIL_MODE_ATTITUDE
#define HIL_PORT            0

#define AIRSPEED_CRUISE     25
#define THROTTLE_FAILSAFE   ENABLED
#define AIRSPEED_SENSOR		ENABLED
