#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    vehicle = bld.path.name
    bld.ap_stlib(
        name=vehicle + '_libs',
        vehicle=vehicle,
        libraries=bld.ap_common_vehicle_libraries() + [
            'APM_Control',
            'APM_OBC',
            'AP_ADSB',
            'AP_Arming',
            'AP_Camera',
            'AP_Frsky_Telem',
            'AP_L1_Control',
            'AP_Menu',
            'AP_Mount',
            'AP_Navigation',
            'AP_Parachute',
            'AP_RCMapper',
            'AP_RPM',
            'AP_RSSI',
            'AP_Relay',
            'AP_ServoRelayEvents',
            'AP_SpdHgtControl',
            'AP_TECS',
            'AP_InertialNav',
            'AC_WPNav',
            'AC_AttitudeControl',
            'AP_Motors',
            'AC_PID'
        ],
        use='mavlink',
    )

    bld.ap_program(
        program_name='arduplane',
        use=vehicle + '_libs',
    )
