#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2005, 2011 (ita)

"""
Including the moc files *is* the best practice (KDE), not doing it is easy,
but makes the compilations about 30-40% slower on average.

This is the slow version that creates _moc.cpp files (a bad idea!)
"""

VERSION='0.0.2'
APPNAME='qt4_test2'

top = '.'
out = 'build'

def options(opt):
	opt.load('compiler_cxx qt4')

def configure(conf):
	conf.load('compiler_cxx qt4')
	conf.load('slow_qt4')

def build(bld):
	bld(
		features = 'qt4 cxx cxxprogram',
		uselib   = 'QTCORE QTGUI QTOPENGL QTSVG',
		source   = 'main.cpp foo.cpp',
		includes = '.',
		target   = 'window',
	)

