
# This service requests the vehicle to takeoff (VTOL style for QuadPlane).

# alt : Set the takeoff altitude above home or above terrain(in case of rangefinder)

float32 alt
---
# status    : True if the request for mode switch was successful, False otherwise

bool status
