#! /usr/bin/env python

top = '.'
out = 'build'

def options(opt):
	opt.load('compiler_c')
	opt.load('compiler_fc')

def configure(conf):
	conf.load('compiler_c')
	conf.load('compiler_fc')

def build(bld):

	bld(
		features = 'fc fcshlib',
		source = 'parent.f90 container.f90 helper.f90',
		target = 'fudge',
	)
	bld(
		features = 'fc fcprogram',
		source = 'submain.f90',
		use = 'fudge',
		target = 'submain',
	)
