#! /usr/bin/env python
# encoding: utf-8

def configure(conf):
	conf.load('fhash', tooldir='.')

def build(bld):
	node = bld.path.get_bld().make_node('test/bar/stuff')

	bld(features='mkdir', target=node)
	bld(rule='du ${SRC}', source=[node])

