def build(bld):
    bld(
        name = "AP_OpticalFlow",
        target = 'AP_OpticalFlow',
        source = [
            'AP_OpticalFlow.cpp',
            'AP_OpticalFlow_UPFLOW_Tx.cpp', 
        ],
        uselib = [
            'AP_HAL',
            'AP_Param',
        ],
        includes = [
            '.',
            '../AP_HAL',
        ],
        install = False,
    )
