#! /usr/bin/env python

top = '../diff_top_src'
out = 'build'

def options(opt):
	opt.load('compiler_c')

def configure(conf):
	conf.load('compiler_c')

def build(bld):
	bld.program(
			source = bld.srcnode.ant_glob('*.c'),
			target = 'main',
			)

# vim:ft=python:noet
