#! /usr/bin/env python

def write_header(tsk):
	tsk.outputs[0].write('int abc = 423;')
bld(rule=write_header, target='b.h', ext_out=['.h'])

bld.program(
	source   = 'main.c',
	includes = '. ..',
	cflags   = ['-O3'],
	defines  = ['foo=bar'],
	target   = 'myprogram',
	use      = 'M')

