#!/usr/bin/env python
# encoding: utf-8

def configure(cfg):
    cfg.env.XRCE_DEPENDENCIES = []
    cfg.env.XRCE_DEPENDENCIES+=[str(source) for source in (cfg.srcnode.ant_glob('modules/Micro-XRCE-DDS-Client/src/c/core/session/stream/*.c'))]
    cfg.env.XRCE_DEPENDENCIES+=[str(source) for source in (cfg.srcnode.ant_glob('modules/Micro-XRCE-DDS-Client/src/c/core/session/*.c'))]
    cfg.env.XRCE_DEPENDENCIES+=[str(source) for source in (cfg.srcnode.ant_glob('modules/Micro-XRCE-DDS-Client/src/c/core/serialization/*.c'))]
    cfg.env.XRCE_DEPENDENCIES+=[str(source) for source in (cfg.srcnode.ant_glob('modules/Micro-XRCE-DDS-Client/src/c/util/*.c'))]
    cfg.env.XRCE_DEPENDENCIES+=[str(source) for source in (cfg.srcnode.ant_glob('modules/Micro-XRCE-DDS-Client/src/c/profile/transport/ip/ip_posix.c'))]
    cfg.env.XRCE_DEPENDENCIES+=[str(source) for source in (cfg.srcnode.ant_glob('modules/Micro-XRCE-DDS-Client/src/c/profile/transport/ip/udp/udp_transport_posix.c'))]
    cfg.env.XRCE_DEPENDENCIES+=[str(source) for source in (cfg.srcnode.ant_glob('modules/Micro-XRCE-DDS-Client/src/c/profile/transport/ip/udp/udp_transport.c'))]
    cfg.env.XRCE_DEPENDENCIES+=[str(source) for source in (cfg.srcnode.ant_glob('modules/Micro-XRCE-DDS-Client/src/c/profile/transport/serial/serial_transport.c'))]
    cfg.env.XRCE_DEPENDENCIES+=[str(source) for source in (cfg.srcnode.ant_glob('modules/Micro-XRCE-DDS-Client/src/c/profile/transport/serial/serial_transport_posix.c'))]
    cfg.env.XRCE_DEPENDENCIES+=[str(source) for source in (cfg.srcnode.ant_glob('modules/Micro-XRCE-DDS-Client/src/c/profile/transport/stream_framing/stream_framing_protocol.c'))]
    cfg.env.XRCE_DEPENDENCIES+=[str(source) for source in (cfg.srcnode.ant_glob('modules/Micro-CDR/src/c/types/*.c'))]
    cfg.env.XRCE_DEPENDENCIES+=[str(source) for source in (cfg.srcnode.ant_glob('modules/Micro-CDR/src/c/common.c'))]
    cfg.env.INCLUDES+=[cfg.srcnode.make_node('modules/Micro-XRCE-DDS-Client/include/uxr/client/').abspath(),cfg.srcnode.make_node('modules/Micro-CDR/src/c/').abspath(),cfg.srcnode.make_node('modules/Micro-CDR/include/ucdr/').abspath()]
    cfg.env.append_value('GIT_SUBMODULES', 'Micro-XRCE-DDS-Client')
    cfg.env.append_value('GIT_SUBMODULES','Micro-CDR')
