#! /usr/bin/env python
# encoding: utf-8

bld.env.NARG = '-flag2'
bld(
	features = 'cxx cxxprogram test',
	source   = 'HelloWorldTest.cpp',
	target   = 'unit_test_program',
	use      = 'unittestmain useless CPPUNIT',
	ut_str   = '${SRC[0].abspath()} -flag1 ${NARG}'
)

