#!/usr/bin/env python3

import sys


def build(bld):
    if bld.env.BOARD not in ('sitl', 'linux'):
        return
    linkflags = []
    if sys.platform.startswith('linux'):
        linkflags = ['-Wl,--wrap=pwrite', '-Wl,--wrap=write']
    bld.ap_example(use='ap', linkflags=linkflags)
