#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_MOTORS_ENABLED
#define AP_MOTORS_ENABLED 1
#endif  // AP_MOTORS_ENABLED

#if AP_MOTORS_ENABLED

#include <AP_Scripting/AP_Scripting_config.h>
#include <SRV_Channel/SRV_Channel_config.h>

#ifndef AP_MOTORS_MAX_NUM_MOTORS
#if AP_SCRIPTING_ENABLED
#define AP_MOTORS_MAX_NUM_MOTORS 32
#else
#define AP_MOTORS_MAX_NUM_MOTORS 12
#endif

// doesn't make sense to have more motors than servo channels, so clamp:
#if NUM_SERVO_CHANNELS < AP_MOTORS_MAX_NUM_MOTORS
#undef AP_MOTORS_MAX_NUM_MOTORS
#define AP_MOTORS_MAX_NUM_MOTORS NUM_SERVO_CHANNELS
#endif

// various Motors backends will not compile if we don't have 16 motors
// available (eg. AP_Motors6DOF).  Until we stop compiling those
// backends in when there aren't enough motors to support those
// backends we will support a minimum of 12 motors, the limit before
// we moved to 32 motor support:
#if AP_MOTORS_MAX_NUM_MOTORS < 12
#undef AP_MOTORS_MAX_NUM_MOTORS
#define AP_MOTORS_MAX_NUM_MOTORS 12
#endif

#endif  // defined (AP_MOTORS_MAX_NUM_MOTORS)

/*
 * direct backends of AP_Motors
 */
#ifndef AP_MOTORS_BACKEND_DEFAULT_ENABLED
#define AP_MOTORS_BACKEND_DEFAULT_ENABLED AP_MOTORS_ENABLED
#endif  // AP_MOTORS_BACKEND_DEFAULT_ENABLED

#ifndef AP_MOTORSHELI_ENABLED
#define AP_MOTORSHELI_ENABLED AP_MOTORS_BACKEND_DEFAULT_ENABLED
#endif  // AP_MOTORSHELI_ENABLED

#ifndef AP_MOTORSMULTI_ENABLED
#define AP_MOTORSMULTI_ENABLED AP_MOTORS_BACKEND_DEFAULT_ENABLED
#endif  // AP_MOTORSMULTI_ENABLED

/*
 * subclasses of AP_MotorsMulti
 */
#ifndef AP_MOTORSMULTI_BACKEND_DEFAULT_ENABLED
#define AP_MOTORSMULTI_BACKEND_DEFAULT_ENABLED AP_MOTORSMULTI_ENABLED
#endif  // AP_MOTORSMULTI_BACKEND_DEFAULT_ENABLED

#ifndef AP_MOTORS_COAX_ENABLED
#define AP_MOTORS_COAX_ENABLED AP_MOTORSMULTI_BACKEND_DEFAULT_ENABLED
#endif  // AP_MOTORS_COAX_ENABLED

#ifndef AP_MOTORS_TAILSITTER_ENABLED
#define AP_MOTORS_TAILSITTER_ENABLED AP_MOTORSMULTI_BACKEND_DEFAULT_ENABLED
#endif  // AP_MOTORS_TAILSITTER_ENABLED

#ifndef AP_MOTORS_TRI_ENABLED
#define AP_MOTORS_TRI_ENABLED AP_MOTORSMULTI_BACKEND_DEFAULT_ENABLED
#endif  // AP_MOTORS_TRI_ENABLED

#ifndef AP_MOTORS_MATRIX_ENABLED
#define AP_MOTORS_MATRIX_ENABLED AP_MOTORSMULTI_BACKEND_DEFAULT_ENABLED
#endif  // AP_MOTORS_MATRIX_ENABLED

#ifndef AP_MOTORS_SINGLE_ENABLED
#define AP_MOTORS_SINGLE_ENABLED AP_MOTORSMULTI_BACKEND_DEFAULT_ENABLED
#endif  // AP_MOTORS_SINGLE_ENABLED

/*
 * the Matrix frames
 */
#ifndef AP_MOTORS_FRAME_DEFAULT_ENABLED
#define AP_MOTORS_FRAME_DEFAULT_ENABLED 1
#endif

#ifndef AP_MOTORS_FRAME_6DOF_ENABLED
#define AP_MOTORS_FRAME_6DOF_ENABLED (AP_MOTORS_FRAME_DEFAULT_ENABLED && AP_MOTORS_MATRIX_ENABLED)
#endif
#ifndef AP_MOTORS_FRAME_6DOF_SCRIPTING_ENABLED
#define AP_MOTORS_FRAME_6DOF_SCRIPTING_ENABLED (AP_MOTORS_FRAME_DEFAULT_ENABLED && AP_MOTORS_MATRIX_ENABLED && AP_SCRIPTING_ENABLED)
#endif  // AP_MOTORS_FRAME_6DOF_SCRIPTING_ENABLED
#ifndef AP_MOTORS_FRAME_QUAD_ENABLED
#define AP_MOTORS_FRAME_QUAD_ENABLED AP_MOTORS_FRAME_DEFAULT_ENABLED && AP_MOTORS_MATRIX_ENABLED
#endif
#ifndef AP_MOTORS_FRAME_HEXA_ENABLED
#define AP_MOTORS_FRAME_HEXA_ENABLED AP_MOTORS_FRAME_DEFAULT_ENABLED && AP_MOTORS_MATRIX_ENABLED
#endif
#ifndef AP_MOTORS_FRAME_OCTA_ENABLED
#define AP_MOTORS_FRAME_OCTA_ENABLED AP_MOTORS_FRAME_DEFAULT_ENABLED && AP_MOTORS_MATRIX_ENABLED
#endif
#ifndef AP_MOTORS_FRAME_DECA_ENABLED
#define AP_MOTORS_FRAME_DECA_ENABLED AP_MOTORS_FRAME_DEFAULT_ENABLED && AP_MOTORS_MATRIX_ENABLED
#endif
#ifndef AP_MOTORS_FRAME_DODECAHEXA_ENABLED
#define AP_MOTORS_FRAME_DODECAHEXA_ENABLED AP_MOTORS_FRAME_DEFAULT_ENABLED && AP_MOTORS_MATRIX_ENABLED
#endif
#ifndef AP_MOTORS_FRAME_Y6_ENABLED
#define AP_MOTORS_FRAME_Y6_ENABLED AP_MOTORS_FRAME_DEFAULT_ENABLED && AP_MOTORS_MATRIX_ENABLED
#endif
#ifndef AP_MOTORS_FRAME_OCTAQUAD_ENABLED
#define AP_MOTORS_FRAME_OCTAQUAD_ENABLED AP_MOTORS_FRAME_DEFAULT_ENABLED && AP_MOTORS_MATRIX_ENABLED
#endif
#ifndef AP_MOTORS_FRAME_SCRIPTING_MATRIX_ENABLED
#define AP_MOTORS_FRAME_SCRIPTING_MATRIX_ENABLED (AP_MOTORS_FRAME_DEFAULT_ENABLED && AP_MOTORS_MATRIX_ENABLED && AP_SCRIPTING_ENABLED)
#endif  // AP_MOTORS_FRAME_SCRIPTING_MATRIX_ENABLED
#ifndef AP_MOTORS_FRAME_DYNAMIC_SCRIPTING_MATRIX_ENABLED
#define AP_MOTORS_FRAME_DYNAMIC_SCRIPTING_MATRIX_ENABLED (AP_MOTORS_FRAME_DEFAULT_ENABLED && AP_MOTORS_MATRIX_ENABLED && AP_SCRIPTING_ENABLED)
#endif  // AP_MOTORS_FRAME_DYNAMIC_SCRIPTING_MATRIX_ENABLED
// end of Matrix frames

/*
 * Non-Matrix frames are enabled iif the corresponding motor library is enabled:
 */
#ifndef AP_MOTORS_FRAME_COAX_ENABLED
#define AP_MOTORS_FRAME_COAX_ENABLED AP_MOTORS_COAX_ENABLED
#endif  // AP_MOTORS_FRAME_COAX_ENABLED

#ifndef AP_MOTORS_FRAME_SINGLE_ENABLED
#define AP_MOTORS_FRAME_SINGLE_ENABLED AP_MOTORS_SINGLE_ENABLED
#endif  // AP_MOTORS_FRAME_SINGLE_ENABLED

#ifndef AP_MOTORS_FRAME_TAILSITTER_ENABLED
#define AP_MOTORS_FRAME_TAILSITTER_ENABLED AP_MOTORS_TAILSITTER_ENABLED
#endif  // AP_MOTORS_FRAME_TAILSITTER_ENABLED

#ifndef AP_MOTORS_FRAME_TRI_ENABLED
#define AP_MOTORS_FRAME_TRI_ENABLED AP_MOTORS_TRI_ENABLED
#endif  // AP_MOTORS_FRAME_TRI_ENABLED

#endif  // AP_MOTORS_ENABLED
