#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_IBUS2_ENABLED
#define AP_IBUS2_ENABLED (HAL_PROGRAM_SIZE_LIMIT_KB > 2048)
#endif

#ifndef AP_IBUS2_MASTER_ENABLED
#define AP_IBUS2_MASTER_ENABLED AP_IBUS2_ENABLED
#endif

#ifndef AP_IBUS2_SLAVE_ENABLED
#define AP_IBUS2_SLAVE_ENABLED AP_IBUS2_ENABLED
#endif
