#!/bin/tcsh -f
setenv MASTER_DRONE 1
#python3 ../Tools/autotest/sim_vehicle.py --map --console -L Moab –instance 2
python3 ../Tools/autotest/sim_vehicle.py --map --console -L Moab –instance=2
#output add <ip-address>:14551
