#define DEBUG_SUBSYSTEM     0

#define FLIGHT_MODE_CHANNEL	8
#define FLIGHT_MODE_1		AUTO
#define FLIGHT_MODE_2		RTL
#define FLIGHT_MODE_3 		FLY_BY_WIRE_A
#define FLIGHT_MODE_4       FLY_BY_WIRE_B
#define FLIGHT_MODE_5       STABILIZE
#define FLIGHT_MODE_6       MANUAL

#define GCS_PROTOCOL        GCS_PROTOCOL_DEBUGTERMINAL
#define ENABLE_HIL			ENABLED
#define GCS_PORT            3
#define GPS_PROTOCOL  		GPS_PROTOCOL_IMU
#define AIRSPEED_CRUISE     25

#define THROTTLE_FAILSAFE   ENABLED
#define AIRSPEED_SENSOR		ENABLED

