#!/usr/bin/env python3

# flake8: noqa

def build(bld):
    if bld.env.BOARD_CLASS != 'SITL':
        return

    bld.ap_program(
        program_name='renode-physics',
        program_groups=['tool'],
        source=['renode_physics.cpp'],
        use='ap',
        vehicle_binary=False,
    )
