#!/usr/bin/env python3
'''
Persistent board state for a Zephyr board that boots under Renode from a
static platform (mr_vmu_rt1176): the microSD image, the parameter-storage
image, and the boot-script lines that hand them to the board script.

Shared by zephyr_boot_check.py and tests/test_physics_flight.py so both
harnesses bring the board up the same way. It is not optional: the board
script's SdCardFromFile line ABORTS THE REST OF THE SCRIPT when $sdcard is
@none, so start never runs, the UART socket never opens, and the board is
indistinguishable from a hang.

AP_FLAKE8_CLEAN
'''
import json
import os

import fat_image

# AP_FlashStorage's two 64 KiB sectors: storage_partition at flash offset
# 0x620000, seen through the FlexSPI window at 0x30000000.
PARAMS_ADDRESS = 0x30620000
PARAMS_SIZE = 2 * 65536
SDCARD_SIZE = 512 * 1024 * 1024


def prepare(state_dir):
    '''Create sdcard.img, params.img and params.repl in state_dir, keeping
    any that already exist - the card and the parameters are what persists
    between runs. fat_image.create_image() validates an existing card's
    geometry rather than replacing it. Returns absolute paths:
    (sd_image, params_image, params_repl). Raises on a mismatched image.'''
    os.makedirs(state_dir, exist_ok=True)

    sd_image = os.path.abspath(os.path.join(state_dir, 'sdcard.img'))
    fat_image.create_image(sd_image, SDCARD_SIZE, sectors_per_cluster=8)

    # Erased (0xFF) when first created, kept thereafter - run.py's
    # make_erased() contract.
    params_image = os.path.abspath(os.path.join(state_dir, 'params.img'))
    if os.path.exists(params_image):
        if os.path.getsize(params_image) != PARAMS_SIZE:
            raise RuntimeError(
                '%s is %u bytes; expected %u (move it aside to reinitialize)'
                % (params_image, os.path.getsize(params_image), PARAMS_SIZE))
    else:
        with open(params_image, 'wb') as f:
            f.write(b'\xff' * PARAMS_SIZE)

    # The persistence node, as run.py's make_persistence_repl() writes it: a
    # .repl file with the path as a STRING LITERAL. It cannot go in the board
    # script as "fileName: $params" - Renode does not expand variables inside
    # a platform description, it is a syntax error, and the error aborts the
    # rest of the script.
    params_repl = os.path.abspath(os.path.join(state_dir, 'params.repl'))
    with open(params_repl, 'w') as f:
        f.write('// GENERATED by zephyr_state.py - parameter storage persistence.\n'
                'params: Miscellaneous.AP_PersistentMemory @ none\n'
                '    fileName: %s\n'
                '    address: 0x%X\n'
                '    size: 0x%X\n'
                % (json.dumps(params_image), PARAMS_ADDRESS, PARAMS_SIZE))
    return sd_image, params_image, params_repl


def lines_before_include(sd_image):
    '''Goes BEFORE the board script's include: it uses "?=", which only
    assigns when the variable is unset.'''
    return '$sdcard = @%s\n' % sd_image


def lines_after_machine(params_image, params_repl):
    '''Goes after "mach set 0": the parameter image into the FlexSPI window,
    and the node that writes it back on quit.'''
    return ('sysbus LoadBinary @%s 0x%X\n'
            'machine LoadPlatformDescription @%s\n'
            % (params_image, PARAMS_ADDRESS, params_repl))
