/*
 * This file is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Code by @davidbuzz and Claude
 */
#include <AP_HAL/AP_HAL.h>
#include "chain_profile.h"

#if CONFIG_HAL_BOARD == HAL_BOARD_ZEPHYR

#include "SPIDevice.h"
#include "bouncebuffer.h"
#include "hwdef.h"

#include <new>
#include <string.h>

#ifdef __ZEPHYR__
#include <zephyr/devicetree.h>
#include <zephyr/drivers/spi.h>
#include <zephyr/kernel.h>   /* k_cycle_get_32 / sys_clock_hw_cycles_per_sec */
#endif

/* Bounce buffers live on the DeviceBus and are SEPARATE for TX and RX, exactly as
 * ChibiOS does, so a shared buffer cannot alias a transfer against itself. */

using namespace Zephyr;

struct SPIDeviceDesc {
    const char *name;
    SPIDevice::DeviceId id;
    uint8_t bus;
    uint8_t cs;
    uint32_t lowspeed_hz;
    uint32_t highspeed_hz;
};

/* SPI devices are now generated from hwdef.dat via zephyr_hwdef.py.
   The HAL_SPI_DEVICES_LIST macro in hwdef.h contains initializers for this array. */
static const SPIDeviceDesc spi_devices[] = {
#ifdef HAL_SPI_DEVICES_LIST
    HAL_SPI_DEVICES_LIST
#endif
};

#ifdef __ZEPHYR__
/* spi_dt_spec declarations, one per hwdef.dat SPIDEV entry whose name matches
   a DTS nodelabel. Generated by zephyr_hwdef.py into hwdef.h. */
#ifdef HAL_SPI_DT_SPEC_DECLS
HAL_SPI_DT_SPEC_DECLS
#endif

/* Name-based lookup — required because DeviceId (IMU0/1/2/BARO/FRAM) is not
   unique enough (e.g. two BARO devices: ms5611 and ms5611_ext share a bus role
   but are different physical parts on different SPI buses/CS pins). */
static const struct spi_dt_spec *spec_for_name(const char *name)
{
#ifdef HAL_SPI_DT_SPEC_LOOKUP
    HAL_SPI_DT_SPEC_LOOKUP(name)
#endif
    return nullptr;
}
#endif

SPIDevice::SPIDevice(const char *name, DeviceId id, uint8_t bus, uint8_t cs_index,
                     uint32_t lowspeed_hz, uint32_t highspeed_hz) :
    _name(name),
    _id(id),
    _speed_hz(highspeed_hz),
    _lowspeed_hz(lowspeed_hz),
    _highspeed_hz(highspeed_hz)
{
    set_device_bus(bus);
    set_device_address(cs_index);
    _bus = DeviceBus::get_bus(bus, (uint8_t)AP_HAL::Device::BUS_TYPE_SPI);
#ifdef __ZEPHYR__
    _spec = spec_for_name(_name);
#endif
}

AP_HAL::Device::PeriodicHandle SPIDevice::register_periodic_callback(
    uint32_t period_usec, AP_HAL::Device::PeriodicCb cb)
{
    if (_bus == nullptr) {
        return nullptr;
    }
    return _bus->register_periodic_callback(period_usec, cb, this);
}

bool SPIDevice::adjust_periodic_callback(AP_HAL::Device::PeriodicHandle h,
                                         uint32_t period_usec)
{
    if (_bus == nullptr) {
        return false;
    }
    return _bus->adjust_timer(h, period_usec);
}

bool SPIDevice::set_speed(AP_HAL::Device::Speed speed)
{
    _speed_hz = (speed == AP_HAL::Device::SPEED_HIGH) ? _highspeed_hz : _lowspeed_hz;
    return true;
}

bool SPIDevice::transfer(const uint8_t *send, uint32_t send_len,
                         uint8_t *recv, uint32_t recv_len)
{
    /* BUSN, not BUS: the non-N form writes profile slot 0 for EVERY bus, so
       with two bus threads transferring concurrently the phase fraction cannot
       be attributed to a bus and dividing by the COMBINED transfer rate
       underestimates per-transfer time. bus_num() is AP_HAL::Device's own
       accessor for the bus this device was constructed on. */
    AP_PHASE_BUSN(bus_num(), AP_PHASE_SPI_XFER);
    AP_PROF_TICK(AP_PROF_XFER_COUNT);
    AP_PROF_ADD(AP_PROF_XFER_BYTES, send_len + recv_len);
#ifdef __ZEPHYR__
    if (!_bus_ready) {
        if (_spec == nullptr || !spi_is_ready_dt(_spec)) {
            return false;
        }
        _bus_ready = true;
    }

    /* Reuse the persistent per-device config so the pointer stays stable -
       see the _cfg comment in SPIDevice.h. Rewriting the whole struct each
       time is fine (contents are identical); what must NOT change is its
       ADDRESS, which is what the driver compares. */
    if (!_cfg_init) {
        _cfg[0] = _spec->config;
        _cfg[1] = _spec->config;
        _cfg[0].frequency = _speed_hz;
        _cfg[1].frequency = _speed_hz;
        _cfg_freq = _speed_hz;
        _cfg_init = true;
    } else if (_cfg_freq != _speed_hz) {
        /* real speed change: flip slots so the POINTER changes too, which is
           the only way this driver notices - see SPIDevice.h */
        _cfg_idx ^= 1;
        _cfg[_cfg_idx] = _spec->config;
        _cfg[_cfg_idx].frequency = _speed_hz;
        _cfg_freq = _speed_hz;
    }
    struct spi_config &cfg = _cfg[_cfg_idx];

    /* ArduPilot transfer() semantics, matching AP_HAL_ChibiOS. */
    /* ChibiOS pattern (bouncebuffer.h): substitute DMA-safe buffers if the
       caller's are not, and do the cache maintenance the Zephyr LPSPI DMA
       driver omits. Done BEFORE the spi_buf structs so they are built with the
       final pointers. */
    const uint8_t *tx_buf = send;
    uint8_t *rx_buf = recv;
    bool combined = false;
    struct spi_buf tx_bufs[2];
    struct spi_buf rx_bufs[2];
    struct spi_buf_set tx_set = { .buffers = tx_bufs, .count = 2 };
    struct spi_buf_set rx_set = { .buffers = rx_bufs, .count = 2 };

    if (send_len > 0 && recv_len > 0 && send != nullptr && recv != nullptr &&
        _bus != nullptr) {
        /* Run the send-then-recv register transaction as ONE full-duplex transfer: as
         * two chunks the DMA RX channel only served the second, returning zeros. */
        uint8_t *tx_full;
        uint8_t *rx_full;
        const uint16_t total = send_len + recv_len;
        if (_bus->xfer_scratch(total, tx_full, rx_full)) {
            memcpy(tx_full, send, send_len);
            memset(tx_full + send_len, 0, recv_len);
            tx_bufs[0] = { .buf = tx_full, .len = total };
            rx_bufs[0] = { .buf = rx_full, .len = total };
            tx_set.count = 1;
            rx_set.count = 1;
            rx_buf = rx_full;
            combined = true;
        }
    }
    if (!combined) {
        if (_bus == nullptr || !_bus->bouncebuffer_setup(tx_buf, send_len, rx_buf, recv_len)) {
            return false;
        }
        tx_bufs[0] = { .buf = const_cast<uint8_t *>(tx_buf), .len = send_len };
        tx_bufs[1] = { .buf = nullptr, .len = recv_len };
        rx_bufs[0] = { .buf = nullptr, .len = send_len };
        rx_bufs[1] = { .buf = rx_buf, .len = recv_len };
    }

    const uint32_t _t0 = k_cycle_get_32();
    const bool ok = spi_transceive(_spec->bus, &cfg, &tx_set, &rx_set) == 0;
    ap_prof_xfer_record(k_cycle_get_32() - _t0, sys_clock_hw_cycles_per_sec());
    if (combined) {
        if (ok) {
            memcpy(recv, rx_buf + send_len, recv_len);
        }
    } else {
        _bus->bouncebuffer_finish(tx_buf, rx_buf, recv_len);
    }
    return ok;
#else
    (void)send;
    (void)send_len;
    (void)recv;
    (void)recv_len;
    return true;
#endif
}

/* In-place full duplex - the form AP_InertialSensor_Invensensev3::read_fifo()
 * uses, where the RX buffer is the TX buffer. */
bool SPIDevice::transfer_fullduplex(uint8_t *send_recv, uint32_t len)
{
    return transfer_fullduplex(send_recv, send_recv, len);
}

bool SPIDevice::transfer_fullduplex(const uint8_t *send, uint8_t *recv,
                                    uint32_t len)
{
    /* INSTRUMENTATION GAP, fixed 2026-08-05: this path carried no phase marker, so
     * its time landed in AP_PHASE_OTHER. */
    AP_PHASE_BUSN(bus_num(), AP_PHASE_SPI_XFER);
    AP_PROF_TICK(AP_PROF_XFER_COUNT);
    AP_PROF_ADD(AP_PROF_XFER_BYTES, len);
#ifdef __ZEPHYR__
    if (send == nullptr || recv == nullptr || len == 0U) {
        return false;
    }
    if (!_bus_ready) {
        if (_spec == nullptr || !spi_is_ready_dt(_spec)) {
            return false;
        }
        _bus_ready = true;
    }

    /* Reuse the persistent per-device config so the pointer stays stable -
       see the _cfg comment in SPIDevice.h. Rewriting the whole struct each
       time is fine (contents are identical); what must NOT change is its
       ADDRESS, which is what the driver compares. */
    if (!_cfg_init) {
        _cfg[0] = _spec->config;
        _cfg[1] = _spec->config;
        _cfg[0].frequency = _speed_hz;
        _cfg[1].frequency = _speed_hz;
        _cfg_freq = _speed_hz;
        _cfg_init = true;
    } else if (_cfg_freq != _speed_hz) {
        /* real speed change: flip slots so the POINTER changes too, which is
           the only way this driver notices - see SPIDevice.h */
        _cfg_idx ^= 1;
        _cfg[_cfg_idx] = _spec->config;
        _cfg[_cfg_idx].frequency = _speed_hz;
        _cfg_freq = _speed_hz;
    }
    struct spi_config &cfg = _cfg[_cfg_idx];

    const uint8_t *tx_buf = send;
    uint8_t *rx_buf = recv;
    if (_bus == nullptr || !_bus->bouncebuffer_setup(tx_buf, len, rx_buf, len)) {
        return false;
    }

    const struct spi_buf tx = {
        .buf = const_cast<uint8_t *>(tx_buf),
        .len = len,
    };
    const struct spi_buf_set tx_set = {
        .buffers = &tx,
        .count = 1,
    };

    struct spi_buf rx = {
        .buf = rx_buf,
        .len = len,
    };
    const struct spi_buf_set rx_set = {
        .buffers = &rx,
        .count = 1,
    };

    const uint32_t _t0 = k_cycle_get_32();
    const bool ok = spi_transceive(_spec->bus, &cfg, &tx_set, &rx_set) == 0;
    ap_prof_xfer_record(k_cycle_get_32() - _t0, sys_clock_hw_cycles_per_sec());
    _bus->bouncebuffer_finish(tx_buf, rx_buf, len);
    return ok;
#else
    (void)send;
    (void)recv;
    (void)len;
    return true;
#endif
}

AP_HAL::SPIDevice *SPIDeviceManager::get_device_ptr(const char *name)
{
    if (name == nullptr) {
        return nullptr;
    }

    for (uint8_t i = 0; i < ARRAY_SIZE(spi_devices); i++) {
        if (strcmp(spi_devices[i].name, name) == 0) {
            AP_HAL::SPIDevice *dev = NEW_NOTHROW SPIDevice(
                spi_devices[i].name,
                spi_devices[i].id,
                spi_devices[i].bus,
                spi_devices[i].cs,
                spi_devices[i].lowspeed_hz,
                spi_devices[i].highspeed_hz);
            return dev;
        }
    }

    return nullptr;
}

uint8_t SPIDeviceManager::get_count()
{
    return ARRAY_SIZE(spi_devices);
}

const char *SPIDeviceManager::get_device_name(uint8_t idx)
{
    if (idx >= ARRAY_SIZE(spi_devices)) {
        return nullptr;
    }
    return spi_devices[idx].name;
}


#endif  // CONFIG_HAL_BOARD == HAL_BOARD_ZEPHYR
