#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2016 (ita)

def options(opt):
	opt.load('compiler_c')

def configure(conf):
	conf.load('compiler_c')

def build(bld):
	bld.load('print_commands')
	bld.program(source='main.c', target='app')

