#pragma once

#ifndef AP_BATTMON_SMBUS_ENABLE
#define AP_BATTMON_SMBUS_ENABLE 1
#endif

#ifndef AP_BATTMON_FUELFLOW_ENABLE
#define AP_BATTMON_FUELFLOW_ENABLE (BOARD_FLASH_SIZE > 1024)
#endif

#ifndef AP_BATTMON_FUELLEVEL_PWM_ENABLE
#define AP_BATTMON_FUELLEVEL_PWM_ENABLE (BOARD_FLASH_SIZE > 1024)
#endif

#ifndef AP_BATTMON_FUELLEVEL_ANALOG_ENABLE
#define AP_BATTMON_FUELLEVEL_ANALOG_ENABLE (BOARD_FLASH_SIZE > 1024)
#endif

#ifndef AP_BATTMON_SYNTHETIC_CURRENT_ENABLED
#define AP_BATTMON_SYNTHETIC_CURRENT_ENABLED  1
#endif

#ifndef AP_BATTMON_SMBUS_SOLO_ENABLED
#define AP_BATTMON_SMBUS_SOLO_ENABLED 0  // turned on in hwdefs
#endif
