#include <AP_HAL/AP_HAL_Boards.h>
#include <AP_Mount/AP_Mount_config.h>

#ifndef AP_MISSION_ENABLED
#define AP_MISSION_ENABLED 1
#endif

#ifndef AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED
#define AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED 1
#endif

#ifndef AP_MISSION_MAV_CMD_DO_SET_ROI_WPNEXT_OFFSET_ENABLED
#define AP_MISSION_MAV_CMD_DO_SET_ROI_WPNEXT_OFFSET_ENABLED (AP_MISSION_ENABLED && AP_MOUNT_ROI_WPNEXT_OFFSET_ENABLED)
#endif
