#! /usr/bin/env python

bld.recurse('libA')
bld.recurse('libB')
bld.recurse('libC')

# Note that main has an implied dependency between our main program and libA
bld.program(
	source   = 'main.c',
	target   = 'test_static_link_chain',
	use      = 'B C')
