#!/usr/bin/env python3

# flake8: noqa
from waflib.TaskGen import after_method, before_method, feature

def build(bld):
    vehicle = bld.path.name
    
    bld.ap_stlib(
        name=vehicle + '_libs',
        ap_vehicle='UNKNOWN',
        dynamic_source='modules/DroneCAN/libcanard/dsdlc_generated/src/**.c',
        ap_libraries=bld.ap_common_vehicle_libraries() + [
            'AP_OSD',
            'AP_Avoidance',
        ],
    )
    bld.ap_program(
        program_groups=['tool'],
        use=[vehicle + '_libs'],
    )
