#! /usr/bin/env python

def options(ctx):
    ctx.load('compiler_c')

def configure(ctx):
    ctx.load('compiler_c')
    ctx.load('objcopy')

def build(ctx):
    ctx(features = 'c cprogram objcopy',
        source   = 'main.c',
        target   = 'app',
#       objcopy_bfdname='srec',
#       objcopy_target  = 'alternative-name',
#       objcopy_install_path = '${PREFIX}/some_dir',
#       objcopy_flags = '--strip-all'
        )
