#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef HAL_TORQEEDO_ENABLED
#define HAL_TORQEEDO_ENABLED BOARD_FLASH_SIZE > 1024 && !defined(HAL_BUILD_AP_PERIPH)
#endif

#ifndef AP_TORQEEDO_BACKEND_DEFAULT_ENABLED
#define AP_TORQEEDO_BACKEND_DEFAULT_ENABLED HAL_TORQEEDO_ENABLED
#endif

#ifndef AP_TORQEEDO_TQBUS_ENABLED
#define AP_TORQEEDO_TQBUS_ENABLED AP_TORQEEDO_BACKEND_DEFAULT_ENABLED
#endif
