#!/usr/bin/env python
# encoding: utf-8

import boards

def build(bld):
    if isinstance(bld.get_board(), boards.chibios) and bld.env['WITH_FATFS'] != '1':
        # we need a filesystem for replay
        return

    vehicle = bld.path.name

    bld.ap_stlib(
        name=vehicle + '_libs',
        ap_vehicle=vehicle,
        ap_libraries=bld.ap_common_vehicle_libraries() + [
            'AP_Beacon',
            'AP_Arming',
            'AP_RCMapper',
            'AP_OSD',
            'AP_Avoidance',
        ],
    )

    bld.ap_program(
        program_groups=['tools','replay'],
        use=vehicle + '_libs',
    )
