# encoding: utf-8

# flake8: noqa

import boards

def build(bld):
    if isinstance(bld.get_board(), boards.chibios) and bld.env['WITH_FATFS'] != '1' and bld.env['WITH_LITTLEFS'] != 1:
        # we need a filesystem for replay
        return

    vehicle = bld.path.name

    bld.ap_stlib(
        name=vehicle + '_libs',
        ap_vehicle=vehicle,
        ap_libraries=bld.ap_common_vehicle_libraries() + [
            'AP_OSD',
            'AP_Avoidance',
        ],
    )

    bld.ap_program(
        program_groups=['tool','replay'],
        use=vehicle + '_libs',
    )
