#pragma once

/// @file    AP_Simulink_Base.h
/// @brief   Base class implementation of Simulink instance class

#include <AP_Common/AP_Common.h>

class AP_Simulink_Base
{
public:
    virtual ~AP_Simulink_Base() {}
    // The initialization function generated by Simulink will be invoked during the init
    virtual void init() = 0;
    // The step function generated by Simulink will be invoked during the update
    virtual void update() = 0;
    // The terminate function generated by Simulink will be invoked during the reset
    virtual void reset() = 0;
};
