//  GCS Message ID's
/// NOTE: to ensure we never block on sending MAVLink messages
/// please keep each MSG_ to a single MAVLink message. If need be
/// create new MSG_ IDs for additional messages on the same
/// stream

#pragma once

enum ap_message : uint8_t {
    MSG_HEARTBEAT                         =  0,
    MSG_ATTITUDE                          =  1,
    MSG_ATTITUDE_QUATERNION               =  2,
    MSG_LOCATION                          =  3,
    MSG_SYS_STATUS                        =  4,
    MSG_POWER_STATUS                      =  5,
    MSG_MEMINFO                           =  6,
    MSG_NAV_CONTROLLER_OUTPUT             =  7,
    MSG_CURRENT_WAYPOINT                  =  8,
    MSG_VFR_HUD                           =  9,
    MSG_SERVO_OUTPUT_RAW                  = 10,
    MSG_RC_CHANNELS                       = 11,
    MSG_RC_CHANNELS_RAW                   = 12,
    MSG_RAW_IMU                           = 13,
    MSG_SCALED_IMU                        = 14,
    MSG_SCALED_IMU2                       = 16,
    MSG_SCALED_IMU3                       = 17,
    MSG_SCALED_PRESSURE                   = 18,
    MSG_SCALED_PRESSURE2                  = 19,
    MSG_SCALED_PRESSURE3                  = 20,
    MSG_GPS_RAW                           = 21,
    MSG_GPS_RTK                           = 22,
    MSG_GPS2_RAW                          = 23,
    MSG_GPS2_RTK                          = 24,
    MSG_SYSTEM_TIME                       = 25,
    MSG_SERVO_OUT                         = 26,
    MSG_NEXT_MISSION_REQUEST_WAYPOINTS    = 27,
    MSG_NEXT_MISSION_REQUEST_RALLY        = 28,
    MSG_NEXT_MISSION_REQUEST_FENCE        = 29,
    MSG_NEXT_PARAM                        = 30,
    MSG_FENCE_STATUS                      = 31,
    MSG_AHRS                              = 32,
    MSG_SIMSTATE                          = 33,
    MSG_SIM_STATE                         = 34,
    MSG_AHRS2                             = 35,
    MSG_HWSTATUS                          = 36,
    MSG_WIND                              = 37,
    MSG_RANGEFINDER                       = 38,
    MSG_DISTANCE_SENSOR                   = 39,
    MSG_TERRAIN                           = 40,
    MSG_BATTERY2                          = 41,
    MSG_CAMERA_FEEDBACK                   = 42,
    MSG_GIMBAL_DEVICE_ATTITUDE_STATUS     = 43,
    MSG_GIMBAL_MANAGER_INFORMATION        = 44,
    MSG_OPTICAL_FLOW                      = 45,
    MSG_MAG_CAL_PROGRESS                  = 46,
    MSG_MAG_CAL_REPORT                    = 47,
    MSG_EKF_STATUS_REPORT                 = 48,
    MSG_LOCAL_POSITION                    = 49,
    MSG_PID_TUNING                        = 50,
    MSG_VIBRATION                         = 51,
    MSG_RPM                               = 52,
    MSG_WHEEL_DISTANCE                    = 53,
    MSG_MISSION_ITEM_REACHED              = 54,
    MSG_POSITION_TARGET_GLOBAL_INT        = 55,
    MSG_POSITION_TARGET_LOCAL_NED         = 56,
    MSG_ADSB_VEHICLE                      = 57,
    MSG_BATTERY_STATUS                    = 58,
    MSG_AOA_SSA                           = 59,
    MSG_LANDING                           = 60,
    MSG_ESC_TELEMETRY                     = 61,
    MSG_ORIGIN                            = 62,
    MSG_HOME                              = 63,
    MSG_NAMED_FLOAT                       = 64,
    MSG_EXTENDED_SYS_STATE                = 65,
    MSG_AUTOPILOT_VERSION                 = 66,
    MSG_EFI_STATUS                        = 67,
    MSG_GENERATOR_STATUS                  = 68,
    MSG_WINCH_STATUS                      = 69,
    MSG_WATER_DEPTH                       = 70,
    MSG_HIGH_LATENCY2                     = 71,
    MSG_AIS_VESSEL                        = 72,
    MSG_MCU_STATUS                        = 73,
    MSG_UAVIONIX_ADSB_OUT_STATUS          = 74,
    MSG_ATTITUDE_TARGET                   = 75,
    MSG_HYGROMETER                        = 76,
    MSG_AUTOPILOT_STATE_FOR_GIMBAL_DEVICE = 77,
    MSG_LAST // MSG_LAST must be the last entry in this enum
};
