"""
Waf tool for functions common to the esp32, Linux and ChibiOS builds.

AP_FLAKE8_CLEAN
"""


def load_env_vars(env, hwdef_env):
    '''load environment variables from the hwdef generator'''
    for k, v in hwdef_env.items():
        if k in env:
            # don't want to encourage modifications from the hwdef
            raise ValueError(f"hwdef redefines environment variable {k} "
                             f"with existing value {env[k]!r} to value {v!r}")
        else:
            env[k] = v
            print("env set %s=%s" % (k, v))


def handle_hwdef_files(cfg, hwdef_files):
    # note files generated by hwdef system as cfg_files. this ensures they
    # don't get deleted on `./waf clean`. this also ensures their node exists
    # so implicit dependencies are properly tracked.

    bldnode = cfg.bldnode.make_node(cfg.variant)
    for file in sorted(hwdef_files):
        cfg.env.append_value("cfg_files", bldnode.make_node(file).abspath())
