#!/usr/bin/env python3
# AP_FLAKE8_CLEAN
'''
Class generator for the Zephyr port: emits the CLASS-3 (per-board,
hwdef.dat-derivable) devicetree overlay and Kconfig fragment, plus the
CLASS-1 SoC-invariant facts (eDMA request numbers) those emissions need.

INERT BY DEFAULT: with no PIN/DMA directives in a board's hwdef.dat this
emits an empty overlay and an empty fragment, and the build is required to
be byte-identical to a build without the generator (the phase-1 gate,
passed 2026-08-14 on mr_vmu_rt1176 against a fresh-config baseline).
Boards adopt it per-peripheral: add PIN lines, delete the now-redundant
hand-written DTS lines, re-verify. The existing hand-written board DTS is
never modified by this tool - side-by-side comparison is the point.

Directives consumed (all optional; parsed by zephyr_hwdef.py into
hwdef.gen_lines / hwdef.can_order, unknown ones ignored elsewhere):

  PIN <PAD> <FUNC> [<dts-prop> ...]
      Pad mux for one peripheral signal - the exact analogue of ChibiOS's
      "PA4 SPI1_CS" lines. The PAD/FUNC pair must name an entry in the
      SoC family's upstream pinctrl catalog (validated; per-family
      naming handled by the backends below):
        NXP i.MX RT:  PIN GPIO_AD_24 LPUART1_TXD     -> &iomuxc_gpio_ad_24_lpuart1_txd
        STM32:        PIN PB10 USART3_TX             -> &usart3_tx_pb10
        ESP32-S3:     PIN GPIO17 UART1_TX            -> UART1_TX_GPIO17 (GPIO matrix)
      Extra tokens are devicetree properties applied to that pin
      (boolean, or name=value for cells), plus one reserved token:

        periph=<NAME>   the peripheral this pin belongs to, when the pad
                        function does not name it. An SPI chip select taken
                        as plain GPIO (GPIO_MUX2_IO11_CM7) needs
                        periph=LPSPI1; a pad muxed to the XBAR that routes
                        to a timer needs periph=QTMR1. <parent>/<child>
                        emits the pinctrl onto a child node instead, e.g.
                        periph=timers1/pwm.

  DMA <PERIPH> <rx_ch> <tx_ch>   |   DMA <PERIPH> <ch>
      Pin the eDMA channel numbers for a peripheral instance (NXP only),
      e.g. DMA LPUART3 20 21. Peripherals whose DMAMUX entry is a single
      bidirectional request (LPI2C) take one channel instead, and emit
      dma-names = "transfer". Channels are board allocation choices
      (class 3); the DMAMUX request SOURCES are silicon facts (class 1)
      extracted from the vendored SoC header, never hardcoded here.
      STM32 refuses this loudly (H7 DMA needs the stream solver - see the
      strategy doc); ESP32 refuses it (GDMA is driver-internal, no dmas
      property exists to emit).

A peripheral is emitted ONLY when it has at least one PIN line - exactly
like ChibiOS, where a UART without pins does not exist. SERIAL_ORDER /
I2C_ORDER / CAN_ORDER / IMU / BARO membership alone changes nothing, so
legacy boards whose pins live in the hand DTS build unchanged.

TWO THINGS THIS CANNOT EXPRESS, both of which keep a peripheral in the
hand-written DTS:

  - A DISABLED peripheral. Every emitted node carries status = "okay",
    so a node that must stay disabled (a bus brought out on the schematic
    but unpopulated) cannot be described here.
  - a peripheral whose child node needs properties other than pinctrl.
    periph=<parent>/<child> puts the pinctrl on the child, which is what
    st,stm32-timers wants (the binding has no pinctrl-0; its st,stm32-pwm
    child does) and what a FlexIO DShot block wants. Anything else the
    child needs still comes from the hand DTS.

Standalone CLI (side-by-side inspection, never touches the build tree):
  python3 Tools/ardupilotwaf/zephyr_class_generator.py <hwdef.dat> \
      [--overlay out.overlay] [--conf out.conf] [--zephyr-base modules/zephyr]
  python3 Tools/ardupilotwaf/zephyr_class_generator.py --selftest
'''

import os
import re
import sys

AUTOGEN_HEADER = (
    '/* AUTOGENERATED by zephyr_class_generator.py from %s - DO NOT EDIT.\n'
    ' * Empty when the board declares no PIN/DMA directives (inert default).\n'
    ' */\n')


def _render_prop(p, indent):
    '''One PIN extra token -> a DTS property line. Three shapes:
    boolean (input-enable), cell (max-frequency=1000000 -> <1000000>),
    string (drive-strength=high -> "high" - pinctrl enums are strings).'''
    if '=' not in p:
        return '%s%s;' % (indent, p)
    k, v = p.split('=', 1)
    if re.fullmatch(r'-?(0[xX][0-9a-fA-F]+|\d+)', v):
        return '%s%s = <%s>;' % (indent, k, v)
    return '%s%s = "%s";' % (indent, k, v.strip('\"'))


class Backend:
    '''Per-SoC-family knowledge: pad-macro naming + catalog validation,
    pinctrl emission shape, node labelling, DMA emission. One subclass per
    family; a family without a backend fails PIN lines loudly rather than
    guessing.'''

    name = 'abstract'

    # Devicetree sources for this family, relative to zephyr_base. The node
    # labels the emitter targets are READ FROM HERE, never hardcoded: see
    # resolve_node(). Every label this port needs already exists in the SoC
    # dtsi, so a table of vendor prefixes would only be a second, staler copy.
    dts_roots = ()

    # The residue no naming rule can reach, kept as data rather than code.
    # A pad says TIM1_CH1 while the node is labelled timers1; ESP32 calls its
    # CAN controller twai and gives it no instance number.
    label_aliases = {}

    def __init__(self, zephyr_base, mcu=''):
        self.zephyr_base = zephyr_base
        self.mcu = mcu
        self._labels = None

    def soc_dts_hint(self):
        '''Substring identifying THIS SoC's devicetree files. A vendor ships
        many SoCs in one directory and they reuse label names, so an
        unscoped scan answers SPI1 with some other part's spi1 instead of
        this part's lpspi1.'''
        return None

    def _load_labels(self):
        '''Every node label this SoC defines. Two shapes appear:
        "lpuart3: uart@40084000 {" and, for nodes with no unit address such
        as the FlexPWM submodules, "flexpwm1_pwm0: flexpwm1_pwm0 {".'''
        if self._labels is not None:
            return self._labels
        pat = re.compile(r'\b([a-z][a-z0-9_]*)\s*:\s*[a-z0-9_@,-]+\s*\{')
        hint = (self.soc_dts_hint() or '').lower()
        found = []
        for root in self.dts_roots:
            base = os.path.join(self.zephyr_base, *root.split('/'))
            for dirpath, _dirs, files in os.walk(base):
                for fn in files:
                    if not fn.endswith(('.dtsi', '.dts')):
                        continue
                    # A "<part>-pinctrl.dtsi" holds one node per PAD
                    # (usart2_tx_pd5), not per peripheral. Harvesting those
                    # as peripheral labels makes resolve_node match a pad and
                    # emit pinctrl onto it. STM32 ships 175 such files.
                    if fn.endswith('-pinctrl.dtsi'):
                        continue
                    path = os.path.join(dirpath, fn)
                    if hint and hint not in path.lower():
                        continue
                    found.append(path)
        self._labels = set()
        for path in found:
            try:
                with open(path, 'r', errors='ignore') as f:
                    for m in pat.finditer(f.read()):
                        self._labels.add(m.group(1))
            except OSError:
                pass
        return self._labels

    def resolve_node(self, token):
        '''Pad function or peripheral token -> devicetree node label.

        LPUART3_RX    -> lpuart3         longest label the token starts with
        FLEXPWM1_PWM1_A -> flexpwm1_pwm1 same rule, submodule kept
        CAN1_TX       -> flexcan1        no label "can1", so match the tail
        ADC1_CH2A     -> lpadc1          likewise

        Returns None when nothing matches, which is the right answer for a
        pad muxed as plain GPIO: those need an explicit owner.'''
        t = token.lower()
        if t in self.label_aliases:
            return self.label_aliases[t]
        labels = self._load_labels()
        if t in labels:
            return t

        # Family renames no string rule can derive (eth -> mac). Applied to
        # the whole token, longest prefix first, and only believed when the
        # result names a real node.
        for pat, repl in self.alias_rules:
            m = re.match(pat, t)
            if m:
                cand = m.expand(repl)
                if cand in labels:
                    return cand

        # longest label that the token begins with, on an underscore boundary
        best = None
        for lab in labels:
            if t.startswith(lab) and (len(t) == len(lab) or t[len(lab)] == '_'):
                if best is None or len(lab) > len(best):
                    best = lab
        if best:
            return best

        # Underscore elision: a pad function spells the peripheral as the reference
        # manual does and the devicetree as the binding author did.
        parts = t.split('_')
        for k in range(len(parts), 0, -1):
            head_parts = parts[:k]
            for mask in range(1 << (k - 1)):
                cand = head_parts[0]
                for i in range(1, k):
                    cand += ('' if (mask >> (i - 1)) & 1 else '_') + head_parts[i]
                if cand in labels:
                    return cand
                for pat, repl in self.alias_rules:
                    m = re.fullmatch(pat, cand)
                    if m and m.expand(repl) in labels:
                        return m.expand(repl)

        # Instance-number mismatch between pad name and node label, both ways:
        # PCNT0_CH0SIG with a node called pcnt, LEDC_CH0 with a node ledc0.
        head = parts[0]
        if head in self.label_aliases:
            return self.label_aliases[head]
        bare = head.rstrip('0123456789')
        if bare and bare != head and bare in labels:
            return bare
        if bare == head:
            numbered = sorted(l for l in labels
                              if l.startswith(head) and l[len(head):].isdigit())
            if len(numbered) == 1:
                return numbered[0]
            return None

        # the IP block named by the pad, then the label that ends with it.
        # Only when the block carries an instance number: a pad muxed as
        # plain GPIO says GPIO_MUX2_IO11_CM7, which names the mux and not an
        # owner, and must fall through to "say it with periph=".
        if not re.search(r'\d', head):
            return None
        cands = [lab for lab in labels if lab.endswith(head)]
        if len(cands) == 1:
            return cands[0]
        if cands:
            return min(cands, key=len)
        return None

    # Generic instance naming. The resolver maps these onto whatever the SoC
    # actually calls the node, so SPI1 finds lpspi1 on NXP and spi1 on STM32.
    def spi_periph(self, bus_num):
        return 'SPI%s' % bus_num

    def i2c_periph(self, n):
        return 'I2C%s' % n

    def can_periph(self, n):
        return 'CAN%s' % n

    # SERIAL_ORDER token -> peripheral instance name (family naming) or None
    def serial_instance(self, token):
        raise NotImplementedError

    # instance -> ArduPilot serialN alias number (the instance digits)
    @staticmethod
    def serial_alias_num(instance):
        m = re.search(r'(\d+)$', instance)
        return m.group(1) if m else None

    # -> (pad_ref, error_or_None); pad_ref is backend-private
    def pin_ref(self, pad, func):
        raise NotImplementedError

    # Family renames that no string transformation can derive, as
    # (pattern, replacement) applied to a whole token or to a candidate.
    # Every result is checked against the real node labels before use, so an
    # over-eager rule costs nothing on a part that lacks the node.
    alias_rules = ()

    # label is the finished pinctrl group label; pins is [(pad_ref, props)]
    # -> (pinctrl value or None, [extra node text])
    def emit_pinctrl(self, label, pins):
        raise NotImplementedError

    # channels: (rx,tx) -> ([property lines], error_or_None)
    def dma_props(self, periph, channels):
        return ([], '%s: DMA directive not supported on %s' % (periph, self.name))


class NXPBackend(Backend):
    '''i.MX RT: pad-mux phandles (&iomuxc_<pad>_<func>) wrapped in a group
    node; eDMA dmas = <&edma0 CH SRC> with SRC from the vendored DMAMUX
    header of the right device family.'''

    name = 'nxp-imxrt'
    dts_roots = ('dts/arm/nxp',)

    def soc_dts_hint(self):
        # MIMXRT1176 -> rt11xx, the series dtsi that defines this part's nodes
        m = re.search(r'(\d{2})\d{2}', self.mcu or '')
        return 'rt%sxx' % m.group(1) if m else None

    _DEVICES_RT = os.path.join('modules', 'hal', 'nxp', 'mcux', 'mcux-sdk-ng',
                               'devices', 'RT')
    _HAL_PINCTRL = os.path.join('modules', 'hal', 'nxp', 'dts', 'nxp',
                                'nxp_imx', 'rt')

    def __init__(self, zephyr_base, mcu=''):
        super().__init__(zephyr_base, mcu)
        self._dmamux = None
        self._catalog = None

    def serial_instance(self, token):
        t = token.upper()
        for prefix in ('LPUART', 'USART', 'UART'):
            if t.startswith(prefix) and t[len(prefix):].isdigit():
                return 'LPUART' + t[len(prefix):]
        return None

    def _load_catalog(self):
        if self._catalog is not None:
            return self._catalog
        self._catalog = set()
        # Pad nodes live in hal_nxp, one file per part
        # (mimxrt1176dvmaa-pinctrl.dtsi), not under dts/arm/nxp. Narrow to the
        # part family so an RT1060 board cannot validate against RT1170 pads;
        # fall back to the whole directory when the MCU name says nothing.
        root = os.path.join(self.zephyr_base, self._HAL_PINCTRL)
        m = re.match(r'(mimxrt\d{3})', (self.mcu or '').lower())
        fam = m.group(1) if m else None
        pat = re.compile(r'\b(iomuxc[a-z0-9_]*)\s*:')
        try:
            for fn in os.listdir(root):
                if not fn.endswith('-pinctrl.dtsi'):
                    continue
                if fam and not fn.startswith(fam):
                    continue
                with open(os.path.join(root, fn), 'r', errors='ignore') as f:
                    for m2 in pat.finditer(f.read()):
                        self._catalog.add(m2.group(1))
        except OSError:
            pass
        return self._catalog

    def pin_ref(self, pad, func):
        macro = 'iomuxc_%s_%s' % (pad.lower(), func.lower())
        cat = self._load_catalog()
        if cat and macro not in cat:
            return None, 'no such pad macro %s in the upstream catalog' % macro
        return macro, None

    def emit_pinctrl(self, label, pins):
        by_props = {}
        for ref, props in pins:
            by_props.setdefault(props, []).append(ref)
        lines = ['&pinctrl {', '\t%s: %s {' % (label, label)]
        for gi, (props, refs) in enumerate(sorted(by_props.items())):
            lines.append('\t\tgroup%d {' % gi)
            joined = ',\n\t\t\t\t '.join('<&%s>' % r for r in refs)
            lines.append('\t\t\tpinmux = %s;' % joined)
            for p in props:
                lines.append(_render_prop(p, '\t\t\t'))
            lines.append('\t\t};')
        lines.append('\t};')
        lines.append('};')
        return '<&%s>' % label, ['\n'.join(lines)]

    def _device_dir(self):
        '''devices/RT/<family> dir for this MCU. MIMXRT1176 lives under
        RT1170 (family dir, not part number) - exact dir first, then the
        tens-truncated family. Selecting the right dir matters: every
        family ships a PERI_DMAMUX.h and the request numbers DIFFER
        between families (selftest-caught when a blind walk merged them).'''
        m = re.search(r'(\d{3,4})', self.mcu or '')
        root = os.path.join(self.zephyr_base, self._DEVICES_RT)
        if m:
            num = int(m.group(1))
            for cand in ('RT%d' % num, 'RT%d' % (num // 10 * 10)):
                if os.path.isdir(os.path.join(root, cand)):
                    return os.path.join(root, cand)
        return root

    def _load_dmamux(self):
        if self._dmamux is not None:
            return self._dmamux
        self._dmamux = {}
        # Two shapes in the same header: split Tx/Rx requests (LPUART, LPSPI)
        # and a single bidirectional request (LPI2C, FLEXCAN). Store the
        # latter under 'one'.
        pat_dir = re.compile(r'kDmaRequestMux(\w+?)(Tx|Rx)\s*=\s*(\d+)')
        pat_one = re.compile(r'kDmaRequestMux([A-Za-z][A-Za-z0-9_]*?)\s*=\s*(\d+)')
        for dirpath, _dirs, files in os.walk(self._device_dir()):
            for fn in files:
                if fn != 'PERI_DMAMUX.h':
                    continue
                with open(os.path.join(dirpath, fn), 'r', errors='ignore') as f:
                    text = f.read()
                for m in pat_dir.finditer(text):
                    p, d, v = m.group(1).upper(), m.group(2).lower(), int(m.group(3))
                    self._dmamux.setdefault(p, {})[d] = v
                for m in pat_one.finditer(text):
                    name = m.group(1)
                    if name.endswith(('Tx', 'Rx')):
                        continue
                    self._dmamux.setdefault(name.upper(), {})['one'] = int(m.group(2))
        return self._dmamux

    def dma_props(self, periph, channels):
        tab = self._load_dmamux().get(periph.upper())
        if not tab:
            return [], ('DMA %s: no DMAMUX request entry in the vendored SoC '
                        'header' % periph)
        if len(channels) == 1:
            if 'one' not in tab:
                return [], ('DMA %s: one channel given but this peripheral has '
                            'separate rx/tx DMAMUX requests' % periph)
            return (['\tdmas = <&edma0 %d %d>;' % (channels[0], tab['one']),
                     '\tdma-names = "transfer";'], None)
        if 'rx' not in tab or 'tx' not in tab:
            return [], ('DMA %s: two channels given but this peripheral has a '
                        'single bidirectional DMAMUX request' % periph)
        rx_ch, tx_ch = channels
        return (['\tdmas = <&edma0 %d %d>, <&edma0 %d %d>;'
                 % (rx_ch, tab['rx'], tx_ch, tab['tx']),
                 '\tdma-names = "rx", "tx";'], None)


class STM32Backend(Backend):
    '''STM32: upstream ships pre-defined signal@pad nodes
    (usart3_tx_pb10) in hal_stm32's per-part pinctrl dtsi - pinctrl-0
    references them DIRECTLY, no wrapper group. Per-pin extra props become
    override nodes on those labels. DMA is refused: H7 stream allocation
    needs the solver deliberately deferred in the strategy doc.'''

    name = 'stm32'
    dts_roots = ('dts/arm/st', 'modules/hal/stm32/dts/st')

    def soc_dts_hint(self):
        # STM32H743xx -> h7
        return (self.mcu or '')[5:7].lower() or None

    # A pad says TIM1_CH1 while the node is labelled timers1. As a regex so
    # it covers every timer the part has, not a hand-kept range: H7 alone
    # goes up to timers24.
    alias_rules = (
        (r'tim(\d+)(?:_.*)?$', r'timers\1'),
        # the ethernet MAC pads all say eth_*, the node is plain "mac"
        (r'eth_.*$', r'mac'),
        # OCTOSPIM port 1/2 pads front the octospi1/octospi2 controllers
        (r'octospim_p(\d)_.*$', r'octospi\1'),
        (r'xspim_p(\d)_.*$', r'xspi\1'),
    )
    label_aliases = {}
    _HAL_DTS = os.path.join('modules', 'hal', 'stm32', 'dts', 'st')

    def __init__(self, zephyr_base, mcu=''):
        super().__init__(zephyr_base, mcu)
        self._catalog = None

    def serial_instance(self, token):
        t = token.upper()
        for prefix in ('LPUART', 'USART', 'UART'):
            if t.startswith(prefix) and t[len(prefix):].isdigit():
                return prefix + t[len(prefix):]   # family keeps usart/uart distinct
        return None

    def _family_dir(self):
        # STM32H743xx -> h7 (same slice the mfr rules use for the soc name)
        fam = (self.mcu or '')[5:7].lower()
        return os.path.join(self.zephyr_base, self._HAL_DTS, fam)

    def _load_catalog(self):
        if self._catalog is not None:
            return self._catalog
        self._catalog = set()
        pat = re.compile(r'\b([a-z0-9_]+)\s*:\s*\1\s*{')
        try:
            for fn in os.listdir(self._family_dir()):
                if not fn.endswith('-pinctrl.dtsi'):
                    continue
                with open(os.path.join(self._family_dir(), fn), 'r', errors='ignore') as f:
                    for m in pat.finditer(f.read()):
                        self._catalog.add(m.group(1))
        except OSError:
            pass
        return self._catalog

    def pin_ref(self, pad, func):
        label = '%s_%s' % (func.lower(), pad.lower())    # usart3_tx_pb10
        cat = self._load_catalog()
        if cat and label not in cat:
            return None, 'no such pinctrl node %s in hal_stm32 for %s' % (label, self.mcu)
        return label, None

    def emit_pinctrl(self, label, pins):
        del label            # STM32 references upstream's per-pad nodes directly
        refs = ' '.join('&%s' % ref for ref, _props in pins)
        extra = []
        for ref, props in pins:
            if not props:
                continue
            lines = ['&%s {' % ref]
            for p in props:
                lines.append(_render_prop(p, '\t'))
            lines.append('};')
            extra.append('\n'.join(lines))
        return '<%s>' % refs, extra

    def dma_props(self, periph, channels):
        return [], ('DMA %s: STM32 dmas emission not implemented - H7 '
                    'DMA/DMAMUX stream allocation needs the solver' % periph)


class ESP32Backend(Backend):
    '''ESP32 GPIO matrix: any signal to any pin via numeric
    <FUNC>_GPIO<n> macros from the dt-bindings pinctrl header; groups look
    like NXP's but pinmux values are macros, not phandles. DMA is refused:
    GDMA is driver-internal on this family, there is no dmas property.'''

    name = 'esp32'
    dts_roots = ('dts/xtensa/espressif', 'dts/riscv/espressif')

    def soc_dts_hint(self):
        return self._variant()

    # Pads say SPIM2 (master) or SPIS2 (slave); both front the spi2
    # controller. As a regex so a variant with more SPI instances works
    # without editing this table.
    alias_rules = (
        (r'spi[ms](\d+)(?:_.*)?$', r'spi\1'),
    )
    # The CAN controller has no instance number in the devicetree.
    label_aliases = {'can1': 'twai', 'can2': 'twai', 'twai': 'twai'}

    def __init__(self, zephyr_base, mcu=''):
        super().__init__(zephyr_base, mcu)
        self._catalog = None

    def _variant(self):
        return (self.mcu or 'esp32').split('/')[0].lower()   # esp32s3

    def serial_instance(self, token):
        t = token.upper()
        for prefix in ('USART', 'UART'):
            if t.startswith(prefix) and t[len(prefix):].isdigit():
                return 'UART' + t[len(prefix):]
        return None

    def _load_catalog(self):
        if self._catalog is not None:
            return self._catalog
        self._catalog = set()
        hdr = os.path.join(self.zephyr_base, 'include', 'zephyr', 'dt-bindings',
                           'pinctrl', '%s-pinctrl.h' % self._variant())
        pat = re.compile(r'^#define\s+(\w+_GPIO\d+)\s', re.M)
        try:
            with open(hdr, 'r', errors='ignore') as f:
                for m in pat.finditer(f.read()):
                    self._catalog.add(m.group(1))
        except OSError:
            pass
        return self._catalog

    def pin_ref(self, pad, func):
        m = re.match(r'GPIO(\d+)$', pad.upper())
        if not m:
            return None, 'ESP32 pads are GPIO<n>, got %s' % pad
        macro = '%s_GPIO%s' % (func.upper(), m.group(1))
        cat = self._load_catalog()
        if cat and macro not in cat:
            return None, 'no such pinmux macro %s in %s-pinctrl.h' % (macro, self._variant())
        return macro, None

    def emit_pinctrl(self, label, pins):
        by_props = {}
        for ref, props in pins:
            by_props.setdefault(props, []).append(ref)
        lines = ['&pinctrl {', '\t%s: %s {' % (label, label)]
        for gi, (props, refs) in enumerate(sorted(by_props.items())):
            lines.append('\t\tgroup%d {' % gi)
            joined = ',\n\t\t\t\t '.join('<%s>' % r for r in refs)
            lines.append('\t\t\tpinmux = %s;' % joined)
            for p in props:
                lines.append(_render_prop(p, '\t\t\t'))
            lines.append('\t\t};')
        lines.append('\t};')
        lines.append('};')
        return '<&%s>' % label, ['\n'.join(lines)]


_BACKENDS = {
    'nxp': NXPBackend,
    'stm32': STM32Backend,
    'esp32': ESP32Backend,
}


class ZephyrClassGenerator:
    def __init__(self, hwdef, zephyr_base):
        '''hwdef: a parsed zephyr_hwdef.ZephyrHWDef instance.'''
        self.hwdef = hwdef
        self.zephyr_base = zephyr_base
        self.errors = []
        mfr, _soc = hwdef.get_mfr_soc()
        cls = _BACKENDS.get(mfr)
        self.backend = cls(zephyr_base, hwdef.mcu) if cls else None

        # {(node_label, state): [(pad_ref, props), ...]}; refs are backend-private
        self.pins = {}
        # {node_label: (rx_ch, tx_ch)} or {node_label: (ch,)}
        self.dma_ch = {}
        # {node_label: [dts prop tokens]} from PERIPH directives
        self.node_props = {}
        # first-seen order, so emission is stable and readable
        self.node_order = []
        self._ingest_directives()

    def _node(self, token, where):
        """Token -> devicetree node label, or None with an error recorded."""
        if self.backend is None:
            return None
        label = self.backend.resolve_node(token)
        if label is None:
            self.errors.append(
                '%s: cannot tell which devicetree node "%s" belongs to; name it '
                'with periph=<node label>' % (where, token))
        return label

    def _add_node(self, label):
        if label not in self.node_order:
            self.node_order.append(label)

    def _ingest_directives(self):
        for tokens in getattr(self.hwdef, 'gen_lines', []):
            if tokens[0] == 'PIN' and len(tokens) >= 3:
                if self.backend is None:
                    self.errors.append('PIN directive but no backend for this '
                                       'SoC family (mcu=%s): %s'
                                       % (self.hwdef.mcu, ' '.join(tokens)))
                    continue
                pad, func = tokens[1], tokens[2]
                # Two reserved tokens; everything else is a devicetree property.
                owner = None
                state = 'default'
                props = []
                for t in tokens[3:]:
                    low = t.lower()
                    if low.startswith('periph='):
                        owner = t.split('=', 1)[1]
                    elif low.startswith('state='):
                        state = t.split('=', 1)[1]
                    else:
                        props.append(t)
                ref, err = self.backend.pin_ref(pad, func)
                if err:
                    self.errors.append('PIN %s %s: %s' % (pad, func, err))
                    continue
                if owner:
                    # An explicit owner is taken at its word. It may name a
                    # node the SoC dtsi never mentions, such as a DShot block
                    # declared in the board's own devicetree.
                    label = self.backend.resolve_node(owner) or owner.lower()
                else:
                    label = self._node(func, 'PIN %s %s' % (pad, func))
                if label is None:
                    continue
                self._add_node(label)
                self.pins.setdefault((label, state), []).append((ref, tuple(props)))
            elif tokens[0] == 'DMA' and len(tokens) >= 3:
                # DMA <PERIPH> <rx> <tx>, or DMA <PERIPH> <ch> where the
                # peripheral has one bidirectional DMAMUX request.
                label = self._node(tokens[1], 'DMA %s' % tokens[1])
                if label is None:
                    continue
                try:
                    self.dma_ch[label] = tuple(int(t, 0) for t in tokens[2:4])
                except ValueError:
                    self.errors.append('DMA: bad channel numbers: %s' % ' '.join(tokens))
            elif tokens[0] == 'PERIPH' and len(tokens) >= 3:
                # PERIPH <node> <dts-prop>...  node-level properties.
                # status is one of them, so a peripheral whose pads are wired
                # but whose bus is not in use can say status=disabled instead
                # of being undescribable.
                label = self._node(tokens[1], 'PERIPH %s' % tokens[1])
                if label is None:
                    continue
                self.node_props.setdefault(label, []).extend(tokens[2:])

    def _states(self, label):
        """Pinctrl states declared for a node, default first."""
        got = [st for (lab, st) in self.pins if lab == label]
        got.sort(key=lambda st: (st != 'default', st))
        return got

    def _has_pins(self, label):
        return bool(label) and any(lab == label for (lab, _st) in self.pins)

    def overlay_text(self):
        if self.backend is None or not self.pins:
            return AUTOGEN_HEADER % self.hwdef.hwdef_path
        out = [AUTOGEN_HEADER % self.hwdef.hwdef_path]
        extra_nodes = []
        periph_nodes = []
        aliases = []
        emitted = set()

        def emit_node(label):
            if not label or label in emitted or not self._has_pins(label):
                return False
            emitted.add(label)
            states = self._states(label)
            # "timers1/pwm" -> emit into the pwm child of &timers1. Some
            # bindings put pinctrl on a child rather than the peripheral:
            # st,stm32-timers has no pinctrl-0, its st,stm32-pwm child does,
            # and a FlexIO DShot block is the same shape.
            parent, _, child = label.partition('/')
            safe = label.replace('/', '_')
            ind = '\t\t' if child else '\t'
            values, names = [], []
            for st in states:
                group = ('pinmux_%s_gen' % safe if st == 'default'
                         else 'pinmux_%s_%s_gen' % (safe, st))
                value, extras = self.backend.emit_pinctrl(group, self.pins[(label, st)])
                extra_nodes.extend(extras)
                if value:
                    values.append(value)
                    names.append(st)
            body = []
            for i, value in enumerate(values):
                body.append('%spinctrl-%d = %s;' % (ind, i, value))
            if names:
                body.append('%spinctrl-names = %s;'
                            % (ind, ', '.join('"%s"' % n for n in names)))
            props = self.node_props.get(label, [])
            if not any(t.split('=')[0] == 'status' for t in props):
                body.append('%sstatus = "okay";' % ind)
            for t in props:
                body.append(_render_prop(t, ind))
            if label in self.dma_ch:
                dprops, err = self.backend.dma_props(label, self.dma_ch[label])
                if err:
                    self.errors.append(err)
                body += [('\t' + d) if child else d for d in dprops]
            if child:
                node = (['&%s {' % parent, '\tstatus = "okay";', '\t%s {' % child]
                        + body + ['\t};', '};'])
            else:
                node = ['&%s {' % parent] + body + ['};']
            periph_nodes.append('\n'.join(node))
            return True

        # CLASS 3: SERIAL_ORDER -> UART enables + serialN aliases
        for token in self.hwdef.serial_order:
            inst = self.backend.serial_instance(token)
            label = self.backend.resolve_node(inst) if inst else None
            if label and emit_node(label):
                n = self.backend.serial_alias_num(inst)
                if n is not None:
                    aliases.append('\t\tserial%s = &%s;' % (n, label))

        # CLASS 3: I2C_ORDER / CAN_ORDER -> bus enables
        for token in self.hwdef.i2c_order:
            t = token.upper().replace('LPI2C', '').replace('I2C', '')
            if t.isdigit():
                emit_node(self.backend.resolve_node(self.backend.i2c_periph(t)))
        for token in getattr(self.hwdef, 'can_order', []):
            if token.isdigit():
                emit_node(self.backend.resolve_node(self.backend.can_periph(token)))

        # CLASS 3: SPIDEV buses -> SPI enables; IMU lines -> spi-imuN aliases
        spi_buses = []
        for dev in self.hwdef.spidevs:
            if dev['bus'] not in spi_buses:
                spi_buses.append(dev['bus'])
        for bus in spi_buses:
            emit_node(self.backend.resolve_node(self.backend.spi_periph(bus)))
        imu_idx = 0
        for imu in self.hwdef.imus:
            name = (imu.get('devices') or [''])[0]
            for dev in self.hwdef.spidevs:
                label = self.backend.resolve_node(self.backend.spi_periph(dev['bus']))
                if dev['name'] == name and self._has_pins(label):
                    alias = '\t\tspi-imu%d = &%s;' % (imu_idx, label)
                    if alias not in aliases:
                        aliases.append(alias)
                        imu_idx += 1
                    break

        # anything else with pins (PWM blocks, ADC, SD, ...) still gets emitted
        for label in self.node_order:
            emit_node(label)

        out.extend(n + '\n' for n in extra_nodes)
        out.extend(n + '\n' for n in periph_nodes)
        if aliases:
            out.append('/ {\n\taliases {\n%s\n\t};\n};\n' % '\n'.join(aliases))
        return '\n'.join(out)

    def conf_text(self, existing_assignments=None):
        '''Feature-inference Kconfig fragment (the ChibiOS not-quite-constant
        rules). MERGE-AWARE: a symbol already assigned by an earlier fragment
        is skipped, so legacy boards with hand-written conf lines stay
        byte-identical and duplicate-assignment warnings cannot arise.'''
        existing = existing_assignments or set()
        lines = ['# AUTOGENERATED by zephyr_class_generator.py - DO NOT EDIT.',
                 '# Feature-inference rules from hwdef.dat; empty when every',
                 '# inferred symbol is already set by an earlier fragment.']
        rules = []
        if self.backend and getattr(self.hwdef, 'can_order', []) and \
                any(self._has_pins(self.backend.resolve_node(self.backend.can_periph(t)))
                    for t in self.hwdef.can_order if t.isdigit()):
            rules.append(('CONFIG_CAN', 'y'))
        # future rules land here: RAM-class buffer sizes, ETH -> CONFIG_NET*,
        # IOMCU, ...
        for sym, val in rules:
            if sym not in existing:
                lines.append('%s=%s' % (sym, val))
        return '\n'.join(lines) + '\n'

    def write(self, overlay_path, conf_path, existing_assignments=None):
        with open(overlay_path, 'w') as f:
            f.write(self.overlay_text())
        with open(conf_path, 'w') as f:
            f.write(self.conf_text(existing_assignments))
        return not self.errors


# ---- standalone CLI / selftest ---------------------------------------

_SELFTEST_NXP = '''\
MCU MIMXRT1176
SERIAL_ORDER OTG1 USART3
CAN_ORDER 1
I2C_ORDER I2C2
IMU Invensensev3 SPI:imu1 ROTATION_NONE
SPIDEV imu1 SPI1 DEVID1 IMU1_CS MODE3 2*MHZ 24*MHZ
PIN GPIO_AD_30 LPUART3_TX
PIN GPIO_AD_31 LPUART3_RX bias-pull-up drive-strength=high
DMA LPUART3 20 21
PIN GPIO_AD_06 CAN1_TX
PIN GPIO_AD_07 CAN1_RX
PIN GPIO_EMC_B2_00 LPSPI1_SCK
PIN GPIO_EMC_B2_02 LPSPI1_SDO
PIN GPIO_EMC_B2_03 LPSPI1_SDI
'''

_SELFTEST_STM32 = '''\
MCU STM32H743xx
SERIAL_ORDER OTG1 USART3
PIN PB10 USART3_TX
PIN PB11 USART3_RX bias-pull-up
DMA USART3 0 1
'''

_SELFTEST_ESP32 = '''\
MCU ESP32S3
SERIAL_ORDER UART1
PIN GPIO17 UART1_TX
PIN GPIO18 UART1_RX
'''


def _mkgen(zephyr_hwdef, td, text, zephyr_base):
    p = os.path.join(td, 'hwdef.dat')
    with open(p, 'w') as f:
        f.write(text)
    return ZephyrClassGenerator(zephyr_hwdef.ZephyrHWDef(p), zephyr_base), p


def _selftest(zephyr_base):
    import tempfile

    import zephyr_hwdef
    failed = []
    with tempfile.TemporaryDirectory() as td:
        # ---- NXP ----
        gen, p = _mkgen(zephyr_hwdef, td, _SELFTEST_NXP, zephyr_base)
        overlay = gen.overlay_text()
        conf = gen.conf_text(set())
        for ok, msg in [
            ('&lpuart3 {' in overlay, 'nxp: lpuart3 node'),
            ('serial3 = &lpuart3;' in overlay, 'nxp: serial3 alias'),
            ('pinmux_lpuart3_gen' in overlay, 'nxp: pinctrl group'),
            ('iomuxc_gpio_ad_31_lpuart3_rx' in overlay, 'nxp: rx pad macro'),
            ('bias-pull-up;' in overlay, 'nxp: per-pin bool prop'),
            ('drive-strength = \"high\";' in overlay, 'nxp: string prop'),
            ('dmas = <&edma0 20 13>, <&edma0 21 12>;' in overlay,
             'nxp: dmas channels from directive, sources from SoC header'),
            ('&flexcan1 {' in overlay, 'nxp: flexcan1 node'),
            ('&lpspi1 {' in overlay, 'nxp: lpspi1 node'),
            ('spi-imu0 = &lpspi1;' in overlay, 'nxp: spi-imu0 alias'),
            ('CONFIG_CAN=y' in conf, 'nxp: CAN inference'),
            ('CONFIG_CAN' not in gen.conf_text({'CONFIG_CAN'}),
             'nxp: merge-aware skip'),
            (not gen.errors, 'nxp: no errors: %s' % gen.errors),
        ]:
            if not ok:
                failed.append(msg)

        # ---- STM32 ----
        gen, p = _mkgen(zephyr_hwdef, td, _SELFTEST_STM32, zephyr_base)
        overlay = gen.overlay_text()
        for ok, msg in [
            ('&usart3 {' in overlay, 'stm32: usart3 node'),
            ('pinctrl-0 = <&usart3_tx_pb10 &usart3_rx_pb11>;' in overlay,
             'stm32: direct pin-node refs, no group'),
            ('&usart3_rx_pb11 {' in overlay and 'bias-pull-up;' in overlay,
             'stm32: per-pin prop as override node'),
            ('serial3 = &usart3;' in overlay, 'stm32: serial3 alias'),
            (any('stream' in e or 'not implemented' in e for e in gen.errors),
             'stm32: DMA refused loudly (got: %s)' % gen.errors),
        ]:
            if not ok:
                failed.append(msg)

        # ---- ESP32 ----
        gen, p = _mkgen(zephyr_hwdef, td, _SELFTEST_ESP32, zephyr_base)
        overlay = gen.overlay_text()
        for ok, msg in [
            ('&uart1 {' in overlay, 'esp32: uart1 node'),
            ('pinmux_uart1_gen' in overlay, 'esp32: group node'),
            ('<UART1_TX_GPIO17>' in overlay, 'esp32: numeric macro, no &'),
            ('serial1 = &uart1;' in overlay, 'esp32: serial1 alias'),
            (not gen.errors, 'esp32: no errors: %s' % gen.errors),
        ]:
            if not ok:
                failed.append(msg)

        # ---- inert default (all families) ----
        for mcu in ('MIMXRT1176', 'STM32H743xx', 'ESP32S3'):
            gen, p = _mkgen(zephyr_hwdef, td,
                            'MCU %s\nSERIAL_ORDER OTG1 USART3\nCAN_ORDER 1\n' % mcu,
                            zephyr_base)
            if gen.overlay_text().strip() != (AUTOGEN_HEADER % p).strip():
                failed.append('inert default broken for %s' % mcu)
            if 'CONFIG_CAN' in gen.conf_text(set()):
                failed.append('inert default: CAN inferred without pins (%s)' % mcu)

    if failed:
        for msg in failed:
            print('SELFTEST FAIL: %s' % msg)
        return 1
    print('selftest OK (nxp + stm32 + esp32 + inert defaults)')
    return 0


def main():
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    args = sys.argv[1:]
    zephyr_base = 'modules/zephyr'
    if '--zephyr-base' in args:
        i = args.index('--zephyr-base')
        zephyr_base = args[i + 1]
        del args[i:i + 2]
    if '--selftest' in args:
        return _selftest(zephyr_base)
    if not args:
        print(__doc__)
        return 1
    import zephyr_hwdef
    hwdef = zephyr_hwdef.ZephyrHWDef(args[0])
    gen = ZephyrClassGenerator(hwdef, zephyr_base)
    overlay_out = conf_out = None
    if '--overlay' in args:
        overlay_out = args[args.index('--overlay') + 1]
    if '--conf' in args:
        conf_out = args[args.index('--conf') + 1]
    if overlay_out:
        with open(overlay_out, 'w') as f:
            f.write(gen.overlay_text())
        print('wrote %s' % overlay_out)
    else:
        print(gen.overlay_text())
    if conf_out:
        with open(conf_out, 'w') as f:
            f.write(gen.conf_text())
        print('wrote %s' % conf_out)
    for e in gen.errors:
        print('ERROR: %s' % e, file=sys.stderr)
    return 1 if gen.errors else 0


if __name__ == '__main__':
    sys.exit(main())
