#!/usr/bin/env python
# encoding: utf-8

def build(bld):

    if bld.env.BOARD != 'linux':
        return

    source = bld.path.ant_glob('*.cpp')
    source.append('../../../../libraries/SITL/SIM_Motor.cpp')
    source.append('../../../../libraries/SITL/SIM_Frame.cpp')

    bld.ap_program(
        use='ap',
        program_groups=['examples'],
        source=source,
    )

