#! /usr/bin/env python

"""
Cycles in use should be detected (raise an error before the build starts)
"""

bld.shlib(
	source = 'a.c',
	target = 'CYC_1',
	use    = 'CYC_2'
)

bld.shlib(
	source = 'b.c',
	target = 'CYC_2',
	use    = 'CYC_1'
).post()

