#!/usr/bin/env python
# encoding: utf-8

import ardupilotwaf

def build(bld):
    vehicle = bld.path.name
    ardupilotwaf.vehicle_stlib(
        bld,
        name=vehicle + '_libs',
        vehicle=vehicle,
        libraries=ardupilotwaf.COMMON_VEHICLE_DEPENDENT_LIBRARIES + [
            'AP_ADSB',
            'AC_AttitudeControl',
            'AC_Fence',
            'AC_PID',
            'AC_PrecLand',
            'AC_Sprayer',
            'AC_WPNav',
            'AP_Camera',
            'AP_EPM',
            'AP_Frsky_Telem',
            'AP_IRLock',
            'AP_InertialNav',
            'AP_LandingGear',
            'AP_Menu',
            'AP_Motors',
            'AP_Mount',
            'AP_Parachute',
            'AP_RCMapper',
            'AP_RPM',
            'AP_RSSI',
            'AP_Relay',
            'AP_ServoRelayEvents',
        ],
        use='mavlink',
    )

    ardupilotwaf.program(
        bld,
        program_name='ardusub',
        use=vehicle + '_libs',
    )
