#pragma once

#include "GPIO_Sysfs.h"

enum gpio_navio2 {
    NAVIO2_GPIO_PWM1,
    NAVIO2_GPIO_PWM2,
    NAVIO2_GPIO_PWM3,
    NAVIO2_GPIO_PWM4,
    NAVIO2_GPIO_PWM5,
    NAVIO2_GPIO_PWM6,
    NAVIO2_GPIO_PWM7,
    NAVIO2_GPIO_PWM8,
    NAVIO2_GPIO_PWM9,
    NAVIO2_GPIO_PWM10,
    NAVIO2_GPIO_PWM11,
    NAVIO2_GPIO_PWM12,
    NAVIO2_GPIO_PWM13,
    NAVIO2_GPIO_PWM14,
    NAVIO2_GPIO_IO17,
    NAVIO2_GPIO_IO18,
    NAVIO2_GPIO_RED,
    NAVIO2_GPIO_GREEN,
    NAVIO2_GPIO_BLUE,
    _NAVIO2_GPIO_MAX,
};
