#pragma once

#include "GPIO_Sysfs.h"

enum gpio_pilotpi {
    PILOTPI_GPIO2,
    PILOTPI_GPIO3,
    PILOTPI_GPIO4,
    PILOTPI_GPIO5,
    PILOTPI_GPIO6,
    PILOTPI_GPIO7,
    PILOTPI_GPIO8,
    PILOTPI_GPIO9,
    PILOTPI_GPIO10,
    PILOTPI_GPIO11,
    PILOTPI_GPIO12,
    PILOTPI_GPIO13,
    PILOTPI_GPIO14,
    PILOTPI_GPIO15,
    PILOTPI_GPIO16,
    PILOTPI_GPIO17,
    PILOTPI_GPIO18,
    PILOTPI_GPIO19,
    PILOTPI_GPIO20,
    PILOTPI_GPIO21,
    PILOTPI_GPIO22,
    PILOTPI_GPIO23,
    PILOTPI_GPIO24,
    PILOTPI_GPIO25,
    PILOTPI_GPIO26,
    PILOTPI_GPIO27,
    _PILOTPI_GPIO_MAX,
};
