#pragma once

#include "GPIO_Sysfs.h"

enum gpio_edge {
    EDGE_GPIO_PWM1,
    EDGE_GPIO_PWM2,
    EDGE_GPIO_PWM3,
    EDGE_GPIO_PWM4,
    EDGE_GPIO_PWM5,
    EDGE_GPIO_PWM6,
    EDGE_GPIO_PWM7,
    EDGE_GPIO_PWM8,
    EDGE_GPIO_PWM9,
    EDGE_GPIO_PWM10,
    EDGE_GPIO_PWM11,
    EDGE_GPIO_PWM12,
    EDGE_GPIO_HEAT_ENABLE,
    _EDGE_GPIO_MAX,
};
