#pragma once

#include "GPIO_Sysfs.h"

enum gpio_minnow {
    MINNOW_GPIO_SPI_CS,
    MINNOW_GPIO_SPI_MISO,
    MINNOW_GPIO_SPI_MOSI,
    MINNOW_GPIO_SPI_CLK,
    MINNOW_GPIO_I2C_SCL,
    MINNOW_GPIO_I2C_SDA,
    MINNOW_GPIO_UART2_TXD,
    MINNOW_GPIO_UART2_RXD,
    MINNOW_GPIO_S5_0,
    MINNOW_GPIO_S5_1,
    MINNOW_GPIO_S5_2,
    MINNOW_GPIO_UART1_TXD,
    MINNOW_GPIO_UART1_RXD,
    MINNOW_GPIO_UART1_CTS,
    MINNOW_GPIO_UART1_RTS,
    MINNOW_GPIO_I2S_CLK,
    MINNOW_GPIO_I2S_FRM,
    MINNOW_GPIO_I2S_DO,
    MINNOW_GPIO_I2S_DI,
    MINNOW_GPIO_PWM0,
    MINNOW_GPIO_PWM1,
    MINNOW_GPIO_IBL_8254,
    _MINNOW_GPIO_MAX,
};
