#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_SCHEDULER_ENABLED
#define AP_SCHEDULER_ENABLED 1
#endif

#ifndef AP_SCHEDULER_EXTENDED_TASKINFO_ENABLED
#define AP_SCHEDULER_EXTENDED_TASKINFO_ENABLED 1
#endif

// run FAST_TASKs on every Nth scheduler tick
#ifndef AP_SCHEDULER_FAST_TASK_MODULO
#define AP_SCHEDULER_FAST_TASK_MODULO 1
#endif
