#pragma once

#include <AP_Vehicle/AP_Vehicle_Type.h>
#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_LANDINGGEAR_ENABLED
#define AP_LANDINGGEAR_ENABLED (APM_BUILD_COPTER_OR_HELI || APM_BUILD_TYPE(APM_BUILD_ArduPlane))
#endif

#ifndef AP_TIE_DOWN_CLAMPS_ENABLED
#define AP_TIE_DOWN_CLAMPS_ENABLED (AP_LANDINGGEAR_ENABLED && HAL_PROGRAM_SIZE_LIMIT_KB > 2048)
#endif
