#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_RC_CHANNEL_ENABLED
#define AP_RC_CHANNEL_ENABLED 1
#endif

#ifndef AP_RC_CHANNEL_AUX_FUNCTION_STRINGS_ENABLED
#define AP_RC_CHANNEL_AUX_FUNCTION_STRINGS_ENABLED AP_RC_CHANNEL_ENABLED
#endif  // AP_RC_CHANNEL_AUX_FUNCTION_STRINGS_ENABLED

#ifndef AP_RC_TRANSMITTER_TUNING_ENABLED
#define AP_RC_TRANSMITTER_TUNING_ENABLED AP_RC_CHANNEL_ENABLED
#endif  // AP_RC_CHANNEL_ENABLED
