//
// THIS FILE WAS AUTOMATICALLY GENERATED - DO NOT EDIT
//
/// @file param_table.h

#define PARAM_FIRST_FLOAT 0
enum float_param_t {
    PARAM_HDNG2RLL_P = PARAM_FIRST_FLOAT,
    PARAM_HDNG2RLL_I,
    PARAM_HDNG2RLL_D,
    PARAM_HDNG2RLL_IMAX,
    PARAM_RLL2SRV_P,
    PARAM_RLL2SRV_I,
    PARAM_RLL2SRV_D,
    PARAM_RLL2SRV_IMAX,
    PARAM_PTCH2SRV_P,
    PARAM_PTCH2SRV_I,
    PARAM_PTCH2SRV_D,
    PARAM_PTCH2SRV_IMAX,
    PARAM_ARSPD2PTCH_P,
    PARAM_ARSPD2PTCH_I,
    PARAM_ARSPD2PTCH_D,
    PARAM_ARSPD2PTCH_IMAX,
    PARAM_YW2SRV_P,
    PARAM_YW2SRV_I,
    PARAM_YW2SRV_D,
    PARAM_YW2SRV_IMAX,
    PARAM_ALT2THR_P,
    PARAM_ALT2THR_I,
    PARAM_ALT2THR_D,
    PARAM_ALT2THR_IMAX,
    PARAM_ENRGY2THR_P,
    PARAM_ENRGY2THR_I,
    PARAM_ENRGY2THR_D,
    PARAM_ENRGY2THR_IMAX,
    PARAM_ALT2PTCH_P,
    PARAM_ALT2PTCH_I,
    PARAM_ALT2PTCH_D,
    PARAM_ALT2PTCH_IMAX,
    PARAM_KFF_PTCHCOMP,
    PARAM_KFF_RDDRMIX,
    PARAM_KFF_PTCH2THR,
    PARAM_GND_ALT,
    PARAM_TRIM_AIRSPEED,
    PARAM_XTRACK_ANGLE,
    PARAM_LIM_ROLL,
    PARAM_LIM_PITCH_MAX,
    PARAM_LIM_PITCH_MIN,
    PARAM_ALT_MIX,
    PARAM_ALT_HOLD_HOME,
    PARAM_ARSPD_RATIO,
    PARAM_IMU_OFFSET_0,
    PARAM_IMU_OFFSET_1,
    PARAM_IMU_OFFSET_2,
    PARAM_IMU_OFFSET_3,
    PARAM_IMU_OFFSET_4,
    PARAM_IMU_OFFSET_5,
    PARAM_LAST_FLOAT
};
#define PARAM_FLOAT_COUNT (PARAM_LAST_FLOAT - PARAM_FIRST_FLOAT)

#define PARAM_FIRST_UINT8 PARAM_LAST_FLOAT
enum uint8_param_t {
    PARAM_YAW_MODE = PARAM_FIRST_UINT8,
    PARAM_WP_MODE,
    PARAM_WP_TOTAL,
    PARAM_WP_INDEX,
    PARAM_WP_RADIUS,
    PARAM_LOITER_RADIUS,
    PARAM_ARSPD_FBW_MIN,
    PARAM_ARSPD_FBW_MAX,
    PARAM_THR_MIN,
    PARAM_THR_MAX,
    PARAM_THR_FAILSAFE,
    PARAM_THR_FS_ACTION,
    PARAM_TRIM_THROTTLE,
    PARAM_CONFIG,
    PARAM_TRIM_AUTO,
    PARAM_SWITCH_ENABLE,
    PARAM_FLIGHT_MODE_CH,
    PARAM_FLIGHT_MODE_1,
    PARAM_FLIGHT_MODE_2,
    PARAM_FLIGHT_MODE_3,
    PARAM_FLIGHT_MODE_4,
    PARAM_FLIGHT_MODE_5,
    PARAM_FLIGHT_MODE_6,
    PARAM_LAST_UINT8
};
#define PARAM_UINT8_COUNT (PARAM_LAST_UINT8 - PARAM_FIRST_UINT8)

#define PARAM_FIRST_UINT16 PARAM_LAST_UINT8
enum uint16_param_t {
    PARAM_FIRMWARE_VER = PARAM_FIRST_UINT16,
    PARAM_RADIOTRIM_CH1,
    PARAM_RADIOTRIM_CH2,
    PARAM_RADIOTRIM_CH3,
    PARAM_RADIOTRIM_CH4,
    PARAM_RADIOTRIM_CH5,
    PARAM_RADIOTRIM_CH6,
    PARAM_RADIOTRIM_CH7,
    PARAM_RADIOTRIM_CH8,
    PARAM_RADIOMIN_CH1,
    PARAM_RADIOMIN_CH2,
    PARAM_RADIOMIN_CH3,
    PARAM_RADIOMIN_CH4,
    PARAM_RADIOMIN_CH5,
    PARAM_RADIOMIN_CH6,
    PARAM_RADIOMIN_CH7,
    PARAM_RADIOMIN_CH8,
    PARAM_RADIOMAX_CH1,
    PARAM_RADIOMAX_CH2,
    PARAM_RADIOMAX_CH3,
    PARAM_RADIOMAX_CH4,
    PARAM_RADIOMAX_CH5,
    PARAM_RADIOMAX_CH6,
    PARAM_RADIOMAX_CH7,
    PARAM_RADIOMAX_CH8,
    PARAM_LOG_BITMASK,
    PARAM_TRIM_ELEVON,
    PARAM_THR_FS_VALUE,
    PARAM_LAST_UINT16
};
#define PARAM_UINT16_COUNT (PARAM_LAST_UINT16 - PARAM_FIRST_UINT16)

#define PARAM_FIRST_INT16 PARAM_LAST_UINT16
enum int16_param_t {
    PARAM_XTRACK_GAIN = PARAM_FIRST_INT16,
    PARAM_GND_TEMP,
    PARAM_AP_OFFSET,
    PARAM_TRIM_PITCH,
    PARAM_LAST_INT16
};
#define PARAM_INT16_COUNT (PARAM_LAST_INT16 - PARAM_FIRST_INT16)

#define PARAM_FIRST_UINT32 PARAM_LAST_INT16
enum uint32_param_t {
    PARAM_GND_ABS_PRESS = PARAM_FIRST_UINT32,
    PARAM_LAST_UINT32
};
#define PARAM_UINT32_COUNT (PARAM_LAST_UINT32 - PARAM_FIRST_UINT32)

#define PARAM_COUNT PARAM_LAST_UINT32
