#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := arduplane
BUILD_DIR_BASE = ../../../build/esp32/idf-plane

include $(IDF_PATH)/make/project.mk

showinc:
	echo INCLUDES: $(COMPONENT_INCLUDES)
