
# This service requests the vehicle to switch its drive/flight mode

# mode : Set the value to the drive/flight mode to be used
# Copter : https://mavlink.io/en/messages/ardupilotmega.html#COPTER_MODE
# Rover  : https://mavlink.io/en/messages/ardupilotmega.html#ROVER_MODE
# Plane  : https://mavlink.io/en/messages/ardupilotmega.html#PLANE_MODE

uint8 mode
---
# status    : True if the request for mode switch was successful, False otherwise
# curr_mode : Returns the code for the current drive/flight mode , after the processing the request

bool status
uint8 curr_mode
