#!/usr/bin/env python
# encoding: utf-8

def build(bld):
    bld.ap_example(
        use=['ap','JEDEC_libs'],
    )
    bld.ap_stlib(name= 'JEDEC_libs',
                ap_vehicle='AP_Periph',
                ap_libraries= ['AP_FlashIface'])
