#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_FILTER_ENABLED
#define AP_FILTER_ENABLED HAL_PROGRAM_SIZE_LIMIT_KB > 1024
#endif

#if AP_FILTER_ENABLED
 #ifndef AP_FILTER_NUM_FILTERS
 #if HAL_PROGRAM_SIZE_LIMIT_KB > 1024
  #define AP_FILTER_NUM_FILTERS 8
 #else
  #define AP_FILTER_NUM_FILTERS 4
 #endif // HAL_PROGRAM_SIZE_LIMIT_KB
 #endif // AP_FILTER_NUM_FILTERS
#endif // AP_FILTER_ENABLED
