#! /usr/bin/env python
# encoding: utf-8

bld.program(
	features = 'test',
	source   = 'AccumulatorTest.cpp',
	target   = 'unit_test_program',
	use      = 'unittestmain useless GTEST',
	ut_cwd   = bld.path.abspath(),
)

