#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_RADIO_ENABLED
#define AP_RADIO_ENABLED 0
#endif

#ifndef AP_RADIO_BACKEND_DEFAULT_ENABLED
#define AP_RADIO_BACKEND_DEFAULT_ENABLED AP_RADIO_ENABLED
#endif

#ifndef AP_RADIO_CC2500_ENABLED
#define AP_RADIO_CC2500_ENABLED AP_RADIO_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AP_RADIO_CYRF6936_ENABLED
#define AP_RADIO_CYRF6936_ENABLED AP_RADIO_BACKEND_DEFAULT_ENABLED
#endif

#ifndef AP_RADIO_BK2425_ENABLED
#define AP_RADIO_BK2425_ENABLED AP_RADIO_BACKEND_DEFAULT_ENABLED
#endif

// tries both CC2500 and BK2425 drivers:
#ifndef AP_RADIO_AUTO_ENABLED
#define AP_RADIO_AUTO_ENABLED 0
#endif  // AP_RADIO_AUTO_ENABLED
