#pragma once

//#error minimise this

/*
 * This (optional) header file disables all discovered AP_*_ENABLED feature flags by default.
 * Generated as a strict deny-by-default baseline for minimal bringup.
 * and it makes it way easier to build a target like tool/CPUInfo with way less libraries.
 */

#ifdef HAL_GCS_ENABLED
#undef HAL_GCS_ENABLED
#endif
#define HAL_GCS_ENABLED 0

#ifdef HAL_LOGGING_ENABLED
#undef HAL_LOGGING_ENABLED
#endif
#define HAL_LOGGING_ENABLED 0

// doesnt start with AP_ , but it realy should be treated teh same as the rest.
#ifndef HAL_VISUALODOM_ENABLED
#define HAL_VISUALODOM_ENABLED 0
#endif
// HAL_GENERATOR_ENABLED
#ifndef HAL_GENERATOR_ENABLED
#define HAL_GENERATOR_ENABLED 0
#endif
//HAL_TORQEEDO_ENABLED
#ifndef HAL_TORQEEDO_ENABLED
#define HAL_TORQEEDO_ENABLED 0
#endif


#ifndef AP_ADSB_AVOIDANCE_ENABLED
#define AP_ADSB_AVOIDANCE_ENABLED 0
#endif

#ifndef AP_ADVANCEDFAILSAFE_ENABLED
#define AP_ADVANCEDFAILSAFE_ENABLED 0
#endif

#ifndef AP_AHRS_BACKEND_DEFAULT_ENABLED
#define AP_AHRS_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_AHRS_DCM_ENABLED
#define AP_AHRS_DCM_ENABLED 0
#endif

#ifndef AP_AHRS_ENABLED
#define AP_AHRS_ENABLED 0
#endif

#ifndef AP_AHRS_EXTERNAL_ENABLED
#define AP_AHRS_EXTERNAL_ENABLED 0
#endif

#ifndef AP_AHRS_EXTERNAL_WIND_ESTIMATE_ENABLED
#define AP_AHRS_EXTERNAL_WIND_ESTIMATE_ENABLED 0
#endif

#ifndef AP_AHRS_POSITION_RESET_ENABLED
#define AP_AHRS_POSITION_RESET_ENABLED 0
#endif

#ifndef AP_AHRS_SIM_ENABLED
#define AP_AHRS_SIM_ENABLED 0
#endif

#ifndef AP_AIRSPEED_ANALOG_ENABLED
#define AP_AIRSPEED_ANALOG_ENABLED 0
#endif

#ifndef AP_AIRSPEED_ASP5033_ENABLED
#define AP_AIRSPEED_ASP5033_ENABLED 0
#endif

#ifndef AP_AIRSPEED_AUAV_ENABLED
#define AP_AIRSPEED_AUAV_ENABLED 0
#endif

#ifndef AP_AIRSPEED_BACKEND_DEFAULT_ENABLED
#define AP_AIRSPEED_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_AIRSPEED_BACKEND_ENABLED
#define AP_AIRSPEED_BACKEND_ENABLED 0
#endif

#ifndef AP_AIRSPEED_DLVR_ENABLED
#define AP_AIRSPEED_DLVR_ENABLED 0
#endif

#ifndef AP_AIRSPEED_DRONECAN_ENABLED
#define AP_AIRSPEED_DRONECAN_ENABLED 0
#endif

#ifndef AP_AIRSPEED_DUMMY_METHODS_ENABLED
#define AP_AIRSPEED_DUMMY_METHODS_ENABLED 0
#endif

#ifndef AP_AIRSPEED_ENABLED
#define AP_AIRSPEED_ENABLED 0
#endif

#ifndef AP_AIRSPEED_EXTERNAL_ENABLED
#define AP_AIRSPEED_EXTERNAL_ENABLED 0
#endif

#ifndef AP_AIRSPEED_MS4525_ENABLED
#define AP_AIRSPEED_MS4525_ENABLED 0
#endif

#ifndef AP_AIRSPEED_MS5525_ENABLED
#define AP_AIRSPEED_MS5525_ENABLED 0
#endif

#ifndef AP_AIRSPEED_MSP_ENABLED
#define AP_AIRSPEED_MSP_ENABLED 0
#endif

#ifndef AP_AIRSPEED_NMEA_ENABLED
#define AP_AIRSPEED_NMEA_ENABLED 0
#endif

#ifndef AP_AIRSPEED_SDP3X_ENABLED
#define AP_AIRSPEED_SDP3X_ENABLED 0
#endif

#ifndef AP_AIRSPEED_SITL_ENABLED
#define AP_AIRSPEED_SITL_ENABLED 0
#endif

#ifndef AP_AIS_DUMMY_METHODS_ENABLED
#define AP_AIS_DUMMY_METHODS_ENABLED 0
#endif

#ifndef AP_AIS_ENABLED
#define AP_AIS_ENABLED 0
#endif

#ifndef AP_ARMING_AUX_AUTH_ENABLED
#define AP_ARMING_AUX_AUTH_ENABLED 0
#endif

#ifndef AP_ARMING_CRASHDUMP_ACK_ENABLED
#define AP_ARMING_CRASHDUMP_ACK_ENABLED 0
#endif

#ifndef AP_ARMING_ENABLED
#define AP_ARMING_ENABLED 1
#endif

#ifndef AP_ARMING_NEED_LOC_PARAMETER_ENABLED
#define AP_ARMING_NEED_LOC_PARAMETER_ENABLED 0
#endif

#ifndef AP_AVOIDANCE_ALTHOLD_ENABLED
#define AP_AVOIDANCE_ALTHOLD_ENABLED 0
#endif

#ifndef AP_AVOIDANCE_ENABLED
#define AP_AVOIDANCE_ENABLED 0
#endif

#ifndef AP_BARO_1976_STANDARD_ATMOSPHERE_ENABLED
#define AP_BARO_1976_STANDARD_ATMOSPHERE_ENABLED 0
#endif

#ifndef AP_BARO_AUAV_ENABLED
#define AP_BARO_AUAV_ENABLED 0
#endif

#ifndef AP_BARO_BACKEND_DEFAULT_ENABLED
#define AP_BARO_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_BARO_BMP085_ENABLED
#define AP_BARO_BMP085_ENABLED 0
#endif

#ifndef AP_BARO_BMP280_ENABLED
#define AP_BARO_BMP280_ENABLED 0
#endif

#ifndef AP_BARO_BMP388_ENABLED
#define AP_BARO_BMP388_ENABLED 0
#endif

#ifndef AP_BARO_BMP581_ENABLED
#define AP_BARO_BMP581_ENABLED 0
#endif

#ifndef AP_BARO_DPS280_ENABLED
#define AP_BARO_DPS280_ENABLED 0
#endif

#ifndef AP_BARO_DRONECAN_ENABLED
#define AP_BARO_DRONECAN_ENABLED 0
#endif

#ifndef AP_BARO_DUMMY_ENABLED
#define AP_BARO_DUMMY_ENABLED 0
#endif

#ifndef AP_BARO_ENABLED
#define AP_BARO_ENABLED 0
#endif

#ifndef AP_BARO_EXTERNALAHRS_ENABLED
#define AP_BARO_EXTERNALAHRS_ENABLED 0
#endif

#ifndef AP_BARO_FBM320_ENABLED
#define AP_BARO_FBM320_ENABLED 0
#endif

#ifndef AP_BARO_ICM20789_ENABLED
#define AP_BARO_ICM20789_ENABLED 0
#endif

#ifndef AP_BARO_ICP101XX_ENABLED
#define AP_BARO_ICP101XX_ENABLED 0
#endif

#ifndef AP_BARO_ICP201XX_ENABLED
#define AP_BARO_ICP201XX_ENABLED 0
#endif

#ifndef AP_BARO_KELLERLD_ENABLED
#define AP_BARO_KELLERLD_ENABLED 0
#endif

#ifndef AP_BARO_LPS2XH_ENABLED
#define AP_BARO_LPS2XH_ENABLED 0
#endif

#ifndef AP_BARO_MS5607_ENABLED
#define AP_BARO_MS5607_ENABLED 0
#endif

#ifndef AP_BARO_MS5611_ENABLED
#define AP_BARO_MS5611_ENABLED 0
#endif

#ifndef AP_BARO_MS5637_ENABLED
#define AP_BARO_MS5637_ENABLED 0
#endif

#ifndef AP_BARO_MS56XX_ENABLED
#define AP_BARO_MS56XX_ENABLED 0
#endif

#ifndef AP_BARO_MS5837_ENABLED
#define AP_BARO_MS5837_ENABLED 0
#endif

#ifndef AP_BARO_MSP_ENABLED
#define AP_BARO_MSP_ENABLED 0
#endif

#ifndef AP_BARO_PROBE_EXT_PARAMETER_ENABLED
#define AP_BARO_PROBE_EXT_PARAMETER_ENABLED 0
#endif

#ifndef AP_BARO_SPL06_ENABLED
#define AP_BARO_SPL06_ENABLED 0
#endif

#ifndef AP_BARO_THST_COMP_ENABLED
#define AP_BARO_THST_COMP_ENABLED 0
#endif

#ifndef AP_BATTERY_AD7091R5_ENABLED
#define AP_BATTERY_AD7091R5_ENABLED 0
#endif

#ifndef AP_BATTERY_ANALOG_ENABLED
#define AP_BATTERY_ANALOG_ENABLED 0
#endif

#ifndef AP_BATTERY_BACKEND_DEFAULT_ENABLED
#define AP_BATTERY_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_BATTERY_BEBOP_ENABLED
#define AP_BATTERY_BEBOP_ENABLED 0
#endif

#ifndef AP_BATTERY_EFI_ENABLED
#define AP_BATTERY_EFI_ENABLED 0
#endif

#ifndef AP_BATTERY_ENABLED
#define AP_BATTERY_ENABLED 0
#endif

#ifndef AP_BATTERY_ESC_ENABLED
#define AP_BATTERY_ESC_ENABLED 0
#endif

#ifndef AP_BATTERY_ESC_TELEM_OUTBOUND_ENABLED
#define AP_BATTERY_ESC_TELEM_OUTBOUND_ENABLED 0
#endif

#ifndef AP_BATTERY_FUELFLOW_ENABLED
#define AP_BATTERY_FUELFLOW_ENABLED 0
#endif

#ifndef AP_BATTERY_FUELLEVEL_ANALOG_ENABLED
#define AP_BATTERY_FUELLEVEL_ANALOG_ENABLED 0
#endif

#ifndef AP_BATTERY_FUELLEVEL_PWM_ENABLED
#define AP_BATTERY_FUELLEVEL_PWM_ENABLED 0
#endif

#ifndef AP_BATTERY_GENERATOR_ENABLED
#define AP_BATTERY_GENERATOR_ENABLED 0
#endif

#ifndef AP_BATTERY_INA239_ENABLED
#define AP_BATTERY_INA239_ENABLED 0
#endif

#ifndef AP_BATTERY_INA2XX_ENABLED
#define AP_BATTERY_INA2XX_ENABLED 0
#endif

#ifndef AP_BATTERY_INA3221_ENABLED
#define AP_BATTERY_INA3221_ENABLED 0
#endif

#ifndef AP_BATTERY_LTC2946_ENABLED
#define AP_BATTERY_LTC2946_ENABLED 0
#endif

#ifndef AP_BATTERY_OPTIONS_PARAM_ENABLED
#define AP_BATTERY_OPTIONS_PARAM_ENABLED 0
#endif

#ifndef AP_BATTERY_SCRIPTING_ENABLED
#define AP_BATTERY_SCRIPTING_ENABLED 0
#endif

#ifndef AP_BATTERY_SMBUS_ENABLED
#define AP_BATTERY_SMBUS_ENABLED 0
#endif

#ifndef AP_BATTERY_SMBUS_GENERIC_ENABLED
#define AP_BATTERY_SMBUS_GENERIC_ENABLED 0
#endif

#ifndef AP_BATTERY_SMBUS_MAXELL_ENABLED
#define AP_BATTERY_SMBUS_MAXELL_ENABLED 0
#endif

#ifndef AP_BATTERY_SMBUS_NEODESIGN_ENABLED
#define AP_BATTERY_SMBUS_NEODESIGN_ENABLED 0
#endif

#ifndef AP_BATTERY_SMBUS_ROTOYE_ENABLED
#define AP_BATTERY_SMBUS_ROTOYE_ENABLED 0
#endif

#ifndef AP_BATTERY_SMBUS_SOLO_ENABLED
#define AP_BATTERY_SMBUS_SOLO_ENABLED 0
#endif

#ifndef AP_BATTERY_SMBUS_SUI_ENABLED
#define AP_BATTERY_SMBUS_SUI_ENABLED 0
#endif

#ifndef AP_BATTERY_SUM_ENABLED
#define AP_BATTERY_SUM_ENABLED 0
#endif

#ifndef AP_BATTERY_SYNTHETIC_CURRENT_ENABLED
#define AP_BATTERY_SYNTHETIC_CURRENT_ENABLED 0
#endif

#ifndef AP_BATTERY_TIBQ76952_ENABLED
#define AP_BATTERY_TIBQ76952_ENABLED 0
#endif

#ifndef AP_BATTERY_TORQEEDO_ENABLED
#define AP_BATTERY_TORQEEDO_ENABLED 0
#endif

#ifndef AP_BATTERY_UAVCAN_BATTERYINFO_ENABLED
#define AP_BATTERY_UAVCAN_BATTERYINFO_ENABLED 0
#endif

#ifndef AP_BATTERY_WATT_MAX_ENABLED
#define AP_BATTERY_WATT_MAX_ENABLED 0
#endif

#ifndef AP_BEACON_BACKEND_DEFAULT_ENABLED
#define AP_BEACON_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_BEACON_ENABLED
#define AP_BEACON_ENABLED 0
#endif

#ifndef AP_BEACON_MARVELMIND_ENABLED
#define AP_BEACON_MARVELMIND_ENABLED 0
#endif

#ifndef AP_BEACON_NOOPLOOP_ENABLED
#define AP_BEACON_NOOPLOOP_ENABLED 0
#endif

#ifndef AP_BEACON_POZYX_ENABLED
#define AP_BEACON_POZYX_ENABLED 0
#endif

#ifndef AP_BEACON_SITL_ENABLED
#define AP_BEACON_SITL_ENABLED 0
#endif

#ifndef AP_BOARDCONFIG_MCU_MEMPROTECT_ENABLED
#define AP_BOARDCONFIG_MCU_MEMPROTECT_ENABLED 0
#endif

#ifndef AP_BOOTLOADER_FLASH_FROM_SD_ENABLED
#define AP_BOOTLOADER_FLASH_FROM_SD_ENABLED 0
#endif

#ifndef AP_BOOTLOADER_FLASHING_ENABLED
#define AP_BOOTLOADER_FLASHING_ENABLED 0
#endif

#ifndef AP_BOOTLOADER_NETWORK_ENABLED
#define AP_BOOTLOADER_NETWORK_ENABLED 0
#endif

#ifndef AP_CAMERA_BACKEND_DEFAULT_ENABLED
#define AP_CAMERA_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_CAMERA_ENABLED
#define AP_CAMERA_ENABLED 0
#endif

#ifndef AP_CAMERA_INFO_FROM_SCRIPT_ENABLED
#define AP_CAMERA_INFO_FROM_SCRIPT_ENABLED 0
#endif

#ifndef AP_CAMERA_MAVLINKCAMV2_ENABLED
#define AP_CAMERA_MAVLINKCAMV2_ENABLED 0
#endif

#ifndef AP_CAMERA_MAVLINK_ENABLED
#define AP_CAMERA_MAVLINK_ENABLED 0
#endif

#ifndef AP_CAMERA_MOUNT_ENABLED
#define AP_CAMERA_MOUNT_ENABLED 0
#endif

#ifndef AP_CAMERA_RELAY_ENABLED
#define AP_CAMERA_RELAY_ENABLED 0
#endif

#ifndef AP_CAMERA_RUNCAM_ENABLED
#define AP_CAMERA_RUNCAM_ENABLED 0
#endif

#ifndef AP_CAMERA_SCRIPTING_ENABLED
#define AP_CAMERA_SCRIPTING_ENABLED 0
#endif

#ifndef AP_CAMERA_SEND_FOV_STATUS_ENABLED
#define AP_CAMERA_SEND_FOV_STATUS_ENABLED 0
#endif

#ifndef AP_CAMERA_SEND_THERMAL_RANGE_ENABLED
#define AP_CAMERA_SEND_THERMAL_RANGE_ENABLED 0
#endif

#ifndef AP_CAMERA_SERVO_ENABLED
#define AP_CAMERA_SERVO_ENABLED 0
#endif

#ifndef AP_CAMERA_SET_CAMERA_SOURCE_ENABLED
#define AP_CAMERA_SET_CAMERA_SOURCE_ENABLED 0
#endif

#ifndef AP_CAMERA_SOLOGIMBAL_ENABLED
#define AP_CAMERA_SOLOGIMBAL_ENABLED 0
#endif

#ifndef AP_CAN_LOGGING_ENABLED
#define AP_CAN_LOGGING_ENABLED 0
#endif

#ifndef AP_CAN_SCLAN_ENABLED
#define AP_CAN_SCLAN_ENABLED 0
#endif

#ifndef AP_CAN_SLCAN_ENABLED
#define AP_CAN_SLCAN_ENABLED 0
#endif

#ifndef AP_CHECK_FIRMWARE_ENABLED
#define AP_CHECK_FIRMWARE_ENABLED 0
#endif

#ifndef AP_COMPASS_AK09916_ENABLED
#define AP_COMPASS_AK09916_ENABLED 0
#endif

#ifndef AP_COMPASS_AK8963_ENABLED
#define AP_COMPASS_AK8963_ENABLED 0
#endif

#ifndef AP_COMPASS_BACKEND_DEFAULT_ENABLED
#define AP_COMPASS_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_COMPASS_BMM150_ENABLED
#define AP_COMPASS_BMM150_ENABLED 0
#endif

#ifndef AP_COMPASS_BMM350_ENABLED
#define AP_COMPASS_BMM350_ENABLED 0
#endif

#ifndef AP_COMPASS_CALIBRATION_FIXED_YAW_ENABLED
#define AP_COMPASS_CALIBRATION_FIXED_YAW_ENABLED 0
#endif

#ifndef AP_COMPASS_DIAGONALS_ENABLED
#define AP_COMPASS_DIAGONALS_ENABLED 0
#endif

#ifndef AP_COMPASS_DRONECAN_ENABLED
#define AP_COMPASS_DRONECAN_ENABLED 0
#endif

#ifndef AP_COMPASS_DRONECAN_HIRES_ENABLED
#define AP_COMPASS_DRONECAN_HIRES_ENABLED 0
#endif

#ifndef AP_COMPASS_ENABLED
#define AP_COMPASS_ENABLED 0
#endif

#ifndef AP_COMPASS_EXTERNALAHRS_ENABLED
#define AP_COMPASS_EXTERNALAHRS_ENABLED 0
#endif

#ifndef AP_COMPASS_HMC5843_ENABLED
#define AP_COMPASS_HMC5843_ENABLED 0
#endif

#ifndef AP_COMPASS_HMC5843_INTERNAL_BUS_PROBING_ENABLED
#define AP_COMPASS_HMC5843_INTERNAL_BUS_PROBING_ENABLED 0
#endif

#ifndef AP_COMPASS_I2C_BACKEND_DEFAULT_ENABLED
#define AP_COMPASS_I2C_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_COMPASS_ICM20948_ENABLED
#define AP_COMPASS_ICM20948_ENABLED 0
#endif

#ifndef AP_COMPASS_IIS2MDC_ENABLED
#define AP_COMPASS_IIS2MDC_ENABLED 0
#endif

#ifndef AP_COMPASS_INTERNAL_BUS_PROBING_ENABLED
#define AP_COMPASS_INTERNAL_BUS_PROBING_ENABLED 0
#endif

#ifndef AP_COMPASS_IST8308_ENABLED
#define AP_COMPASS_IST8308_ENABLED 0
#endif

#ifndef AP_COMPASS_IST8310_ENABLED
#define AP_COMPASS_IST8310_ENABLED 0
#endif

#ifndef AP_COMPASS_IST8310_EXTERNAL_BUS_PROBING_ENABLED
#define AP_COMPASS_IST8310_EXTERNAL_BUS_PROBING_ENABLED 0
#endif

#ifndef AP_COMPASS_IST8310_INTERNAL_BUS_PROBING_ENABLED
#define AP_COMPASS_IST8310_INTERNAL_BUS_PROBING_ENABLED 0
#endif

#ifndef AP_COMPASS_KMC5843_INTERNAL_BUS_PROBING_ENABLED
#define AP_COMPASS_KMC5843_INTERNAL_BUS_PROBING_ENABLED 0
#endif

#ifndef AP_COMPASS_LIS2MDL_ENABLED
#define AP_COMPASS_LIS2MDL_ENABLED 0
#endif

#ifndef AP_COMPASS_LIS2MDL_EXTERNAL_BUS_PROBING_ENABLED
#define AP_COMPASS_LIS2MDL_EXTERNAL_BUS_PROBING_ENABLED 0
#endif

#ifndef AP_COMPASS_LIS3MDL_ENABLED
#define AP_COMPASS_LIS3MDL_ENABLED 0
#endif

#ifndef AP_COMPASS_LSM303D_ENABLED
#define AP_COMPASS_LSM303D_ENABLED 0
#endif

#ifndef AP_COMPASS_LSM9DS1_ENABLED
#define AP_COMPASS_LSM9DS1_ENABLED 0
#endif

#ifndef AP_COMPASS_MAG3110_ENABLED
#define AP_COMPASS_MAG3110_ENABLED 0
#endif

#ifndef AP_COMPASS_MMC3416_ENABLED
#define AP_COMPASS_MMC3416_ENABLED 0
#endif

#ifndef AP_COMPASS_MMC5XX3_ENABLED
#define AP_COMPASS_MMC5XX3_ENABLED 0
#endif

#ifndef AP_COMPASS_MSP_ENABLED
#define AP_COMPASS_MSP_ENABLED 0
#endif

#ifndef AP_COMPASS_PROBING_ENABLED
#define AP_COMPASS_PROBING_ENABLED 0
#endif

#ifndef AP_COMPASS_QMC5883L_ENABLED
#define AP_COMPASS_QMC5883L_ENABLED 0
#endif

#ifndef AP_COMPASS_QMC5883P_ENABLED
#define AP_COMPASS_QMC5883P_ENABLED 0
#endif

#ifndef AP_COMPASS_QMC5883P_INTERNAL_BUS_PROBING_ENABLED
#define AP_COMPASS_QMC5883P_INTERNAL_BUS_PROBING_ENABLED 0
#endif

#ifndef AP_COMPASS_RM3100_ENABLED
#define AP_COMPASS_RM3100_ENABLED 0
#endif

#ifndef AP_COMPASS_SITL_ENABLED
#define AP_COMPASS_SITL_ENABLED 0
#endif

#ifndef AP_COPTER_ADVANCED_FAILSAFE_ENABLED
#define AP_COPTER_ADVANCED_FAILSAFE_ENABLED 0
#endif

#ifndef AP_COPTER_AHRS_AUTO_TRIM_ENABLED
#define AP_COPTER_AHRS_AUTO_TRIM_ENABLED 0
#endif

#ifndef AP_CPU_IDLE_STATS_ENABLED
#define AP_CPU_IDLE_STATS_ENABLED 0
#endif

#ifndef AP_CRASHDUMP_ENABLED
#define AP_CRASHDUMP_ENABLED 0
#endif

#ifndef AP_CRSF_ENABLED
#define AP_CRSF_ENABLED 0
#endif

#ifndef AP_CRSF_SCRIPTING_ENABLED
#define AP_CRSF_SCRIPTING_ENABLED 0
#endif

#ifndef AP_CUSTOMCONTROL_BACKEND_DEFAULT_ENABLED
#define AP_CUSTOMCONTROL_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_CUSTOMCONTROL_EMPTY_ENABLED
#define AP_CUSTOMCONTROL_EMPTY_ENABLED 0
#endif

#ifndef AP_CUSTOMCONTROL_ENABLED
#define AP_CUSTOMCONTROL_ENABLED 0
#endif

#ifndef AP_CUSTOMCONTROL_PID_ENABLED
#define AP_CUSTOMCONTROL_PID_ENABLED 0
#endif

#ifndef AP_CUSTOMCONTROL_XYZ_ENABLED
#define AP_CUSTOMCONTROL_XYZ_ENABLED 0
#endif

#ifndef AP_CUSTOMROTATIONS_ENABLED
#define AP_CUSTOMROTATIONS_ENABLED 0
#endif

#ifndef AP_DAC_BACKEND_DEFAULT_ENABLED
#define AP_DAC_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_DAC_ENABLED
#define AP_DAC_ENABLED 0
#endif

#ifndef AP_DAC_MCP40D1X_ENABLED
#define AP_DAC_MCP40D1X_ENABLED 0
#endif

#ifndef AP_DAC_TIX3204_ENABLED
#define AP_DAC_TIX3204_ENABLED 0
#endif

#ifndef AP_DDS_AIRSPEED_PUB_ENABLED
#define AP_DDS_AIRSPEED_PUB_ENABLED 0
#endif

#ifndef AP_DDS_ARM_CHECK_SERVER_ENABLED
#define AP_DDS_ARM_CHECK_SERVER_ENABLED 0
#endif

#ifndef AP_DDS_ARM_SERVER_ENABLED
#define AP_DDS_ARM_SERVER_ENABLED 0
#endif

#ifndef AP_DDS_BATTERY_STATE_PUB_ENABLED
#define AP_DDS_BATTERY_STATE_PUB_ENABLED 0
#endif

#ifndef AP_DDS_CLOCK_PUB_ENABLED
#define AP_DDS_CLOCK_PUB_ENABLED 0
#endif

#ifndef AP_DDS_DYNAMIC_TF_SUB_ENABLED
#define AP_DDS_DYNAMIC_TF_SUB_ENABLED 0
#endif

#ifndef AP_DDS_ENABLED
#define AP_DDS_ENABLED 0
#endif

#ifndef AP_DDS_EXPERIMENTAL_ENABLED
#define AP_DDS_EXPERIMENTAL_ENABLED 0
#endif

#ifndef AP_DDS_GEOPOSE_PUB_ENABLED
#define AP_DDS_GEOPOSE_PUB_ENABLED 0
#endif

#ifndef AP_DDS_GLOBAL_POS_CTRL_ENABLED
#define AP_DDS_GLOBAL_POS_CTRL_ENABLED 0
#endif

#ifndef AP_DDS_GOAL_PUB_ENABLED
#define AP_DDS_GOAL_PUB_ENABLED 0
#endif

#ifndef AP_DDS_GPS_GLOBAL_ORIGIN_PUB_ENABLED
#define AP_DDS_GPS_GLOBAL_ORIGIN_PUB_ENABLED 0
#endif

#ifndef AP_DDS_IMU_PUB_ENABLED
#define AP_DDS_IMU_PUB_ENABLED 0
#endif

#ifndef AP_DDS_JOY_SUB_ENABLED
#define AP_DDS_JOY_SUB_ENABLED 0
#endif

#ifndef AP_DDS_LOCAL_POSE_PUB_ENABLED
#define AP_DDS_LOCAL_POSE_PUB_ENABLED 0
#endif

#ifndef AP_DDS_LOCAL_VEL_PUB_ENABLED
#define AP_DDS_LOCAL_VEL_PUB_ENABLED 0
#endif

#ifndef AP_DDS_MODE_SWITCH_SERVER_ENABLED
#define AP_DDS_MODE_SWITCH_SERVER_ENABLED 0
#endif

#ifndef AP_DDS_NAVSATFIX_PUB_ENABLED
#define AP_DDS_NAVSATFIX_PUB_ENABLED 0
#endif

#ifndef AP_DDS_PARAMETER_SERVER_ENABLED
#define AP_DDS_PARAMETER_SERVER_ENABLED 0
#endif

#ifndef AP_DDS_RC_PUB_ENABLED
#define AP_DDS_RC_PUB_ENABLED 0
#endif

#ifndef AP_DDS_STATIC_TF_PUB_ENABLED
#define AP_DDS_STATIC_TF_PUB_ENABLED 0
#endif

#ifndef AP_DDS_STATUS_PUB_ENABLED
#define AP_DDS_STATUS_PUB_ENABLED 0
#endif

#ifndef AP_DDS_TIME_PUB_ENABLED
#define AP_DDS_TIME_PUB_ENABLED 0
#endif

#ifndef AP_DDS_UDP_ENABLED
#define AP_DDS_UDP_ENABLED 0
#endif

#ifndef AP_DDS_VEL_CTRL_ENABLED
#define AP_DDS_VEL_CTRL_ENABLED 0
#endif

#ifndef AP_DDS_VISUALODOM_ENABLED
#define AP_DDS_VISUALODOM_ENABLED 0
#endif

#ifndef AP_DDS_VTOL_TAKEOFF_SERVER_ENABLED
#define AP_DDS_VTOL_TAKEOFF_SERVER_ENABLED 0
#endif

#ifndef AP_DEVO_TELEM_ENABLED
#define AP_DEVO_TELEM_ENABLED 0
#endif

#ifndef AP_DRONECAN_SERIAL_ENABLED
#define AP_DRONECAN_SERIAL_ENABLED 0
#endif

#ifndef AP_DRONECAN_VOLZ_FEEDBACK_ENABLED
#define AP_DRONECAN_VOLZ_FEEDBACK_ENABLED 0
#endif

#ifndef AP_EFI_BACKEND_DEFAULT_ENABLED
#define AP_EFI_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_EFI_CURRAWONG_ECU_ENABLED
#define AP_EFI_CURRAWONG_ECU_ENABLED 0
#endif

#ifndef AP_EFI_DRONECAN_ENABLED
#define AP_EFI_DRONECAN_ENABLED 0
#endif

#ifndef AP_EFI_LOWEHEISER_ENABLED
#define AP_EFI_LOWEHEISER_ENABLED 0
#endif

#ifndef AP_EFI_MAV_ENABLED
#define AP_EFI_MAV_ENABLED 0
#endif

#ifndef AP_EFI_NWPWU_ENABLED
#define AP_EFI_NWPWU_ENABLED 0
#endif

#ifndef AP_EFI_SCRIPTING_ENABLED
#define AP_EFI_SCRIPTING_ENABLED 0
#endif

#ifndef AP_EFI_SERIAL_HIRTH_ENABLED
#define AP_EFI_SERIAL_HIRTH_ENABLED 0
#endif

#ifndef AP_EFI_SERIAL_LUTAN_ENABLED
#define AP_EFI_SERIAL_LUTAN_ENABLED 0
#endif

#ifndef AP_EFI_SERIAL_MS_ENABLED
#define AP_EFI_SERIAL_MS_ENABLED 0
#endif

#ifndef AP_EFI_THROTTLE_LINEARISATION_ENABLED
#define AP_EFI_THROTTLE_LINEARISATION_ENABLED 0
#endif

#ifndef AP_EXTENDED_DSHOT_TELEM_V2_ENABLED
#define AP_EXTENDED_DSHOT_TELEM_V2_ENABLED 0
#endif

#ifndef AP_EXTENDED_ESC_TELEM_ENABLED
#define AP_EXTENDED_ESC_TELEM_ENABLED 0
#endif

#ifndef AP_EXTERNAL_AHRS_BACKEND_DEFAULT_ENABLED
#define AP_EXTERNAL_AHRS_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_EXTERNAL_AHRS_ENABLED
#define AP_EXTERNAL_AHRS_ENABLED 0
#endif

#ifndef AP_EXTERNAL_AHRS_INERTIALLABS_ENABLED
#define AP_EXTERNAL_AHRS_INERTIALLABS_ENABLED 0
#endif

#ifndef AP_EXTERNAL_AHRS_MICROSTRAIN5_ENABLED
#define AP_EXTERNAL_AHRS_MICROSTRAIN5_ENABLED 0
#endif

#ifndef AP_EXTERNAL_AHRS_MICROSTRAIN7_ENABLED
#define AP_EXTERNAL_AHRS_MICROSTRAIN7_ENABLED 0
#endif

#ifndef AP_EXTERNAL_AHRS_SBG_ENABLED
#define AP_EXTERNAL_AHRS_SBG_ENABLED 0
#endif

#ifndef AP_EXTERNAL_AHRS_VECTORNAV_ENABLED
#define AP_EXTERNAL_AHRS_VECTORNAV_ENABLED 0
#endif

#ifndef AP_EXTERNAL_CONTROL_ENABLED
#define AP_EXTERNAL_CONTROL_ENABLED 0
#endif

#ifndef AP_FASTBOOT_ENABLED
#define AP_FASTBOOT_ENABLED 0
#endif

#ifndef AP_FAULTHANDLER_DEBUG_VARIABLES_ENABLED
#define AP_FAULTHANDLER_DEBUG_VARIABLES_ENABLED 0
#endif

#ifndef AP_FENCE_ENABLED
#define AP_FENCE_ENABLED 0
#endif

#ifndef AP_FETTEC_ONEWIRE_ENABLED
#define AP_FETTEC_ONEWIRE_ENABLED 0
#endif

#ifndef AP_FIELD_ELEVATION_ENABLED
#define AP_FIELD_ELEVATION_ENABLED 0
#endif

#ifndef AP_FILESYSTEM_ESP32_ENABLED
#define AP_FILESYSTEM_ESP32_ENABLED 0
#endif

#ifndef AP_FILESYSTEM_FATFS_ENABLED
#define AP_FILESYSTEM_FATFS_ENABLED 0
#endif

#ifndef AP_FILESYSTEM_FILE_READING_ENABLED
#define AP_FILESYSTEM_FILE_READING_ENABLED 0
#endif

#ifndef AP_FILESYSTEM_FILE_WRITING_ENABLED
#define AP_FILESYSTEM_FILE_WRITING_ENABLED 0
#endif

#ifndef AP_FILESYSTEM_FORMAT_ENABLED
#define AP_FILESYSTEM_FORMAT_ENABLED 0
#endif

#ifndef AP_FILESYSTEM_LITTLEFS_ENABLED
#define AP_FILESYSTEM_LITTLEFS_ENABLED 0
#endif

#ifndef AP_FILESYSTEM_MISSION_ENABLED
#define AP_FILESYSTEM_MISSION_ENABLED 0
#endif

#ifndef AP_FILESYSTEM_PARAM_ENABLED
#define AP_FILESYSTEM_PARAM_ENABLED 0
#endif

#ifndef AP_FILESYSTEM_POSIX_ENABLED
#define AP_FILESYSTEM_POSIX_ENABLED 0
#endif

#ifndef AP_FILESYSTEM_ROMFS_ENABLED
#define AP_FILESYSTEM_ROMFS_ENABLED 0
#endif

#ifndef AP_FILESYSTEM_SYS_ENABLED
#define AP_FILESYSTEM_SYS_ENABLED 0
#endif

#ifndef AP_FILESYSTEM_SYS_FLASH_ENABLED
#define AP_FILESYSTEM_SYS_FLASH_ENABLED 0
#endif

#ifndef AP_FILTER_ENABLED
#define AP_FILTER_ENABLED 0
#endif

#ifndef AP_FLASH_ECC_CHECK_ENABLED
#define AP_FLASH_ECC_CHECK_ENABLED 0
#endif

#ifndef AP_FOLLOW_ENABLED
#define AP_FOLLOW_ENABLED 0
#endif

#ifndef AP_FRSKY_D_TELEM_ENABLED
#define AP_FRSKY_D_TELEM_ENABLED 0
#endif

#ifndef AP_FRSKY_SPORT_PASSTHROUGH_ENABLED
#define AP_FRSKY_SPORT_PASSTHROUGH_ENABLED 0
#endif

#ifndef AP_FRSKY_SPORT_TELEM_ENABLED
#define AP_FRSKY_SPORT_TELEM_ENABLED 0
#endif

#ifndef AP_FRSKY_TELEM_ENABLED
#define AP_FRSKY_TELEM_ENABLED 0
#endif

#ifndef AP_GENERATOR_BACKEND_DEFAULT_ENABLED
#define AP_GENERATOR_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_GENERATOR_CORTEX_ENABLED
#define AP_GENERATOR_CORTEX_ENABLED 0
#endif

#ifndef AP_GENERATOR_IE_2400_ENABLED
#define AP_GENERATOR_IE_2400_ENABLED 0
#endif

#ifndef AP_GENERATOR_IE_650_800_ENABLED
#define AP_GENERATOR_IE_650_800_ENABLED 0
#endif

#ifndef AP_GENERATOR_IE_ENABLED
#define AP_GENERATOR_IE_ENABLED 0
#endif

#ifndef AP_GENERATOR_LOWEHEISER_ENABLED
#define AP_GENERATOR_LOWEHEISER_ENABLED 0
#endif

#ifndef AP_GENERATOR_RICHENPOWER_ENABLED
#define AP_GENERATOR_RICHENPOWER_ENABLED 0
#endif

#ifndef AP_GHST_TELEM_ENABLED
#define AP_GHST_TELEM_ENABLED 0
#endif

#ifndef AP_GPS_BACKEND_DEFAULT_ENABLED
#define AP_GPS_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_GPS_BLENDED_ENABLED
#define AP_GPS_BLENDED_ENABLED 0
#endif

#ifndef AP_GPS_DEBUG_LOGGING_ENABLED
#define AP_GPS_DEBUG_LOGGING_ENABLED 0
#endif

#ifndef AP_GPS_DRONECAN_ENABLED
#define AP_GPS_DRONECAN_ENABLED 0
#endif

// special
#ifndef AP_GPS_ENABLED
#define AP_GPS_ENABLED 1
#endif

#ifndef AP_GPS_ERB_ENABLED
#define AP_GPS_ERB_ENABLED 0
#endif

#ifndef AP_GPS_GPS2_RAW_SENDING_ENABLED
#define AP_GPS_GPS2_RAW_SENDING_ENABLED 0
#endif

#ifndef AP_GPS_GPS2_RTK_SENDING_ENABLED
#define AP_GPS_GPS2_RTK_SENDING_ENABLED 0
#endif

#ifndef AP_GPS_GPS_RAW_INT_SENDING_ENABLED
#define AP_GPS_GPS_RAW_INT_SENDING_ENABLED 0
#endif

#ifndef AP_GPS_GPS_RTK_SENDING_ENABLED
#define AP_GPS_GPS_RTK_SENDING_ENABLED 0
#endif

#ifndef AP_GPS_GSOF_ENABLED
#define AP_GPS_GSOF_ENABLED 0
#endif

#ifndef AP_GPS_MAV_ENABLED
#define AP_GPS_MAV_ENABLED 0
#endif

#ifndef AP_GPS_NMEA_ENABLED
#define AP_GPS_NMEA_ENABLED 0
#endif

#ifndef AP_GPS_NMEA_UNICORE_ENABLED
#define AP_GPS_NMEA_UNICORE_ENABLED 0
#endif

#ifndef AP_GPS_NOVA_ENABLED
#define AP_GPS_NOVA_ENABLED 0
#endif

#ifndef AP_GPS_RTCM_DECODE_ENABLED
#define AP_GPS_RTCM_DECODE_ENABLED 0
#endif

#ifndef AP_GPS_SBF_ENABLED
#define AP_GPS_SBF_ENABLED 0
#endif

#ifndef AP_GPS_SBP2_ENABLED
#define AP_GPS_SBP2_ENABLED 0
#endif

#ifndef AP_GPS_SBP_ENABLED
#define AP_GPS_SBP_ENABLED 0
#endif

#ifndef AP_GPS_SIRF_ENABLED
#define AP_GPS_SIRF_ENABLED 0
#endif

#ifndef AP_GPS_UBLOX_CFGV2_ENABLED
#define AP_GPS_UBLOX_CFGV2_ENABLED 0
#endif

#ifndef AP_GPS_UBLOX_ENABLED
#define AP_GPS_UBLOX_ENABLED 0
#endif

#ifndef AP_GRIPPER_BACKEND_DEFAULT_ENABLED
#define AP_GRIPPER_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_GRIPPER_ENABLED
#define AP_GRIPPER_ENABLED 0
#endif

#ifndef AP_GRIPPER_EPM_ENABLED
#define AP_GRIPPER_EPM_ENABLED 0
#endif

#ifndef AP_GRIPPER_SERVO_ENABLED
#define AP_GRIPPER_SERVO_ENABLED 0
#endif

#ifndef AP_GSOF_ENABLED
#define AP_GSOF_ENABLED 0
#endif

#ifndef AP_HAL_ANALOGIN_ENABLED
#define AP_HAL_ANALOGIN_ENABLED 0
#endif

#ifndef AP_HAL_LINUX_SET_HW_RTC_ENABLED
#define AP_HAL_LINUX_SET_HW_RTC_ENABLED 0
#endif

//special
#ifndef AP_HAL_SHARED_DMA_ENABLED
#define AP_HAL_SHARED_DMA_ENABLED 1
#endif

#ifndef AP_HAL_SPI_ENABLED
#define AP_HAL_SPI_ENABLED 0
#endif

// special
#ifndef AP_HAL_UARTDRIVER_ENABLED
#define AP_HAL_UARTDRIVER_ENABLED 1
#endif

#ifndef AP_HOME_ENABLED
#define AP_HOME_ENABLED 0
#endif

#ifndef AP_IBUS_TELEM_ENABLED
#define AP_IBUS_TELEM_ENABLED 0
#endif

#ifndef AP_ICENGINE_ENABLED
#define AP_ICENGINE_ENABLED 0
#endif

#ifndef AP_ICENGINE_TCA9554_STARTER_ENABLED
#define AP_ICENGINE_TCA9554_STARTER_ENABLED 0
#endif

#ifndef AP_INERTIALSENSOR_BACKEND_DEFAULT_ENABLED
#define AP_INERTIALSENSOR_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_INERTIALSENSOR_BATCHSAMPLER_ENABLED
#define AP_INERTIALSENSOR_BATCHSAMPLER_ENABLED 0
#endif

#ifndef AP_INERTIALSENSOR_ENABLED
#define AP_INERTIALSENSOR_ENABLED 1
#endif

#ifndef AP_INERTIALSENSOR_FAST_SAMPLE_WINDOW_ENABLED
#define AP_INERTIALSENSOR_FAST_SAMPLE_WINDOW_ENABLED 0
#endif

#ifndef AP_INERTIALSENSOR_HARMONICNOTCH_ENABLED
#define AP_INERTIALSENSOR_HARMONICNOTCH_ENABLED 0
#endif

#ifndef AP_INERTIALSENSOR_KILL_IMU_ENABLED
#define AP_INERTIALSENSOR_KILL_IMU_ENABLED 0
#endif

#ifndef AP_INERTIALSENSOR_RATE_LOOP_WINDOW_ENABLED
#define AP_INERTIALSENSOR_RATE_LOOP_WINDOW_ENABLED 0
#endif

#ifndef AP_INERTIALSENSOR_RST_ENABLED
#define AP_INERTIALSENSOR_RST_ENABLED 0
#endif

// special
#ifndef AP_INTERNALERROR_ENABLED
#define AP_INTERNALERROR_ENABLED 1
#endif

#ifndef AP_IOMCU_PROFILED_SUPPORT_ENABLED
#define AP_IOMCU_PROFILED_SUPPORT_ENABLED 0
#endif

#ifndef AP_IRLOCK_BACKEND_DEFAULT_ENABLED
#define AP_IRLOCK_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_IRLOCK_ENABLED
#define AP_IRLOCK_ENABLED 0
#endif

#ifndef AP_IRLOCK_I2C_ENABLED
#define AP_IRLOCK_I2C_ENABLED 0
#endif

#ifndef AP_IRLOCK_SITL_ENABLED
#define AP_IRLOCK_SITL_ENABLED 0
#endif

#ifndef AP_IRLOCK_SITL_GAZEBO_ENABLED
#define AP_IRLOCK_SITL_GAZEBO_ENABLED 0
#endif

#ifndef AP_KDECAN_ENABLED
#define AP_KDECAN_ENABLED 0
#endif

#ifndef AP_LANDINGGEAR_ENABLED
#define AP_LANDINGGEAR_ENABLED 0
#endif

#ifndef AP_LIGHTWARESERIAL_ENABLED
#define AP_LIGHTWARESERIAL_ENABLED 0
#endif

#ifndef AP_LTM_TELEM_ENABLED
#define AP_LTM_TELEM_ENABLED 0
#endif

#ifndef AP_MAVLINK_AUTOPILOT_VERSION_REQUEST_ENABLED
#define AP_MAVLINK_AUTOPILOT_VERSION_REQUEST_ENABLED 0
#endif

#ifndef AP_MAVLINKCAN_ENABLED
#define AP_MAVLINKCAN_ENABLED 0
#endif

#ifndef AP_MAVLINK_COMMAND_LONG_ENABLED
#define AP_MAVLINK_COMMAND_LONG_ENABLED 0
#endif

#ifndef AP_MAVLINK_FAILURE_CREATION_ENABLED
#define AP_MAVLINK_FAILURE_CREATION_ENABLED 0
#endif

#ifndef AP_MAVLINK_FOLLOW_HANDLING_ENABLED
#define AP_MAVLINK_FOLLOW_HANDLING_ENABLED 0
#endif

#ifndef AP_MAVLINK_FTP_ENABLED
#define AP_MAVLINK_FTP_ENABLED 0
#endif

#ifndef AP_MAVLINK_MAV_CMD_NAV_SET_YAW_SPEED_ENABLED
#define AP_MAVLINK_MAV_CMD_NAV_SET_YAW_SPEED_ENABLED 0
#endif

#ifndef AP_MAVLINK_MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES_ENABLED
#define AP_MAVLINK_MAV_CMD_REQUEST_AUTOPILOT_CAPABILITIES_ENABLED 0
#endif

#ifndef AP_MAVLINK_MAV_CMD_SET_HAGL_ENABLED
#define AP_MAVLINK_MAV_CMD_SET_HAGL_ENABLED 0
#endif

#ifndef AP_MAVLINK_MISSION_SET_CURRENT_ENABLED
#define AP_MAVLINK_MISSION_SET_CURRENT_ENABLED 0
#endif

#ifndef AP_MAVLINK_MSG_DEVICE_OP_ENABLED
#define AP_MAVLINK_MSG_DEVICE_OP_ENABLED 0
#endif

#ifndef AP_MAVLINK_MSG_FLIGHT_INFORMATION_ENABLED
#define AP_MAVLINK_MSG_FLIGHT_INFORMATION_ENABLED 0
#endif

#ifndef AP_MAVLINK_MSG_HIGHRES_IMU_ENABLED
#define AP_MAVLINK_MSG_HIGHRES_IMU_ENABLED 0
#endif

#ifndef AP_MAVLINK_MSG_HWSTATUS_ENABLED
#define AP_MAVLINK_MSG_HWSTATUS_ENABLED 0
#endif

#ifndef AP_MAVLINK_MSG_MISSION_REQUEST_ENABLED
#define AP_MAVLINK_MSG_MISSION_REQUEST_ENABLED 0
#endif

#ifndef AP_MAVLINK_MSG_RANGEFINDER_SENDING_ENABLED
#define AP_MAVLINK_MSG_RANGEFINDER_SENDING_ENABLED 0
#endif

#ifndef AP_MAVLINK_MSG_RC_CHANNELS_RAW_ENABLED
#define AP_MAVLINK_MSG_RC_CHANNELS_RAW_ENABLED 0
#endif

#ifndef AP_MAVLINK_MSG_RELAY_STATUS_ENABLED
#define AP_MAVLINK_MSG_RELAY_STATUS_ENABLED 0
#endif

#ifndef AP_MAVLINK_MSG_SERIAL_CONTROL_ENABLED
#define AP_MAVLINK_MSG_SERIAL_CONTROL_ENABLED 0
#endif

#ifndef AP_MAVLINK_MSG_UAVIONIX_ADSB_OUT_STATUS_ENABLED
#define AP_MAVLINK_MSG_UAVIONIX_ADSB_OUT_STATUS_ENABLED 0
#endif

#ifndef AP_MAVLINK_MSG_VIDEO_STREAM_INFORMATION_ENABLED
#define AP_MAVLINK_MSG_VIDEO_STREAM_INFORMATION_ENABLED 0
#endif

#ifndef AP_MAVLINK_MSG_WIND_ENABLED
#define AP_MAVLINK_MSG_WIND_ENABLED 0
#endif

#ifndef AP_MAVLINK_PACKETISE_ENABLED
#define AP_MAVLINK_PACKETISE_ENABLED 0
#endif

#ifndef AP_MAVLINK_RALLY_POINT_PROTOCOL_ENABLED
#define AP_MAVLINK_RALLY_POINT_PROTOCOL_ENABLED 0
#endif

#ifndef AP_MAVLINK_SERVO_RELAY_ENABLED
#define AP_MAVLINK_SERVO_RELAY_ENABLED 0
#endif

#ifndef AP_MAVLINK_SET_GPS_GLOBAL_ORIGIN_MESSAGE_ENABLED
#define AP_MAVLINK_SET_GPS_GLOBAL_ORIGIN_MESSAGE_ENABLED 0
#endif

#ifndef AP_MAVLINK_SIGNING_ENABLED
#define AP_MAVLINK_SIGNING_ENABLED 0
#endif

#ifndef AP_MICROSTRAIN_ENABLED
#define AP_MICROSTRAIN_ENABLED 0
#endif

#ifndef AP_MISSION_ENABLED
#define AP_MISSION_ENABLED 0
#endif

#ifndef AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED
#define AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED 0
#endif

#ifndef AP_MOTORS_FRAME_DECA_ENABLED
#define AP_MOTORS_FRAME_DECA_ENABLED 0
#endif

#ifndef AP_MOTORS_FRAME_DEFAULT_ENABLED
#define AP_MOTORS_FRAME_DEFAULT_ENABLED 0
#endif

#ifndef AP_MOTORS_FRAME_DODECAHEXA_ENABLED
#define AP_MOTORS_FRAME_DODECAHEXA_ENABLED 0
#endif

#ifndef AP_MOTORS_FRAME_HEXA_ENABLED
#define AP_MOTORS_FRAME_HEXA_ENABLED 0
#endif

#ifndef AP_MOTORS_FRAME_OCTA_ENABLED
#define AP_MOTORS_FRAME_OCTA_ENABLED 0
#endif

#ifndef AP_MOTORS_FRAME_OCTAQUAD_ENABLED
#define AP_MOTORS_FRAME_OCTAQUAD_ENABLED 0
#endif

#ifndef AP_MOTORS_FRAME_QUAD_ENABLED
#define AP_MOTORS_FRAME_QUAD_ENABLED 0
#endif

#ifndef AP_MOTORS_FRAME_Y6_ENABLED
#define AP_MOTORS_FRAME_Y6_ENABLED 0
#endif

#ifndef AP_MOTORS_TRI_ENABLED
#define AP_MOTORS_TRI_ENABLED 0
#endif

#ifndef AP_MOUNT_BACKEND_DEFAULT_ENABLED
#define AP_MOUNT_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_MOUNT_POI_LOCK_ENABLED
#define AP_MOUNT_POI_LOCK_ENABLED 0
#endif

#ifndef AP_MOUNT_POI_TO_LATLONALT_ENABLED
#define AP_MOUNT_POI_TO_LATLONALT_ENABLED 0
#endif

#ifndef AP_MOUNT_SEND_THERMAL_RANGE_ENABLED
#define AP_MOUNT_SEND_THERMAL_RANGE_ENABLED 0
#endif

#ifndef AP_MSP_INAV_FONTS_ENABLED
#define AP_MSP_INAV_FONTS_ENABLED 0
#endif

#ifndef AP_NETWORKING_BACKEND_DEFAULT_ENABLED
#define AP_NETWORKING_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_NETWORKING_CAN_MCAST_BRIDGING_ENABLED
#define AP_NETWORKING_CAN_MCAST_BRIDGING_ENABLED 0
#endif

#ifndef AP_NETWORKING_CAN_MCAST_ENABLED
#define AP_NETWORKING_CAN_MCAST_ENABLED 0
#endif

#ifndef AP_NETWORKING_CAPTURE_ENABLED
#define AP_NETWORKING_CAPTURE_ENABLED 0
#endif

#ifndef AP_NETWORKING_CONTROLS_HOST_IP_SETTINGS_ENABLED
#define AP_NETWORKING_CONTROLS_HOST_IP_SETTINGS_ENABLED 0
#endif

#ifndef AP_NETWORKING_ENABLED
#define AP_NETWORKING_ENABLED 0
#endif

#ifndef AP_NETWORKING_PPP_GATEWAY_ENABLED
#define AP_NETWORKING_PPP_GATEWAY_ENABLED 0
#endif

#ifndef AP_NETWORKING_REGISTER_PORT_ENABLED
#define AP_NETWORKING_REGISTER_PORT_ENABLED 0
#endif

#ifndef AP_NETWORKING_SOCKETS_ENABLED
#define AP_NETWORKING_SOCKETS_ENABLED 0
#endif

#ifndef AP_NETWORKING_TESTS_ENABLED
#define AP_NETWORKING_TESTS_ENABLED 0
#endif

#ifndef AP_NMEA_OUTPUT_MESSAGE_ENABLED
#define AP_NMEA_OUTPUT_MESSAGE_ENABLED 0
#endif

#ifndef AP_NOTIFY_BUZZER_ENABLED
#define AP_NOTIFY_BUZZER_ENABLED 0
#endif

#ifndef AP_NOTIFY_DISCO_LED_ENABLED
#define AP_NOTIFY_DISCO_LED_ENABLED 0
#endif

#ifndef AP_NOTIFY_DISCRETE_RGB_ENABLED
#define AP_NOTIFY_DISCRETE_RGB_ENABLED 0
#endif

#ifndef AP_NOTIFY_DRONECAN_LED_ENABLED
#define AP_NOTIFY_DRONECAN_LED_ENABLED 0
#endif

#ifndef AP_NOTIFY_DSHOT_LED_ENABLED
#define AP_NOTIFY_DSHOT_LED_ENABLED 0
#endif

#ifndef AP_NOTIFY_EXTERNALLED_ENABLED
#define AP_NOTIFY_EXTERNALLED_ENABLED 0
#endif

#ifndef AP_NOTIFY_GPIO_LED_1_ENABLED
#define AP_NOTIFY_GPIO_LED_1_ENABLED 0
#endif

#ifndef AP_NOTIFY_GPIO_LED_2_ENABLED
#define AP_NOTIFY_GPIO_LED_2_ENABLED 0
#endif

#ifndef AP_NOTIFY_GPIO_LED_3_ENABLED
#define AP_NOTIFY_GPIO_LED_3_ENABLED 0
#endif

#ifndef AP_NOTIFY_GPIO_LED_ENABLED
#define AP_NOTIFY_GPIO_LED_ENABLED 0
#endif

#ifndef AP_NOTIFY_GPIO_LED_RGB_ENABLED
#define AP_NOTIFY_GPIO_LED_RGB_ENABLED 0
#endif

#ifndef AP_NOTIFY_IS31FL3195_ENABLED
#define AP_NOTIFY_IS31FL3195_ENABLED 0
#endif

#ifndef AP_NOTIFY_LP5562_ENABLED
#define AP_NOTIFY_LP5562_ENABLED 0
#endif

#ifndef AP_NOTIFY_MAVLINK_LED_CONTROL_SUPPORT_ENABLED
#define AP_NOTIFY_MAVLINK_LED_CONTROL_SUPPORT_ENABLED 0
#endif

#ifndef AP_NOTIFY_MAVLINK_PLAY_TUNE_SUPPORT_ENABLED
#define AP_NOTIFY_MAVLINK_PLAY_TUNE_SUPPORT_ENABLED 0
#endif

#ifndef AP_NOTIFY_NAVIGATOR_LED_ENABLED
#define AP_NOTIFY_NAVIGATOR_LED_ENABLED 0
#endif

#ifndef AP_NOTIFY_NCP5623_ENABLED
#define AP_NOTIFY_NCP5623_ENABLED 0
#endif

#ifndef AP_NOTIFY_NEOPIXEL_ENABLED
#define AP_NOTIFY_NEOPIXEL_ENABLED 0
#endif

#ifndef AP_NOTIFY_OREOLED_ENABLED
#define AP_NOTIFY_OREOLED_ENABLED 0
#endif

#ifndef AP_NOTIFY_PCA9685_ENABLED
#define AP_NOTIFY_PCA9685_ENABLED 0
#endif

#ifndef AP_NOTIFY_PROFILED_ENABLED
#define AP_NOTIFY_PROFILED_ENABLED 0
#endif

#ifndef AP_NOTIFY_PROFILED_SPI_ENABLED
#define AP_NOTIFY_PROFILED_SPI_ENABLED 0
#endif

#ifndef AP_NOTIFY_RCOUTPUTRGBLEDINVERTED_LED_ENABLED
#define AP_NOTIFY_RCOUTPUTRGBLEDINVERTED_LED_ENABLED 0
#endif

#ifndef AP_NOTIFY_RCOUTPUTRGBLED_LED_ENABLED
#define AP_NOTIFY_RCOUTPUTRGBLED_LED_ENABLED 0
#endif

#ifndef AP_NOTIFY_RCOUTPUTRGBLEDOFF_LED_ENABLED
#define AP_NOTIFY_RCOUTPUTRGBLEDOFF_LED_ENABLED 0
#endif

#ifndef AP_NOTIFY_SCRIPTING_LED_ENABLED
#define AP_NOTIFY_SCRIPTING_LED_ENABLED 0
#endif

#ifndef AP_NOTIFY_SERIALLED_ENABLED
#define AP_NOTIFY_SERIALLED_ENABLED 0
#endif

#ifndef AP_NOTIFY_SYSFS_LED_ENABLED
#define AP_NOTIFY_SYSFS_LED_ENABLED 0
#endif

#ifndef AP_NOTIFY_TONEALARM_ENABLED
#define AP_NOTIFY_TONEALARM_ENABLED 0
#endif

#ifndef AP_NOTIFY_TOSHIBALED_ENABLED
#define AP_NOTIFY_TOSHIBALED_ENABLED 0
#endif

#ifndef AP_NOTIFY_VRBOARD_LED_ENABLED
#define AP_NOTIFY_VRBOARD_LED_ENABLED 0
#endif

#ifndef AP_OADATABASE_ENABLED
#define AP_OADATABASE_ENABLED 0
#endif

#ifndef AP_OAPATHPLANNER_BACKEND_DEFAULT_ENABLED
#define AP_OAPATHPLANNER_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_OAPATHPLANNER_BENDYRULER_ENABLED
#define AP_OAPATHPLANNER_BENDYRULER_ENABLED 0
#endif

#ifndef AP_OAPATHPLANNER_DIJKSTRA_ENABLED
#define AP_OAPATHPLANNER_DIJKSTRA_ENABLED 0
#endif

#ifndef AP_OAPATHPLANNER_ENABLED
#define AP_OAPATHPLANNER_ENABLED 0
#endif

#ifndef AP_OPENDRONEID_ENABLED
#define AP_OPENDRONEID_ENABLED 0
#endif

#ifndef AP_OPTICALFLOW_BACKEND_DEFAULT_ENABLED
#define AP_OPTICALFLOW_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_OPTICALFLOW_CALIBRATOR_ENABLED
#define AP_OPTICALFLOW_CALIBRATOR_ENABLED 0
#endif

#ifndef AP_OPTICALFLOW_CXOF_ENABLED
#define AP_OPTICALFLOW_CXOF_ENABLED 0
#endif

#ifndef AP_OPTICALFLOW_ENABLED
#define AP_OPTICALFLOW_ENABLED 0
#endif

#ifndef AP_OPTICALFLOW_HEREFLOW_ENABLED
#define AP_OPTICALFLOW_HEREFLOW_ENABLED 0
#endif

#ifndef AP_OPTICALFLOW_MAV_ENABLED
#define AP_OPTICALFLOW_MAV_ENABLED 0
#endif

#ifndef AP_OPTICALFLOW_ONBOARD_ENABLED
#define AP_OPTICALFLOW_ONBOARD_ENABLED 0
#endif

#ifndef AP_OPTICALFLOW_PIXART_ENABLED
#define AP_OPTICALFLOW_PIXART_ENABLED 0
#endif

#ifndef AP_OPTICALFLOW_PX4FLOW_ENABLED
#define AP_OPTICALFLOW_PX4FLOW_ENABLED 0
#endif

#ifndef AP_OPTICALFLOW_SITL_ENABLED
#define AP_OPTICALFLOW_SITL_ENABLED 0
#endif

#ifndef AP_OPTICALFLOW_UPFLOW_ENABLED
#define AP_OPTICALFLOW_UPFLOW_ENABLED 0
#endif

#ifndef AP_OSD_CALLSIGN_FROM_SD_ENABLED
#define AP_OSD_CALLSIGN_FROM_SD_ENABLED 0
#endif

#ifndef AP_OSD_LINK_STATS_EXTENSIONS_ENABLED
#define AP_OSD_LINK_STATS_EXTENSIONS_ENABLED 0
#endif

// #ifndef AP_PARAM_DEFAULTS_ENABLED
// #define AP_PARAM_DEFAULTS_ENABLED 0
// #endif
//libraries/AP_Param/AP_Param.h line 45

#ifndef AP_PARAM_DEFAULTS_FILE_PARSING_ENABLED
#define AP_PARAM_DEFAULTS_FILE_PARSING_ENABLED 0
#endif

#ifndef AP_PARAM_DYNAMIC_ENABLED
#define AP_PARAM_DYNAMIC_ENABLED 0
#endif

#ifndef AP_PARAM_STORAGE_BAK_ENABLED
#define AP_PARAM_STORAGE_BAK_ENABLED 0
#endif

#ifndef AP_PERIPH_ACTUATOR_TELEM_ENABLED
#define AP_PERIPH_ACTUATOR_TELEM_ENABLED 0
#endif

#ifndef AP_PERIPH_ADSB_ENABLED
#define AP_PERIPH_ADSB_ENABLED 0
#endif

#ifndef AP_PERIPH_AIRSPEED_ENABLED
#define AP_PERIPH_AIRSPEED_ENABLED 0
#endif

#ifndef AP_PERIPH_BARO_ENABLED
#define AP_PERIPH_BARO_ENABLED 0
#endif

#ifndef AP_PERIPH_BATTERY_BALANCE_ENABLED
#define AP_PERIPH_BATTERY_BALANCE_ENABLED 0
#endif

#ifndef AP_PERIPH_BATTERY_BMS_ENABLED
#define AP_PERIPH_BATTERY_BMS_ENABLED 0
#endif

#ifndef AP_PERIPH_BATTERY_ENABLED
#define AP_PERIPH_BATTERY_ENABLED 0
#endif

#ifndef AP_PERIPH_BATTERY_TAG_ENABLED
#define AP_PERIPH_BATTERY_TAG_ENABLED 0
#endif

#ifndef AP_PERIPH_BUZZER_ENABLED
#define AP_PERIPH_BUZZER_ENABLED 0
#endif

#ifndef AP_PERIPH_BUZZER_WITHOUT_NOTIFY_ENABLED
#define AP_PERIPH_BUZZER_WITHOUT_NOTIFY_ENABLED 0
#endif

#ifndef AP_PERIPH_DEVICE_TEMPERATURE_ENABLED
#define AP_PERIPH_DEVICE_TEMPERATURE_ENABLED 0
#endif

#ifndef AP_PERIPH_EFI_ENABLED
#define AP_PERIPH_EFI_ENABLED 0
#endif

#ifndef AP_PERIPH_ESC_APD_ENABLED
#define AP_PERIPH_ESC_APD_ENABLED 0
#endif

#ifndef AP_PERIPH_GPS_ENABLED
#define AP_PERIPH_GPS_ENABLED 0
#endif

#ifndef AP_PERIPH_GPS_TYPE_COMPATABILITY_ENABLED
#define AP_PERIPH_GPS_TYPE_COMPATABILITY_ENABLED 0
#endif

#ifndef AP_PERIPH_HOBBYWING_ESC_ENABLED
#define AP_PERIPH_HOBBYWING_ESC_ENABLED 0
#endif

#ifndef AP_PERIPH_IMU_ENABLED
#define AP_PERIPH_IMU_ENABLED 0
#endif

#ifndef AP_PERIPH_MAG_ENABLED
#define AP_PERIPH_MAG_ENABLED 0
#endif

#ifndef AP_PERIPH_MSP_ENABLED
#define AP_PERIPH_MSP_ENABLED 0
#endif

#ifndef AP_PERIPH_NCP5623_BGR_LED_WITHOUT_NOTIFY_ENABLED
#define AP_PERIPH_NCP5623_BGR_LED_WITHOUT_NOTIFY_ENABLED 0
#endif

#ifndef AP_PERIPH_NCP5623_LED_WITHOUT_NOTIFY_ENABLED
#define AP_PERIPH_NCP5623_LED_WITHOUT_NOTIFY_ENABLED 0
#endif

#ifndef AP_PERIPH_NETWORKING_ENABLED
#define AP_PERIPH_NETWORKING_ENABLED 0
#endif

#ifndef AP_PERIPH_NOTIFY_ENABLED
#define AP_PERIPH_NOTIFY_ENABLED 0
#endif

#ifndef AP_PERIPH_PROXIMITY_ENABLED
#define AP_PERIPH_PROXIMITY_ENABLED 0
#endif

#ifndef AP_PERIPH_PWM_HARDPOINT_ENABLED
#define AP_PERIPH_PWM_HARDPOINT_ENABLED 0
#endif

#ifndef AP_PERIPH_RANGEFINDER_ENABLED
#define AP_PERIPH_RANGEFINDER_ENABLED 0
#endif

#ifndef AP_PERIPH_RCIN_ENABLED
#define AP_PERIPH_RCIN_ENABLED 0
#endif

#ifndef AP_PERIPH_RC_OUT_ENABLED
#define AP_PERIPH_RC_OUT_ENABLED 0
#endif

#ifndef AP_PERIPH_RELAY_ENABLED
#define AP_PERIPH_RELAY_ENABLED 0
#endif

#ifndef AP_PERIPH_RPM_ENABLED
#define AP_PERIPH_RPM_ENABLED 0
#endif

#ifndef AP_PERIPH_RPM_STREAM_ENABLED
#define AP_PERIPH_RPM_STREAM_ENABLED 0
#endif

#ifndef AP_PERIPH_RTC_ENABLED
#define AP_PERIPH_RTC_ENABLED 0
#endif

#ifndef AP_PERIPH_RTC_GLOBALTIME_ENABLED
#define AP_PERIPH_RTC_GLOBALTIME_ENABLED 0
#endif

#ifndef AP_PERIPH_SAFETY_SWITCH_ENABLED
#define AP_PERIPH_SAFETY_SWITCH_ENABLED 0
#endif

#ifndef AP_PERIPH_SERIAL_OPTIONS_ENABLED
#define AP_PERIPH_SERIAL_OPTIONS_ENABLED 0
#endif

#ifndef AP_PERIPH_TOSHIBA_LED_WITHOUT_NOTIFY_ENABLED
#define AP_PERIPH_TOSHIBA_LED_WITHOUT_NOTIFY_ENABLED 0
#endif

#ifndef AP_PICCOLOCAN_ENABLED
#define AP_PICCOLOCAN_ENABLED 0
#endif

#ifndef AP_PLANE_GLIDER_PULLUP_ENABLED
#define AP_PLANE_GLIDER_PULLUP_ENABLED 0
#endif

#ifndef AP_PLANE_OFFBOARD_GUIDED_SLEW_ENABLED
#define AP_PLANE_OFFBOARD_GUIDED_SLEW_ENABLED 0
#endif

#ifndef AP_PLANE_SYSTEMID_ENABLED
#define AP_PLANE_SYSTEMID_ENABLED 0
#endif

#ifndef AP_PROXIMITY_AIRSIMSITL_ENABLED
#define AP_PROXIMITY_AIRSIMSITL_ENABLED 0
#endif

#ifndef AP_PROXIMITY_BACKEND_DEFAULT_ENABLED
#define AP_PROXIMITY_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_PROXIMITY_CYGBOT_ENABLED
#define AP_PROXIMITY_CYGBOT_ENABLED 0
#endif

#ifndef AP_PROXIMITY_DRONECAN_ENABLED
#define AP_PROXIMITY_DRONECAN_ENABLED 0
#endif

#ifndef AP_PROXIMITY_HEXSOONRADAR_ENABLED
#define AP_PROXIMITY_HEXSOONRADAR_ENABLED 0
#endif

#ifndef AP_PROXIMITY_LD06_ENABLED
#define AP_PROXIMITY_LD06_ENABLED 0
#endif

#ifndef AP_PROXIMITY_LIGHTWARE_SF40C_ENABLED
#define AP_PROXIMITY_LIGHTWARE_SF40C_ENABLED 0
#endif

#ifndef AP_PROXIMITY_LIGHTWARE_SF45B_ENABLED
#define AP_PROXIMITY_LIGHTWARE_SF45B_ENABLED 0
#endif

#ifndef AP_PROXIMITY_MAV_ENABLED
#define AP_PROXIMITY_MAV_ENABLED 0
#endif

#ifndef AP_PROXIMITY_MR72_DRIVER_ENABLED
#define AP_PROXIMITY_MR72_DRIVER_ENABLED 0
#endif

#ifndef AP_PROXIMITY_MR72_ENABLED
#define AP_PROXIMITY_MR72_ENABLED 0
#endif

#ifndef AP_PROXIMITY_RANGEFINDER_ENABLED
#define AP_PROXIMITY_RANGEFINDER_ENABLED 0
#endif

#ifndef AP_PROXIMITY_RPLIDARA2_ENABLED
#define AP_PROXIMITY_RPLIDARA2_ENABLED 0
#endif

#ifndef AP_PROXIMITY_SCRIPTING_ENABLED
#define AP_PROXIMITY_SCRIPTING_ENABLED 0
#endif

#ifndef AP_PROXIMITY_SITL_ENABLED
#define AP_PROXIMITY_SITL_ENABLED 0
#endif

#ifndef AP_PROXIMITY_TERARANGERTOWER_ENABLED
#define AP_PROXIMITY_TERARANGERTOWER_ENABLED 0
#endif

#ifndef AP_PROXIMITY_TERARANGERTOWEREVO_ENABLED
#define AP_PROXIMITY_TERARANGERTOWEREVO_ENABLED 0
#endif

#ifndef AP_QUICKTUNE_ENABLED
#define AP_QUICKTUNE_ENABLED 0
#endif

#ifndef AP_RADIO_AUTO_ENABLED
#define AP_RADIO_AUTO_ENABLED 0
#endif

#ifndef AP_RADIO_BACKEND_DEFAULT_ENABLED
#define AP_RADIO_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_RADIO_BK2425_ENABLED
#define AP_RADIO_BK2425_ENABLED 0
#endif

#ifndef AP_RADIO_CC2500_ENABLED
#define AP_RADIO_CC2500_ENABLED 0
#endif

#ifndef AP_RADIO_CYRF6936_ENABLED
#define AP_RADIO_CYRF6936_ENABLED 0
#endif

#ifndef AP_RADIO_CYRPRESS_ENABLED
#define AP_RADIO_CYRPRESS_ENABLED 0
#endif

#ifndef AP_RADIO_ENABLED
#define AP_RADIO_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_AINSTEIN_LR_D1_ENABLED
#define AP_RANGEFINDER_AINSTEIN_LR_D1_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_ANALOG_ENABLED
#define AP_RANGEFINDER_ANALOG_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_BACKEND_CAN_ENABLED
#define AP_RANGEFINDER_BACKEND_CAN_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_BACKEND_DEFAULT_ENABLED
#define AP_RANGEFINDER_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_BBB_PRU_ENABLED
#define AP_RANGEFINDER_BBB_PRU_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_BEBOP_ENABLED
#define AP_RANGEFINDER_BEBOP_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_BENEWAKE_CAN_ENABLED
#define AP_RANGEFINDER_BENEWAKE_CAN_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_BENEWAKE_ENABLED
#define AP_RANGEFINDER_BENEWAKE_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_BENEWAKE_TF02_ENABLED
#define AP_RANGEFINDER_BENEWAKE_TF02_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_BENEWAKE_TF03_ENABLED
#define AP_RANGEFINDER_BENEWAKE_TF03_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_BENEWAKE_TFMINI_ENABLED
#define AP_RANGEFINDER_BENEWAKE_TFMINI_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_BENEWAKE_TFMINIPLUS_ENABLED
#define AP_RANGEFINDER_BENEWAKE_TFMINIPLUS_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_BENEWAKE_TFS20L_ENABLED
#define AP_RANGEFINDER_BENEWAKE_TFS20L_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_BLPING_ENABLED
#define AP_RANGEFINDER_BLPING_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_DRONECAN_ENABLED
#define AP_RANGEFINDER_DRONECAN_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_DTS6012M_ENABLED
#define AP_RANGEFINDER_DTS6012M_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_ENABLED
#define AP_RANGEFINDER_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_GYUS42V2_ENABLED
#define AP_RANGEFINDER_GYUS42V2_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_HC_SR04_ENABLED
#define AP_RANGEFINDER_HC_SR04_ENABLED 0
#endif

// #ifndef AP_RANGEFINDER_HEXSOONRADAR_ENABLED
// #define AP_RANGEFINDER_HEXSOONRADAR_ENABLED 0
// #endif

#ifndef AP_RANGEFINDER_JRE_SERIAL_ENABLED
#define AP_RANGEFINDER_JRE_SERIAL_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_LANBAO_ENABLED
#define AP_RANGEFINDER_LANBAO_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_LEDDARONE_ENABLED
#define AP_RANGEFINDER_LEDDARONE_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_LEDDARVU8_ENABLED
#define AP_RANGEFINDER_LEDDARVU8_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_LIGHTWARE_GRF_ENABLED
#define AP_RANGEFINDER_LIGHTWARE_GRF_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_LIGHTWARE_SERIAL_ENABLED
#define AP_RANGEFINDER_LIGHTWARE_SERIAL_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_LUA_ENABLED
#define AP_RANGEFINDER_LUA_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_LWI2C_ENABLED
#define AP_RANGEFINDER_LWI2C_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_MAVLINK_ENABLED
#define AP_RANGEFINDER_MAVLINK_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_MAXBOTIX_SERIAL_ENABLED
#define AP_RANGEFINDER_MAXBOTIX_SERIAL_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_MAXSONARI2CXL_ENABLED
#define AP_RANGEFINDER_MAXSONARI2CXL_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_NMEA_ENABLED
#define AP_RANGEFINDER_NMEA_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_NOOPLOOP_ENABLED
#define AP_RANGEFINDER_NOOPLOOP_ENABLED 0
#endif

// #ifndef AP_RANGEFINDER_NRA24_CAN_DRIVER_ENABLED
// #define AP_RANGEFINDER_NRA24_CAN_DRIVER_ENABLED 0
// #endif

#ifndef AP_RANGEFINDER_NRA24_CAN_ENABLED
#define AP_RANGEFINDER_NRA24_CAN_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_PULSEDLIGHTLRF_ENABLED
#define AP_RANGEFINDER_PULSEDLIGHTLRF_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_PWM_ENABLED
#define AP_RANGEFINDER_PWM_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_RDS02UF_ENABLED
#define AP_RANGEFINDER_RDS02UF_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_SIM_ENABLED
#define AP_RANGEFINDER_SIM_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_TERARANGER_SERIAL_ENABLED
#define AP_RANGEFINDER_TERARANGER_SERIAL_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_TOFSENSEF_I2C_ENABLED
#define AP_RANGEFINDER_TOFSENSEF_I2C_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_TOFSENSEP_CAN_ENABLED
#define AP_RANGEFINDER_TOFSENSEP_CAN_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_TRI2C_ENABLED
#define AP_RANGEFINDER_TRI2C_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_USD1_CAN_ENABLED
#define AP_RANGEFINDER_USD1_CAN_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_USD1_SERIAL_ENABLED
#define AP_RANGEFINDER_USD1_SERIAL_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_VL53L0X_ENABLED
#define AP_RANGEFINDER_VL53L0X_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_VL53L1X_ENABLED
#define AP_RANGEFINDER_VL53L1X_ENABLED 0
#endif

#ifndef AP_RANGEFINDER_WASP_ENABLED
#define AP_RANGEFINDER_WASP_ENABLED 0
#endif

#ifndef AP_RC_CHANNEL_AUX_FUNCTION_STRINGS_ENABLED
#define AP_RC_CHANNEL_AUX_FUNCTION_STRINGS_ENABLED 0
#endif

// bit special
#ifndef AP_RC_CHANNEL_ENABLED
#define AP_RC_CHANNEL_ENABLED 1
#endif

#ifndef AP_RCMAPPER_ENABLED
#define AP_RCMAPPER_ENABLED 0
#endif

#ifndef AP_RCOUTPUT_ZYNQ_ENABLED
#define AP_RCOUTPUT_ZYNQ_ENABLED 0
#endif

#ifndef AP_RCPROTCOL_ENABLED
#define AP_RCPROTCOL_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_BACKEND_DEFAULT_ENABLED
#define AP_RCPROTOCOL_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_CRSF_ENABLED
#define AP_RCPROTOCOL_CRSF_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_DRONECAN_ENABLED
#define AP_RCPROTOCOL_DRONECAN_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_DSM_ENABLED
#define AP_RCPROTOCOL_DSM_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_EMLID_RCIO_ENABLED
#define AP_RCPROTOCOL_EMLID_RCIO_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_ENABLED
#define AP_RCPROTOCOL_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_FASTSBUS_ENABLED
#define AP_RCPROTOCOL_FASTSBUS_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_FDM_ENABLED
#define AP_RCPROTOCOL_FDM_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_FPORT2_ENABLED
#define AP_RCPROTOCOL_FPORT2_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_FPORT_ENABLED
#define AP_RCPROTOCOL_FPORT_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_GHST_ENABLED
#define AP_RCPROTOCOL_GHST_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_IBUS_ENABLED
#define AP_RCPROTOCOL_IBUS_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_IOMCU_ENABLED
#define AP_RCPROTOCOL_IOMCU_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_JOYSTICK_SFML_ENABLED
#define AP_RCPROTOCOL_JOYSTICK_SFML_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_MAVLINK_RADIO_ENABLED
#define AP_RCPROTOCOL_MAVLINK_RADIO_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_PPMSUM_ENABLED
#define AP_RCPROTOCOL_PPMSUM_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_RADIO_ENABLED
#define AP_RCPROTOCOL_RADIO_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_SBUS_ENABLED
#define AP_RCPROTOCOL_SBUS_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_SBUS_NI_ENABLED
#define AP_RCPROTOCOL_SBUS_NI_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_SRXL2_ENABLED
#define AP_RCPROTOCOL_SRXL2_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_SRXL_ENABLED
#define AP_RCPROTOCOL_SRXL_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_ST24_ENABLED
#define AP_RCPROTOCOL_ST24_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_SUMD_ENABLED
#define AP_RCPROTOCOL_SUMD_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_UDP_ENABLED
#define AP_RCPROTOCOL_UDP_ENABLED 0
#endif

#ifndef AP_RCPROTOCOL_ZYNQ_ENABLED
#define AP_RCPROTOCOL_ZYNQ_ENABLED 0
#endif

#ifndef AP_RC_TRANSMITTER_TUNING_ENABLED
#define AP_RC_TRANSMITTER_TUNING_ENABLED 0
#endif

// #ifndef AP_RELAY_DRONECAN_ENABLED
// #define AP_RELAY_DRONECAN_ENABLED 0
// #endif
// see libraries/AP_Relay/AP_Relay_config.h

#ifndef AP_RELAY_ENABLED
#define AP_RELAY_ENABLED 0
#endif

#ifndef AP_ROBOTISSERVO_ENABLED
#define AP_ROBOTISSERVO_ENABLED 0
#endif

#ifndef AP_ROVER_ADVANCED_FAILSAFE_ENABLED
#define AP_ROVER_ADVANCED_FAILSAFE_ENABLED 0
#endif

#ifndef AP_ROVER_AUTO_ARM_ONCE_ENABLED
#define AP_ROVER_AUTO_ARM_ONCE_ENABLED 0
#endif

#ifndef AP_RPM_BACKEND_DEFAULT_ENABLED
#define AP_RPM_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_RPM_DRONECAN_ENABLED
#define AP_RPM_DRONECAN_ENABLED 0
#endif

#ifndef AP_RPM_EFI_ENABLED
#define AP_RPM_EFI_ENABLED 0
#endif

#ifndef AP_RPM_ENABLED
#define AP_RPM_ENABLED 0
#endif

#ifndef AP_RPM_ESC_TELEM_ENABLED
#define AP_RPM_ESC_TELEM_ENABLED 0
#endif

#ifndef AP_RPM_ESC_TELEM_OUTBOUND_ENABLED
#define AP_RPM_ESC_TELEM_OUTBOUND_ENABLED 0
#endif

#ifndef AP_RPM_GENERATOR_ENABLED
#define AP_RPM_GENERATOR_ENABLED 0
#endif

#ifndef AP_RPM_HARMONICNOTCH_ENABLED
#define AP_RPM_HARMONICNOTCH_ENABLED 0
#endif

#ifndef AP_RPM_PIN_ENABLED
#define AP_RPM_PIN_ENABLED 0
#endif

#ifndef AP_RPM_SIM_ENABLED
#define AP_RPM_SIM_ENABLED 0
#endif

#ifndef AP_RPM_STREAM_ENABLED
#define AP_RPM_STREAM_ENABLED 0
#endif

#ifndef AP_RSSI_ENABLED
#define AP_RSSI_ENABLED 0
#endif

#ifndef AP_RTC_ENABLED
#define AP_RTC_ENABLED 0
#endif

#ifndef AP_RTC_LOGGING_ENABLED
#define AP_RTC_LOGGING_ENABLED 0
#endif

#ifndef AP_SBUSOUTPUT_ENABLED
#define AP_SBUSOUTPUT_ENABLED 0
#endif

// bit special
#ifndef AP_SCHEDULER_ENABLED
#define AP_SCHEDULER_ENABLED 1
#endif

#ifndef AP_SCHEDULER_EXTENDED_TASKINFO_ENABLED
#define AP_SCHEDULER_EXTENDED_TASKINFO_ENABLED 0
#endif

#ifndef AP_SCRIPTING_BINDING_MOTORS_ENABLED
#define AP_SCRIPTING_BINDING_MOTORS_ENABLED 0
#endif

#ifndef AP_SCRIPTING_BINDING_VEHICLE_ENABLED
#define AP_SCRIPTING_BINDING_VEHICLE_ENABLED 0
#endif

#ifndef AP_SCRIPTING_CAN_SENSOR_ENABLED
#define AP_SCRIPTING_CAN_SENSOR_ENABLED 0
#endif

#ifndef AP_SCRIPTING_ENABLED
#define AP_SCRIPTING_ENABLED 0
#endif

#ifndef AP_SCRIPTING_SERIALDEVICE_ENABLED
#define AP_SCRIPTING_SERIALDEVICE_ENABLED 0
#endif

#ifndef AP_SDCARD_STORAGE_ENABLED
#define AP_SDCARD_STORAGE_ENABLED 0
#endif

#ifndef AP_SERIALLED_ENABLED
#define AP_SERIALLED_ENABLED 0
#endif

#ifndef AP_SERIALMANAGER_ENABLED
#define AP_SERIALMANAGER_ENABLED 1
#endif

#ifndef AP_SERIALMANAGER_IMUOUT_ENABLED
#define AP_SERIALMANAGER_IMUOUT_ENABLED 0
#endif

#ifndef AP_SERIALMANAGER_REGISTER_ENABLED
#define AP_SERIALMANAGER_REGISTER_ENABLED 0
#endif

#ifndef AP_SERVORELAYEVENTS_ENABLED
#define AP_SERVORELAYEVENTS_ENABLED 0
#endif

#ifndef AP_SERVO_TELEM_ENABLED
#define AP_SERVO_TELEM_ENABLED 0
#endif

#ifndef AP_SIM_ADSB_ENABLED
#define AP_SIM_ADSB_ENABLED 0
#endif

#ifndef AP_SIM_ADSB_SAGETECH_MXS_ENABLED
#define AP_SIM_ADSB_SAGETECH_MXS_ENABLED 0
#endif

#ifndef AP_SIM_AIRSIM_ENABLED
#define AP_SIM_AIRSIM_ENABLED 0
#endif

#ifndef AP_SIM_AIRSPEED_DLVR_ENABLED
#define AP_SIM_AIRSPEED_DLVR_ENABLED 0
#endif

#ifndef AP_SIM_AIS_ENABLED
#define AP_SIM_AIS_ENABLED 0
#endif

#ifndef AP_SIM_AS5600_ENABLED
#define AP_SIM_AS5600_ENABLED 0
#endif

#ifndef AP_SIM_BARO_ENABLED
#define AP_SIM_BARO_ENABLED 0
#endif

#ifndef AP_SIM_BATT_MONITOR_SMBUS_MAXELL_ENABLED
#define AP_SIM_BATT_MONITOR_SMBUS_MAXELL_ENABLED 0
#endif

#ifndef AP_SIM_BATT_MONITOR_SMBUS_ROTOYE_ENABLED
#define AP_SIM_BATT_MONITOR_SMBUS_ROTOYE_ENABLED 0
#endif

#ifndef AP_SIM_COMPASS_BACKEND_DEFAULT_ENABLED
#define AP_SIM_COMPASS_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_SIM_COMPASS_QMC5883L_ENABLED
#define AP_SIM_COMPASS_QMC5883L_ENABLED 0
#endif

#ifndef AP_SIM_CRRCSIM_ENABLED
#define AP_SIM_CRRCSIM_ENABLED 0
#endif

#ifndef AP_SIM_CRSF_ENABLED
#define AP_SIM_CRSF_ENABLED 0
#endif

#ifndef AP_SIM_ENABLED
#define AP_SIM_ENABLED 0
#endif

#ifndef AP_SIM_FLIGHTAXIS_ENABLED
#define AP_SIM_FLIGHTAXIS_ENABLED 0
#endif

#ifndef AP_SIM_FRAME_COPTER_DOTRIACONTA_OCTAQUAD_X_ENABLED
#define AP_SIM_FRAME_COPTER_DOTRIACONTA_OCTAQUAD_X_ENABLED 0
#endif

#ifndef AP_SIM_FRAME_DEFAULT_ENABLED
#define AP_SIM_FRAME_DEFAULT_ENABLED 0
#endif

#ifndef AP_SIM_GAZEBO_ENABLED
#define AP_SIM_GAZEBO_ENABLED 0
#endif

#ifndef AP_SIM_GIMBAL_ENABLED
#define AP_SIM_GIMBAL_ENABLED 0
#endif

#ifndef AP_SIM_GLIDER_ENABLED
#define AP_SIM_GLIDER_ENABLED 0
#endif

#ifndef AP_SIM_GPIO_LED_1_ENABLED
#define AP_SIM_GPIO_LED_1_ENABLED 0
#endif

#ifndef AP_SIM_GPIO_LED_2_ENABLED
#define AP_SIM_GPIO_LED_2_ENABLED 0
#endif

#ifndef AP_SIM_GPIO_LED_3_ENABLED
#define AP_SIM_GPIO_LED_3_ENABLED 0
#endif

#ifndef AP_SIM_GPIO_LED_RGB_ENABLED
#define AP_SIM_GPIO_LED_RGB_ENABLED 0
#endif

#ifndef AP_SIM_GPS_BACKEND_DEFAULT_ENABLED
#define AP_SIM_GPS_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_SIM_GPS_ENABLED
#define AP_SIM_GPS_ENABLED 0
#endif

#ifndef AP_SIM_GPS_FILE_ENABLED
#define AP_SIM_GPS_FILE_ENABLED 0
#endif

#ifndef AP_SIM_GPS_MSP_ENABLED
#define AP_SIM_GPS_MSP_ENABLED 0
#endif

#ifndef AP_SIM_GPS_NMEA_ENABLED
#define AP_SIM_GPS_NMEA_ENABLED 0
#endif

#ifndef AP_SIM_GPS_NOVA_ENABLED
#define AP_SIM_GPS_NOVA_ENABLED 0
#endif

#ifndef AP_SIM_GPS_SBF_ENABLED
#define AP_SIM_GPS_SBF_ENABLED 0
#endif

#ifndef AP_SIM_GPS_SBP2_ENABLED
#define AP_SIM_GPS_SBP2_ENABLED 0
#endif

#ifndef AP_SIM_GPS_SBP_ENABLED
#define AP_SIM_GPS_SBP_ENABLED 0
#endif

#ifndef AP_SIM_GPS_TRIMBLE_ENABLED
#define AP_SIM_GPS_TRIMBLE_ENABLED 0
#endif

#ifndef AP_SIM_GPS_UBLOX_ENABLED
#define AP_SIM_GPS_UBLOX_ENABLED 0
#endif

#ifndef AP_SIM_ICM40609_ENABLED
#define AP_SIM_ICM40609_ENABLED 0
#endif

#ifndef AP_SIM_INA3221_ENABLED
#define AP_SIM_INA3221_ENABLED 0
#endif

#ifndef AP_SIM_INS_ENABLED
#define AP_SIM_INS_ENABLED 0
#endif

#ifndef AP_SIM_INS_FILE_ENABLED
#define AP_SIM_INS_FILE_ENABLED 0
#endif

#ifndef AP_SIM_IS31FL3195_ENABLED
#define AP_SIM_IS31FL3195_ENABLED 0
#endif

#ifndef AP_SIM_JEDEC_ENABLED
#define AP_SIM_JEDEC_ENABLED 0
#endif

#ifndef AP_SIM_JEDEC_MX25L3206E_ENABLED
#define AP_SIM_JEDEC_MX25L3206E_ENABLED 0
#endif

#ifndef AP_SIM_JSBSIM_ENABLED
#define AP_SIM_JSBSIM_ENABLED 0
#endif

#ifndef AP_SIM_JSON_ENABLED
#define AP_SIM_JSON_ENABLED 0
#endif

#ifndef AP_SIM_JSON_MASTER_ENABLED
#define AP_SIM_JSON_MASTER_ENABLED 0
#endif

#ifndef AP_SIM_LAST_LETTER_ENABLED
#define AP_SIM_LAST_LETTER_ENABLED 0
#endif

#ifndef AP_SIM_LED_N_ENABLED
#define AP_SIM_LED_N_ENABLED 0
#endif

#ifndef AP_SIM_LM2755_ENABLED
#define AP_SIM_LM2755_ENABLED 0
#endif

#ifndef AP_SIM_LOWEHEISER_ENABLED
#define AP_SIM_LOWEHEISER_ENABLED 0
#endif

#ifndef AP_SIM_LP5562_ENABLED
#define AP_SIM_LP5562_ENABLED 0
#endif

#ifndef AP_SIM_MAXSONAR_I2C_XL_ENABLED
#define AP_SIM_MAXSONAR_I2C_XL_ENABLED 0
#endif

#ifndef AP_SIM_MORSE_ENABLED
#define AP_SIM_MORSE_ENABLED 0
#endif

#ifndef AP_SIM_MS5525_ENABLED
#define AP_SIM_MS5525_ENABLED 0
#endif

#ifndef AP_SIM_MS5611_ENABLED
#define AP_SIM_MS5611_ENABLED 0
#endif

#ifndef AP_SIM_PARAM_ENABLED
#define AP_SIM_PARAM_ENABLED 0
#endif

#ifndef AP_SIM_PS_LD06_ENABLED
#define AP_SIM_PS_LD06_ENABLED 0
#endif

#ifndef AP_SIM_PS_LIGHTWARE_ENABLED
#define AP_SIM_PS_LIGHTWARE_ENABLED 0
#endif

#ifndef AP_SIM_PS_LIGHTWARE_SF45B_ENABLED
#define AP_SIM_PS_LIGHTWARE_SF45B_ENABLED 0
#endif

#ifndef AP_SIM_PS_RPLIDARA1_ENABLED
#define AP_SIM_PS_RPLIDARA1_ENABLED 0
#endif

#ifndef AP_SIM_PS_RPLIDARA2_ENABLED
#define AP_SIM_PS_RPLIDARA2_ENABLED 0
#endif

#ifndef AP_SIM_PS_RPLIDARS2_ENABLED
#define AP_SIM_PS_RPLIDARS2_ENABLED 0
#endif

#ifndef AP_SIM_PS_TERARANGERTOWER_ENABLED
#define AP_SIM_PS_TERARANGERTOWER_ENABLED 0
#endif

#ifndef AP_SIM_RAMTRON_ENABLED
#define AP_SIM_RAMTRON_ENABLED 0
#endif

#ifndef AP_SIM_RAMTRON_FM25V02_ENABLED
#define AP_SIM_RAMTRON_FM25V02_ENABLED 0
#endif

#ifndef AP_SIM_RF_BENEWAKE_TFMINIPLUS_ENABLED
#define AP_SIM_RF_BENEWAKE_TFMINIPLUS_ENABLED 0
#endif

#ifndef AP_SIM_RF_DTS6012M_ENABLED
#define AP_SIM_RF_DTS6012M_ENABLED 0
#endif

#ifndef AP_SIM_RF_LIGHTWAREI2C_LEGACY16BIT_ENABLED
#define AP_SIM_RF_LIGHTWAREI2C_LEGACY16BIT_ENABLED 0
#endif

#ifndef AP_SIM_RF_LIGHTWAR_GRF250_ENABLED
#define AP_SIM_RF_LIGHTWAR_GRF250_ENABLED 0
#endif

#ifndef AP_SIM_SCRIMMAGE_ENABLED
#define AP_SIM_SCRIMMAGE_ENABLED 0
#endif

#ifndef AP_SIM_SERIALDEVICE_CORRUPTION_ENABLED
#define AP_SIM_SERIALDEVICE_CORRUPTION_ENABLED 0
#endif

#ifndef AP_SIM_SERIALPROXIMITYSENSOR_ENABLED
#define AP_SIM_SERIALPROXIMITYSENSOR_ENABLED 0
#endif

#ifndef AP_SIM_SHIP_ENABLED
#define AP_SIM_SHIP_ENABLED 0
#endif

#ifndef AP_SIM_SILENTWINGS_ENABLED
#define AP_SIM_SILENTWINGS_ENABLED 0
#endif

#ifndef AP_SIM_SLUNGPAYLOAD_ENABLED
#define AP_SIM_SLUNGPAYLOAD_ENABLED 0
#endif

#ifndef AP_SIM_SOLOGIMBAL_ENABLED
#define AP_SIM_SOLOGIMBAL_ENABLED 0
#endif

#ifndef AP_SIM_STRATOBLIMP_ENABLED
#define AP_SIM_STRATOBLIMP_ENABLED 0
#endif

#ifndef AP_SIM_TEMPERATURE_MCP9600_ENABLED
#define AP_SIM_TEMPERATURE_MCP9600_ENABLED 0
#endif

#ifndef AP_SIM_TEMPERATURE_SHT3X_ENABLED
#define AP_SIM_TEMPERATURE_SHT3X_ENABLED 0
#endif

#ifndef AP_SIM_TEMPERATURE_TSYS01_ENABLED
#define AP_SIM_TEMPERATURE_TSYS01_ENABLED 0
#endif

#ifndef AP_SIM_TERARANGERI2C_ENABLED
#define AP_SIM_TERARANGERI2C_ENABLED 0
#endif

#ifndef AP_SIM_TETHER_ENABLED
#define AP_SIM_TETHER_ENABLED 0
#endif

#ifndef AP_SIM_TFS20L_ENABLED
#define AP_SIM_TFS20L_ENABLED 0
#endif

#ifndef AP_SIM_TOSHIBALED_ENABLED
#define AP_SIM_TOSHIBALED_ENABLED 0
#endif

#ifndef AP_SIM_TSYS03_ENABLED
#define AP_SIM_TSYS03_ENABLED 0
#endif

#ifndef AP_SIM_VICON_ENABLED
#define AP_SIM_VICON_ENABLED 0
#endif

#ifndef AP_SIM_VOLZ_ENABLED
#define AP_SIM_VOLZ_ENABLED 0
#endif

#ifndef AP_SIM_WEBOTS_ENABLED
#define AP_SIM_WEBOTS_ENABLED 0
#endif

#ifndef AP_SIM_WEBOTSPYTHON_ENABLED
#define AP_SIM_WEBOTSPYTHON_ENABLED 0
#endif

#ifndef AP_SIM_WIND_SIMULATION_ENABLED
#define AP_SIM_WIND_SIMULATION_ENABLED 0
#endif

#ifndef AP_SIM_XPLANE_ENABLED
#define AP_SIM_XPLANE_ENABLED 0
#endif

#ifndef AP_SMARTAUDIO_ENABLED
#define AP_SMARTAUDIO_ENABLED 0
#endif

#ifndef AP_SOCKET_NATIVE_ENABLED
#define AP_SOCKET_NATIVE_ENABLED 0
#endif

#ifndef AP_SRV_CHANNELS_ENABLED
#define AP_SRV_CHANNELS_ENABLED 0
#endif

#ifndef AP_STATS_ENABLED
#define AP_STATS_ENABLED 0
#endif

#ifndef AP_SUB_RC_ENABLED
#define AP_SUB_RC_ENABLED 0
#endif

#ifndef AP_TEMPCALIBRATION_ENABLED
#define AP_TEMPCALIBRATION_ENABLED 0
#endif

#ifndef AP_TEMPERATURE_SENSOR_ANALOG_ENABLED
#define AP_TEMPERATURE_SENSOR_ANALOG_ENABLED 0
#endif

#ifndef AP_TEMPERATURE_SENSOR_BACKEND_DEFAULT_ENABLED
#define AP_TEMPERATURE_SENSOR_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_TEMPERATURE_SENSOR_DRONECAN_ENABLED
#define AP_TEMPERATURE_SENSOR_DRONECAN_ENABLED 0
#endif

#ifndef AP_TEMPERATURE_SENSOR_DUMMY_METHODS_ENABLED
#define AP_TEMPERATURE_SENSOR_DUMMY_METHODS_ENABLED 0
#endif

#ifndef AP_TEMPERATURE_SENSOR_ENABLED
#define AP_TEMPERATURE_SENSOR_ENABLED 0
#endif

#ifndef AP_TEMPERATURE_SENSOR_MAX31865_ENABLED
#define AP_TEMPERATURE_SENSOR_MAX31865_ENABLED 0
#endif

#ifndef AP_TEMPERATURE_SENSOR_MCP9600_ENABLED
#define AP_TEMPERATURE_SENSOR_MCP9600_ENABLED 0
#endif

#ifndef AP_TEMPERATURE_SENSOR_MLX90614_ENABLED
#define AP_TEMPERATURE_SENSOR_MLX90614_ENABLED 0
#endif

#ifndef AP_TEMPERATURE_SENSOR_SHT3X_ENABLED
#define AP_TEMPERATURE_SENSOR_SHT3X_ENABLED 0
#endif

#ifndef AP_TEMPERATURE_SENSOR_TSYS01_ENABLED
#define AP_TEMPERATURE_SENSOR_TSYS01_ENABLED 0
#endif

#ifndef AP_TEMPERATURE_SENSOR_TSYS03_ENABLED
#define AP_TEMPERATURE_SENSOR_TSYS03_ENABLED 0
#endif

#ifndef AP_TRACKER_SET_HOME_VIA_MISSION_UPLOAD_ENABLED
#define AP_TRACKER_SET_HOME_VIA_MISSION_UPLOAD_ENABLED 0
#endif

#ifndef AP_TRAMP_ENABLED
#define AP_TRAMP_ENABLED 0
#endif

#ifndef AP_TUNING_ENABLED
#define AP_TUNING_ENABLED 0
#endif

#ifndef AP_UART_MONITOR_ENABLED
#define AP_UART_MONITOR_ENABLED 0
#endif

#ifndef AP_VEHICLE_ENABLED
#define AP_VEHICLE_ENABLED 0
#endif

#ifndef AP_VIDEOTX_ENABLED
#define AP_VIDEOTX_ENABLED 0
#endif

#ifndef AP_VISUALODOM_BACKEND_DEFAULT_ENABLED
#define AP_VISUALODOM_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_VISUALODOM_INTELT265_ENABLED
#define AP_VISUALODOM_INTELT265_ENABLED 0
#endif

#ifndef AP_VISUALODOM_MAV_ENABLED
#define AP_VISUALODOM_MAV_ENABLED 0
#endif

#ifndef AP_VOLZ_ENABLED
#define AP_VOLZ_ENABLED 0
#endif

#ifndef AP_WATCHDOG_SAVE_FAULT_ENABLED
#define AP_WATCHDOG_SAVE_FAULT_ENABLED 1
#endif

#ifndef AP_WINCH_BACKEND_DEFAULT_ENABLED
#define AP_WINCH_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_WINCH_DAIWA_ENABLED
#define AP_WINCH_DAIWA_ENABLED 0
#endif

#ifndef AP_WINCH_ENABLED
#define AP_WINCH_ENABLED 0
#endif

#ifndef AP_WINCH_PWM_ENABLED
#define AP_WINCH_PWM_ENABLED 0
#endif

#ifndef AP_WINDVANE_AIRSPEED_ENABLED
#define AP_WINDVANE_AIRSPEED_ENABLED 0
#endif

#ifndef AP_WINDVANE_ANALOG_ENABLED
#define AP_WINDVANE_ANALOG_ENABLED 0
#endif

#ifndef AP_WINDVANE_BACKEND_DEFAULT_ENABLED
#define AP_WINDVANE_BACKEND_DEFAULT_ENABLED 0
#endif

#ifndef AP_WINDVANE_ENABLED
#define AP_WINDVANE_ENABLED 0
#endif

#ifndef AP_WINDVANE_HOME_ENABLED
#define AP_WINDVANE_HOME_ENABLED 0
#endif

#ifndef AP_WINDVANE_MODERNDEVICE_ENABLED
#define AP_WINDVANE_MODERNDEVICE_ENABLED 0
#endif

#ifndef AP_WINDVANE_NMEA_ENABLED
#define AP_WINDVANE_NMEA_ENABLED 0
#endif

#ifndef AP_WINDVANE_RPM_ENABLED
#define AP_WINDVANE_RPM_ENABLED 0
#endif

#ifndef AP_WINDVANE_SIM_ENABLED
#define AP_WINDVANE_SIM_ENABLED 0
#endif

/*
 * Some AP_*_ENABLED macros are derived in subsystem config headers from
 * more primitive feature toggles. Drop those derived names here so the
 * config headers can recompute them without macro redefinition warnings.
 */
#undef AP_AHRS_EXTERNAL_WIND_ESTIMATE_ENABLED
#undef AP_AHRS_POSITION_RESET_ENABLED
#undef AP_AIRSPEED_DUMMY_METHODS_ENABLED
#undef AP_AIRSPEED_MSP_ENABLED
#undef AP_AIS_DUMMY_METHODS_ENABLED
#undef AP_BARO_DRONECAN_ENABLED
#undef AP_BARO_MS56XX_ENABLED
#undef AP_BATTERY_AD7091R5_ENABLED
#undef AP_BATTERY_INA2XX_ENABLED
#undef AP_BATTERY_INA3221_ENABLED
#undef AP_BATTERY_LTC2946_ENABLED
#undef AP_BATTERY_OPTIONS_PARAM_ENABLED
#undef AP_BATTERY_SCRIPTING_ENABLED
#undef AP_BEACON_SITL_ENABLED
#undef AP_COMPASS_DRONECAN_ENABLED
#undef AP_COMPASS_EXTERNALAHRS_ENABLED
#undef AP_COMPASS_HMC5843_INTERNAL_BUS_PROBING_ENABLED
#undef AP_COMPASS_INTERNAL_BUS_PROBING_ENABLED
#undef AP_COMPASS_IST8310_EXTERNAL_BUS_PROBING_ENABLED
#undef AP_COMPASS_IST8310_INTERNAL_BUS_PROBING_ENABLED
#undef AP_COMPASS_LIS2MDL_EXTERNAL_BUS_PROBING_ENABLED
#undef AP_COMPASS_MSP_ENABLED
#undef AP_COMPASS_SITL_ENABLED
#undef AP_DAC_MCP40D1X_ENABLED
#undef AP_DAC_TIX3204_ENABLED
#undef AP_DDS_RC_PUB_ENABLED
#undef AP_EFI_SCRIPTING_ENABLED
#undef AP_FILESYSTEM_ESP32_ENABLED
#undef AP_FILESYSTEM_FILE_READING_ENABLED
#undef AP_FILESYSTEM_FILE_WRITING_ENABLED
#undef AP_FILESYSTEM_POSIX_ENABLED
#undef AP_INERTIALSENSOR_BATCHSAMPLER_ENABLED
#undef AP_INERTIALSENSOR_FAST_SAMPLE_WINDOW_ENABLED
#undef AP_KDECAN_ENABLED
#undef AP_LIGHTWARESERIAL_ENABLED
#undef AP_MAVLINKCAN_ENABLED
#undef AP_MAVLINK_FOLLOW_HANDLING_ENABLED
#undef AP_MAVLINK_MAV_CMD_SET_HAGL_ENABLED
#undef AP_MAVLINK_MSG_HIGHRES_IMU_ENABLED
#undef AP_MAVLINK_SET_GPS_GLOBAL_ORIGIN_MESSAGE_ENABLED
#undef AP_NETWORKING_CAPTURE_ENABLED
#undef AP_NETWORKING_ENABLED
#undef AP_NETWORKING_PPP_GATEWAY_ENABLED
#undef AP_NOTIFY_TONEALARM_ENABLED
#undef AP_OPTICALFLOW_HEREFLOW_ENABLED
#undef AP_OPTICALFLOW_MAV_ENABLED
#undef AP_OPTICALFLOW_SITL_ENABLED
#undef AP_OSD_CALLSIGN_FROM_SD_ENABLED
#undef AP_PARAM_STORAGE_BAK_ENABLED
#undef AP_PROXIMITY_MR72_DRIVER_ENABLED
#undef AP_RANGEFINDER_BENEWAKE_CAN_ENABLED
#undef AP_RANGEFINDER_BENEWAKE_TF02_ENABLED
#undef AP_RANGEFINDER_BENEWAKE_TF03_ENABLED
#undef AP_RANGEFINDER_BENEWAKE_TFMINI_ENABLED
#undef AP_RANGEFINDER_DRONECAN_ENABLED
#undef AP_RANGEFINDER_DTS6012M_ENABLED
#undef AP_RANGEFINDER_NRA24_CAN_ENABLED
#undef AP_RANGEFINDER_PWM_ENABLED
#undef AP_RANGEFINDER_SIM_ENABLED
#undef AP_SCRIPTING_CAN_SENSOR_ENABLED
#undef AP_SDCARD_STORAGE_ENABLED
#undef AP_SERIALMANAGER_IMUOUT_ENABLED
#undef AP_SERVO_TELEM_ENABLED
#undef AP_SIM_ADSB_ENABLED
#undef AP_SIM_ADSB_SAGETECH_MXS_ENABLED
#undef AP_SIM_AIRSIM_ENABLED
#undef AP_SIM_AIRSPEED_DLVR_ENABLED
#undef AP_SIM_AIS_ENABLED
#undef AP_SIM_AS5600_ENABLED
#undef AP_SIM_BATT_MONITOR_SMBUS_MAXELL_ENABLED
#undef AP_SIM_BATT_MONITOR_SMBUS_ROTOYE_ENABLED
#undef AP_SIM_COMPASS_BACKEND_DEFAULT_ENABLED
#undef AP_SIM_CRRCSIM_ENABLED
#undef AP_SIM_CRSF_ENABLED
#undef AP_SIM_FLIGHTAXIS_ENABLED
#undef AP_SIM_GAZEBO_ENABLED
#undef AP_SIM_GIMBAL_ENABLED
#undef AP_SIM_GLIDER_ENABLED
#undef AP_SIM_GPS_ENABLED
#undef AP_SIM_GPS_FILE_ENABLED
#undef AP_SIM_ICM40609_ENABLED
#undef AP_SIM_INA3221_ENABLED
#undef AP_SIM_IS31FL3195_ENABLED
#undef AP_SIM_JEDEC_ENABLED
#undef AP_SIM_JSBSIM_ENABLED
#undef AP_SIM_JSON_ENABLED
#undef AP_SIM_JSON_MASTER_ENABLED
#undef AP_SIM_LAST_LETTER_ENABLED
#undef AP_SIM_LED_N_ENABLED
#undef AP_SIM_LM2755_ENABLED
#undef AP_SIM_LP5562_ENABLED
#undef AP_SIM_MAXSONAR_I2C_XL_ENABLED
#undef AP_SIM_MORSE_ENABLED
#undef AP_SIM_MS5525_ENABLED
#undef AP_SIM_MS5611_ENABLED
#undef AP_SIM_RAMTRON_ENABLED
#undef AP_SIM_RF_BENEWAKE_TFMINIPLUS_ENABLED
#undef AP_SIM_RF_DTS6012M_ENABLED
#undef AP_SIM_RF_LIGHTWAREI2C_LEGACY16BIT_ENABLED
#undef AP_SIM_RF_LIGHTWAR_GRF250_ENABLED
#undef AP_SIM_SCRIMMAGE_ENABLED
#undef AP_SIM_SERIALPROXIMITYSENSOR_ENABLED
#undef AP_SIM_SHIP_ENABLED
#undef AP_SIM_SILENTWINGS_ENABLED
#undef AP_SIM_SLUNGPAYLOAD_ENABLED
#undef AP_SIM_SOLOGIMBAL_ENABLED
#undef AP_SIM_STRATOBLIMP_ENABLED
#undef AP_SIM_TEMPERATURE_MCP9600_ENABLED
#undef AP_SIM_TEMPERATURE_SHT3X_ENABLED
#undef AP_SIM_TEMPERATURE_TSYS01_ENABLED
#undef AP_SIM_TERARANGERI2C_ENABLED
#undef AP_SIM_TETHER_ENABLED
#undef AP_SIM_TFS20L_ENABLED
#undef AP_SIM_TOSHIBALED_ENABLED
#undef AP_SIM_TSYS03_ENABLED
#undef AP_SIM_WEBOTS_ENABLED
#undef AP_SIM_WEBOTSPYTHON_ENABLED
#undef AP_SIM_XPLANE_ENABLED
#undef AP_TEMPERATURE_SENSOR_DUMMY_METHODS_ENABLED

