#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_IRLOCK_ENABLED
#define AP_IRLOCK_ENABLED 1
#endif  // AP_IRLOCK_ENABLED

#ifndef AP_IRLOCK_BACKEND_DEFAULT_ENABLED
#define AP_IRLOCK_BACKEND_DEFAULT_ENABLED AP_IRLOCK_ENABLED
#endif  // AP_IRLOCK_BACKEND_DEFAULT_ENABLED

#ifndef AP_IRLOCK_I2C_ENABLED
#define AP_IRLOCK_I2C_ENABLED AP_IRLOCK_BACKEND_DEFAULT_ENABLED
#endif  // AP_IRLOCK_I2C_ENABLED

#ifndef AP_IRLOCK_SITL_ENABLED
#define AP_IRLOCK_SITL_ENABLED AP_IRLOCK_BACKEND_DEFAULT_ENABLED && (CONFIG_HAL_BOARD == HAL_BOARD_SITL)
#endif  // AP_IRLOCK_SITL_ENABLED

#ifndef AP_IRLOCK_SITL_GAZEBO_ENABLED
#define AP_IRLOCK_SITL_GAZEBO_ENABLED AP_IRLOCK_BACKEND_DEFAULT_ENABLED && (CONFIG_HAL_BOARD == HAL_BOARD_SITL)
#endif  // AP_IRLOCK_SITL_GAZEBO_ENABLED
