#!/usr/bin/env python3
# AP_FLAKE8_CLEAN


def build(bld):
    bld.ap_program(
        # Keep the normal artifact names for Tools/scripts/build_bootloaders.py.
        program_name='AP_Bootloader',
        program_groups='bootloader',
        use=[],
        use_legacy_defines=False,
    )
