#pragma once

using namespace SITL;

#define MOT_1_ROLL_FACTOR 0.0
#define MOT_1_PITCH_FACTOR 0.0
#define MOT_1_YAW_FACTOR 1.0
#define MOT_1_THROTTLE_FACTOR 0.0
#define MOT_1_FORWARD_FACTOR -1
#define MOT_1_STRAFE_FACTOR 1

//Front left
#define MOT_2_ROLL_FACTOR 0.0
#define MOT_2_PITCH_FACTOR 0.0
#define MOT_2_YAW_FACTOR -1.0
#define MOT_2_THROTTLE_FACTOR 0.0
#define MOT_2_FORWARD_FACTOR -1
#define MOT_2_STRAFE_FACTOR -1

//Back right
#define MOT_3_ROLL_FACTOR 0
#define MOT_3_PITCH_FACTOR 0
#define MOT_3_YAW_FACTOR -1.0
#define MOT_3_THROTTLE_FACTOR 0.0
#define MOT_3_FORWARD_FACTOR 1
#define MOT_3_STRAFE_FACTOR 1

//Back left
#define MOT_4_ROLL_FACTOR 0
#define MOT_4_PITCH_FACTOR 0
#define MOT_4_YAW_FACTOR 1.0
#define MOT_4_THROTTLE_FACTOR 0.0
#define MOT_4_FORWARD_FACTOR 1
#define MOT_4_STRAFE_FACTOR -1

//Right facing up
#define MOT_5_ROLL_FACTOR 1.0
#define MOT_5_PITCH_FACTOR 0.0
#define MOT_5_YAW_FACTOR 0.0
#define MOT_5_THROTTLE_FACTOR -1
#define MOT_5_FORWARD_FACTOR 0.0
#define MOT_5_STRAFE_FACTOR 0.0

//Left facing up
#define MOT_6_ROLL_FACTOR -1.0
#define MOT_6_PITCH_FACTOR 0.0
#define MOT_6_YAW_FACTOR 0.0
#define MOT_6_THROTTLE_FACTOR -1
#define MOT_6_FORWARD_FACTOR 0.0
#define MOT_6_STRAFE_FACTOR 0.0
