#pragma once

#include <AP_BoardConfig/AP_BoardConfig.h>

#ifndef HAL_LANDING_DEEPSTALL_ENABLED
#define HAL_LANDING_DEEPSTALL_ENABLED (BOARD_FLASH_SIZE > 1024)
#endif

#ifndef AP_LANDING_PARAM_LAND_DISARMDELAY_DEFAULT
#if CONFIG_HAL_BOARD == HAL_BOARD_SITL
#define AP_LANDING_PARAM_LAND_DISARMDELAY_DEFAULT 3
#else
#define AP_LANDING_PARAM_LAND_DISARMDELAY_DEFAULT 20
#endif
#endif
