#!/usr/bin/env python3
# AP_FLAKE8_CLEAN
"""Filter a Zephyr-generated zephyr.dts (with provenance comments) down to
only the content contributed by OUR tree (AP_HAL_Zephyr), keeping enclosing
node structure for readability. Upstream-only nodes/properties are dropped."""
import re
import sys

src, dst = sys.argv[1], sys.argv[2]
lines = open(src).read().splitlines()

OURS = 'AP_HAL_Zephyr'

# classify each line: 'ours' if its provenance comment references our tree
prov_re = re.compile(r'/\*\s*(?:in|node .* defined in)\s+(\S+?):?\d*\s*\*/')

n = len(lines)
keep = [False] * n
stack = []            # indices of currently-open block lines
opens_ours = [False] * n

for i, ln in enumerate(lines):
    stripped = ln.strip()
    m = prov_re.search(ln)
    is_ours = bool(m and OURS in m.group(1))
    if stripped.endswith('{'):
        stack.append(i)
        opens_ours[i] = is_ours
        if is_ours:
            keep[i] = True
    elif stripped.startswith('};') or stripped == '}':
        if stack:
            stack.pop()
    else:
        if is_ours:
            keep[i] = True
            for a in stack:      # keep all ancestors of a kept line
                keep[a] = True

# node-comment lines directly above kept node-opening lines
for i, ln in enumerate(lines):
    if keep[i] and ln.strip().endswith('{'):
        j = i - 1
        while j >= 0 and lines[j].strip().startswith('/*'):
            if 'AP_HAL_Zephyr' in lines[j]:
                keep[j] = True
            j -= 1

# second pass: keep closing braces matching kept opens
stack = []
for i, ln in enumerate(lines):
    stripped = ln.strip()
    if stripped.endswith('{'):
        stack.append(i)
    elif stripped.startswith('};') or stripped == '}':
        if stack:
            o = stack.pop()
            if keep[o]:
                keep[i] = True

out = [lines[i] for i in range(n) if keep[i]]
header = [
    '/* FILTERED VIEW - NOT A BUILDABLE DTS.',
    ' * %s reduced to only the content contributed by this' % src.split('/')[-1],
    ' * repository (provenance comments referencing AP_HAL_Zephyr): the board',
    ' * DTS, our pinctrl dtsi and any overlays. All purely-upstream',
    ' * (modules/zephyr) nodes and properties removed; upstream-defined nodes',
    ' * are kept only as skeletons where our files add or override properties',
    ' * inside them. Generated by dts_ours_only.py.',
    ' */',
    '',
]
open(dst, 'w').write('\n'.join(header + out) + '\n')
print('%s: %d -> %d lines' % (dst, n, len(out)))
