def build(bld):
    bld(
        name = "AP_RangeFinder",
        target = 'AP_RangeFinder',
        source = [
            'AP_RangeFinder.cpp',
            'AP_RangeFinder_UPFLOW_TOF.cpp',
        ],
        uselib = [
            'AP_OpticalFlow',
            'AP_HAL',
            'AP_Param',
        ],
        includes = [
            '.',
            '../AP_HAL',
        ],
        install = False,
    )
