#!/usr/bin/env python3

import os


def build(bld):

    if bld.env.BOARD != 'sitl':
        return

    lib_node = bld.bldnode.make_node(os.path.join('lib', 'libAP_FW_Controller_test_libs.a'))
    if lib_node.exists():
        lib_node.delete()

    bld.ap_stlib(
        name='AP_FW_Controller_test_libs',
        ap_vehicle='UNKNOWN',
        ap_libraries=bld.ap_common_vehicle_libraries() + [
            'SITL',
            'APM_Control',
            'AP_AdvancedFailsafe',
            'AP_Avoidance',
        ],
    )

    bld.ap_program(
        use='AP_FW_Controller_test_libs',
        program_groups=['examples'],
    )
