#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#include <AP_Mission/AP_Mission_config.h>

#if HAL_OS_POSIX_IO || HAL_OS_FATFS_IO
#define HAVE_FILESYSTEM_SUPPORT 1
#else
#define HAVE_FILESYSTEM_SUPPORT 0
#endif

#ifndef AP_FILESYSTEM_PARAM_ENABLED
#define AP_FILESYSTEM_PARAM_ENABLED 1
#endif

#ifndef AP_FILESYSTEM_MISSION_ENABLED
#define AP_FILESYSTEM_MISSION_ENABLED AP_MISSION_ENABLED
#endif

#ifndef AP_FILESYSTEM_SYS_ENABLED
#define AP_FILESYSTEM_SYS_ENABLED 1
#endif

#ifndef AP_FILESYSTEM_ROMFS_ENABLED
#define AP_FILESYSTEM_ROMFS_ENABLED defined(HAL_HAVE_AP_ROMFS_EMBEDDED_H)
#endif
