name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install --upgrade pip
      - run: pip install MAVProxy numpy pexpect pytest setuptools
      - run: pip install --editable modules/DroneCAN/pydronecan
      - run: pip install --editable modules/mavlink/pymavlink
      - run: pytest --ignore=modules/gtest
                    --ignore=modules/mavlink/pymavlink/generator/C/test/posix/sha256_test.py
                    --ignore=modules/mavlink/pymavlink/tests/test_wp.py
                    --ignore=modules/waf
                    --ignore=Tools/FilterTestTool
                    --ignore=Tools/ros2/ardupilot_dds_tests/test
