name: Sunfish CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Upload firmware to Google Drive
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        run: |
          NOW=$(date -u +"%F-%T")
          echo "timestamp=${NOW}" >> $GITHUB_OUTPUT
      - name: ccache cache files
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{github.workflow}}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}
          restore-keys: ${{github.workflow}}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}  # restore ccache from either previous build on this branch or on master
      - name: setup ccache
        run: |
          . .github/workflows/ccache.env
      - name: Install Dependencies
        run: Tools/environment_install/install-prereqs-ubuntu.sh
      - name: Build
        run: . ~/.profile && make sunfish
      - name: Upload binaries to Google Drive
        uses: adityak74/google-drive-upload-git-action@v0.3
        with:
          credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          filename: build/sunfish/*
