name: test scripting

on:
  push:
    paths: # only run for scripting changes
      - 'libraries/AP_Scripting/tests/docs_check.py'
      - 'libraries/AP_Scripting/generator/**'
      - '**.lua'
      - 'Tools/scripts/run_lua_language_check.py'
      - 'Tools/scripts/run_luacheck.sh'
      - 'Tools/scripts/generate_lua_docs.sh'
      - '.github/workflows/test_scripting.yml'

  pull_request:
    paths: # only run for scripting changes
      - 'libraries/AP_Scripting/tests/docs_check.py'
      - 'libraries/AP_Scripting/generator/**'
      - '**.lua'
      - 'Tools/scripts/run_lua_language_check.py'
      - 'Tools/scripts/run_luacheck.sh'
      - 'Tools/scripts/generate_lua_docs.sh'
      - '.github/workflows/test_scripting.yml'

  workflow_dispatch:

concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-scripting:
    runs-on: ubuntu-slim
    steps:
      # git checkout the PR
      - uses: actions/checkout@v6
        with:
          submodules: false
          persist-credentials: false

      - name: Register lua check problem matcher
        run: |
          echo "::add-matcher::.github/problem-matchers/Lua.json"
          echo "::remove-matcher owner=Lua-language-server-problem-matcher::"

      - name: Lua Linter
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get -y install lua-check
          ./Tools/scripts/run_luacheck.sh

      - name: Register lua language server problem matcher
        run: |
          echo "::add-matcher::.github/problem-matchers/Lua.json"
          echo "::remove-matcher owner=Luacheck-problem-matcher::"

      - name: Language server check
        shell: bash
        run: |
          python3 -m pip install github-release-downloader
          python3 ./Tools/scripts/run_lua_language_check.py --debugLogging

      - name: Remove problem matchers
        run: |
          echo "::remove-matcher owner=Luacheck-problem-matcher::"
          echo "::remove-matcher owner=Lua-language-server-problem-matcher::"

      - name: Generate lua markdown API docs
        shell: bash
        run: |
          ./Tools/scripts/generate_lua_docs.sh

      - name: Copy current lua docs
        run: |
          PATH="/github/home/.local/bin:$PATH"
          mv "libraries/AP_Scripting/docs/docs.lua" "libraries/AP_Scripting/docs/current_docs.lua"

      - name: ReGenerate lua docs and annotations from code
        shell: bash
        run: |
          ./waf configure
          ./waf scripting_docs

      - name: Compare Previous and current lua docs
        run: |
          PATH="/github/home/.local/bin:$PATH"
          python ./libraries/AP_Scripting/tests/docs_check.py "./libraries/AP_Scripting/docs/docs.lua" "./libraries/AP_Scripting/docs/current_docs.lua"

      - name: Upload docs
        uses: actions/upload-artifact@v7
        with:
          name: Docs
          path: ScriptingDocs.md
          retention-days: 7
