name: test size

on:
  pull_request:
    paths-ignore:  # ignore autotest stuffs
      - 'Tools/autotest/**'
      # Remove markdown files as irrelevant
      - '**.md'
      # Remove dotfile at root directory
      - './.dir-locals.el'
      - './.dockerignore'
      - './.editorconfig'
      - './.flake8'
      - './.gitattributes'
      - './.github'
      - './.gitignore'
      - './.pre-commit-config.yaml'
      - './.pydevproject'
      - './.valgrind-suppressions'
      - './.valgrindrc'
      - 'Dockerfile'
      - 'Vagrantfile'
      - 'Makefile'
      # Remove some directories check
      - '.vscode/**'
      - '.github/ISSUE_TEMPLATE/**'
      # Remove generic tools
      - 'Tools/CHDK-Script/**'
      - 'Tools/CodeStyle/**'
      - 'Tools/completion/**'
      - 'Tools/CPUInfo/**'
      - 'Tools/debug/**'
      - 'Tools/environment_install/**'
      - 'Tools/FilterTestTool/**'
      - 'Tools/geotag/**'
      - 'Tools/GIT_Test/**'
      - 'Tools/gittools/**'
      - 'Tools/Hello/**'
      - 'Tools/Linux_HAL_Essentials/**'
      - 'Tools/mavproxy_modules/**'
      - 'Tools/Pozyx/**'
      - 'Tools/PrintVersion.py'
      - 'Tools/simulink/**'
      - 'Tools/UDP_Proxy/**'
      - 'Tools/vagrant/**'
      - 'Tools/Vicon/**'
      # remove non CHIBIOS HAL
      - 'libraries/AP_HAL_SITL/**'
      - 'libraries/AP_HAL_ESP32/**'
      - 'libraries/AP_HAL_Linux/**'
      # Remove change on other workflows
      - '.github/workflows/test_environment.yml'
  workflow_dispatch:


concurrency:
  group: ci-${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ardupilot/ardupilot-dev-chibios:v0.1.3
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        run: |
          NOW=$(date -u +"%F-%T")
          echo "timestamp=${NOW}" >> $GITHUB_OUTPUT

      - name: ccache cache files
        uses: actions/cache@v5
        with:
          path: ~/.ccache
          key: ${{github.workflow}}-ccache-${{steps.ccache_cache_timestamp.outputs.timestamp}}
          restore-keys: ${{github.workflow}}-ccache-

      - name: setup ccache
        run: |
          . .github/workflows/ccache.env

      - name: Compare sizes and features
        shell: bash
        run: |
          apt-get update && apt-get install -y rsync
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          BOARDS="Durandal,"
          BOARDS+="MatekF405,"
          BOARDS+="KakuteF7,"
          BOARDS+="MatekH743-bdshot,"
          BOARDS+="MambaH743v4,"
          BOARDS+="Pixhawk1-1M,"
          BOARDS+="MatekF405-CAN,"
          BOARDS+="DrotekP3Pro,"
          BOARDS+="Hitec-Airspeed,"
          BOARDS+="f103-GPS"
          python3 Tools/scripts/size_compare_branches.py \
            --master-branch "${{ github.event.pull_request.base.ref }}" \
            --board "$BOARDS" \
            --all-vehicles \
            --features \
            --no-merge-base \
             | tee /tmp/scb_output.txt
          echo "### Size and Feature Comparison" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat /tmp/scb_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
