/*
 * Copyright (C) 2016 Intel Corporation. All rights reserved.
 *
 * Based on a file auto-generated by the fastcdrgen tool with the following
 * Copyright and license:
 * Copyright (C) 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#include <string>
#include <functional>

#include <fastrtps/fastrtps_fwd.h>
#include <fastrtps/subscriber/SubscriberListener.h>

#include "RTPSPubSubType.h"

template <class State>
class RTPSIsolatedSubscriber {
public:
    RTPSIsolatedSubscriber() {}
    ~RTPSIsolatedSubscriber();

    bool init(const std::string& subscriber, const std::string& topic,
        std::function<void(State)> on_new_message_);

private:
    class SubListener : public eprosima::fastrtps::SubscriberListener {
    public:
        void onSubscriptionMatched(eprosima::fastrtps::Subscriber* sub,
            eprosima::fastrtps::rtps::MatchingInfo& info);
        void onNewDataMessage(eprosima::fastrtps::Subscriber* sub);

        std::function<void(State)> on_new_message;

        int n_matched{0};
    } listener;

    eprosima::fastrtps::Participant* participant{nullptr};
    eprosima::fastrtps::Subscriber* subscriber{nullptr};

    RTPSPubSubType<State> *type{nullptr};
};
