#!/bin/bash
# Interactive guide to extract key from secure storage

echo "=========================================="
echo "Key Extraction Guide"
echo "=========================================="
echo ""
echo "The encryption key is stored in firmware's secure storage."
echo ""
echo "Storage Location:"
echo "  - Area: StorageManager::StorageKeys"
echo "  - Offset: 8064 (or 8128) within total storage"
echo "  - Size: 40 bytes"
echo ""
echo "Format:"
echo "  [0-3]   Magic: 0x43525950 ('CRYP')"
echo "  [4-7]   Version: 1"
echo "  [8-39]  32-byte encryption key"
echo ""
echo "=========================================="
echo "Extraction Methods:"
echo "=========================================="
echo ""
echo "1. DEBUGGER (GDB/OpenOCD):"
echo "   (gdb) dump binary memory storage_block.bin <ADDRESS> <ADDRESS+40>"
echo ""
echo "2. STORAGE DUMP FILE:"
echo "   dd if=storage_dump.bin of=storage_block.bin bs=1 skip=8064 count=40"
echo ""
echo "3. FIRMWARE MODIFICATION (temporary):"
echo "   Add debug code to output key to console"
echo ""
echo "4. PHYSICAL ACCESS:"
echo "   Use EEPROM/flash programmer to read storage"
echo ""
echo "=========================================="
echo "After Extraction:"
echo "=========================================="
echo ""
echo "1. View the key:"
echo "   python3 view_stored_key.py storage_block.bin"
echo ""
echo "2. Decrypt files:"
echo "   python3 encrypt_decrypt_files.py decrypt file.tlog output.log --key <base64url_key>"
echo ""
echo "See HOW_TO_GET_KEY_FROM_STORAGE.md for detailed instructions."





