#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := arducopter
BUILD_DIR_BASE = ../../../build/esp32/idf-copter

include $(IDF_PATH)/make/project.mk

